### ISSUE TITLE
Half of the user commands lacks argument checking

### ISSUE THREAD

**Issue by mossarelli** [sopel-irc/sopel#1001]
And there's no guidelines for how each function ends. So I have to add:

```
if not trigger.group(2):
        bot.say("Use the command like this: .kickban [#chan] user1 user!*@* message")
        return
```

To every command in the standard module's library.

Test: .movie
Bot says nothing.

Todo:
Standardize argument checking. Use @example as return message or use the example in the comment section of the commands. Every command that takes argument should tell the user when there is no arguments.

Thank you.

**Comment by thomastanck** [comment]
Perhaps a @arguments decorator that modifies the way rules are processed?
```python
@commands('test')
@arguments('\W*', '\W*')
def fancy_test(bot, trigger):
    print('%s tests %s' % (trigger.group(1), trigger.group(2))
```
See ```sopel.tools.get_command_regex``` in tools/__init__.py to see the current commands-->rules conversion that's done internally.

**Comment by embolalia** [comment]
I've been thinking for a while of doing something similar to [docopt](http://docopt.org/), which is fairly similar to your suggestion @thomastanck. You would only need to specify the usage, and it'd figure out the command and arguments from there. Parsing it and designing good semantics for this context is non-trivial, but it's on the list of things to do.

**Comment by thomastanck** [comment]
Why not actually use docopt? We can pass in the args into the docopt function
```python
docopt(usagestr, argv=args_here)
```

```python
# will create a callable similar to
# @rule('\.test (.*)')
@usage("""Usage:
.test <tester> <testee>...
.test vigorously <tester> <testee>""")
def fancy_test(bot, trigger):
    # if it doesn't match the usage, fancy_test doesn't get called.
    tester = trigger.docopt.tester
    testee = trigger.docopt.testee # testee is a list because of the ellipsis in the first command
    if trigger.docopt.vigorously == True:
        print('%s tests %s vigorously' % (tester, testee[0])
    else:
        for t in testee:
            print('%s tests %s' % (tester, t))
```

**Comment by thomastanck** [comment]
Got a mock working

```python
# coding=utf-8

from __future__ import unicode_literals, absolute_import, print_function, division

from docopt import docopt

from sopel.module import rule

@rule('\.test.*')
def test(bot, trigger):
    print('matched')
    print(trigger.group(0))
    print(trigger.group(0).split(' '))
    usage = str('''Usage:
    .test vigorously <tester> <testee>
    .test <tester> <testee>...''')
    try:
        docopt_output = docopt(usage, argv=[str(e) for e in trigger.group(0).split(' ')[1:]], help=True)
    except:
        for line in usage.split('\n'):
            bot.say(line)
        raise
    print("docopt_output: '" + str(docopt_output) + "'")
    tester = docopt_output['<tester>']
    testee = docopt_output['<testee>'] # testee is a list because of the ellipsis in the first command
    if docopt_output['vigorously'] == True:
        bot.say('%s tests %s vigorously' % (tester, testee[0]))
    else:
        for t in testee:
            bot.say('%s tests %s' % (tester, t))
    bot.say('done')

```

Testing:
```
13:07:06 me: .test
13:07:07 testbot: Usage:
13:07:07 testbot:    .test vigorously <tester> <testee>
13:07:08 testbot:    .test <tester> <testee>...
13:07:10 me: .test hey
13:07:11 testbot: Usage:
13:07:12 testbot:    .test vigorously <tester> <testee>
13:07:13 testbot:    .test <tester> <testee>...
13:07:14 me: .test hey there
13:07:15 testbot: hey tests there
13:07:16 testbot: done
13:07:18 me: .test hey there delilah
13:07:19 testbot: hey tests there
13:07:20 testbot: hey tests delilah
13:07:21 testbot: done
13:07:26 me: .test vigorously hey
13:07:27 testbot: vigorously tests hey
13:07:28 testbot: done
13:07:30 me: .test vigorously hey there
13:07:31 testbot: hey tests there vigorously
13:07:32 testbot: done
13:07:34 me: .test vigorously hey there delilah
13:07:34 testbot: vigorously tests hey
13:07:35 testbot: vigorously tests there
13:07:36 testbot: vigorously tests delilah
13:07:37 testbot: done
```

Only problem is that i couldn't get docopt to work well with unicode strings. Since we future import unicode_literals, i had to encase the strings with str(). This could be a problem in IRC where things can potentially be unicode.

**Comment by embolalia** [comment]
The problem with docopt is that it requires multiline usage strings. This is fairly spammy over IRC, especially when there are multiple patterns. Restricting it to a single line does limit the possibilities somewhat, but we get something more fitting for our use case. I'm also hesitant to bring in `--option` syntax, since it's inconsistent with everything else, and I think probably encourages commands to be more complex. (There's a certain irony in using "less is more" as an argument against including unixy commands, but I think it's valid.) Lastly, I want to avoid dependency creep, especially in things a lot of modules will rely on. It's one thing with `requests` (and, likely "soon", `sqlalchemy`), which is stable, near-standard, and does exactly what we need it to do. But docopt is relatively uncommon and hasn't hit its 1.0 yet, on top of being slightly different from what I think we want, so it's not something I'd like to rely on.

**Comment by thomastanck** [comment]
@embolalia Makes sense. Also you can see from the mock that docopt doesn't even handle unicode that well. We'd probably want to make a similar, simpler and narrower scope version of docopt.

**Comment by dgw** [comment]
This would be a great "check all the things" project for 7.1, along with #709.
