### ISSUE TITLE
Geo Locator broken? (.weather, .setlocation)

### ISSUE THREAD

**Issue by iampureevil** [sopel-irc/sopel#1006]
.weather seems to now fail, potentially due to the Yahoo placefinder service shut down? Any alternatives that can be used?

**Comment by hughes** [comment]
Also noticed this today. Super annoying!

**Comment by yoosi** [comment]
.time is also affected

**Comment by embolalia** [comment]
@yoosi time is not affected by this. I saw in #sopel you were trying to do `.time london` - this has never worked. The time zone must be an IANA one, like from [here](http://sopel.chat/tz).

**Comment by yoosi** [comment]
@embolalia You are right. My mistake.

**Comment by ridelore** [comment]
.weather works if you had your location set already though.


14:07 <@Phixion> .wea
14:07 <+Willie> Yahoo! Weather - Munich, DE: Fair, 3°C (37°F), Humidity: 81%, Light breeze 2.7m/s (↗)
14:07 <@Phixion> .wea London
14:07 <+Willie> Phixion: I don't know where that is.

**Comment by iampureevil** [comment]
That's correct. It's the polling of the WOEID that fails, as Yahoo shut down their service for this. I am trying to re-write, but using Yahoo would involve using an API code which is limited to 2k pulls per day.

**Comment by iampureevil** [comment]
I did manage to fix this by changing a few things up, however it will require getting a Yahoo API key. 

(I am not a great Python coder, so I am sure there is plenty of room for improvement)





[weather.txt](https://github.com/sopel-irc/sopel/files/103652/weather.txt)

**Comment by spichugin** [comment]
After a "pip install sopel" fresh installation, there is still the problem.

18:42 < my_nick> .version
18:42 < bot_nick> my_nick: Sopel v. 6.2.1
18:47 < my_nick> .weather London
18:47 < bot_nick> my_nick: I don't know where that is.

/usr/lib/python2.7/site-packages/sopel/modules/weather.py contains a code without the commit.

**Comment by maxpowa** [comment]
@spichugin You have to update from github. 6.2.1 was released before this issue was fixed.

**Comment by antdude** [comment]
Thank you for fixing v6.3.0. However, is this normal to show up everytime weather command is used?

$ Function get is deprecated.
  File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/weather.py", line 133, in weather
    first_result = woeid_search(location)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/weather.py", line 21, in woeid_search
    dont_decode=True)
Function get is deprecated.
  File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/weather.py", line 142, in weather
    dont_decode=True)

**Comment by maxpowa** [comment]
Yes, because web.py is deprecated. The function still works fine it just spits that out in the log. weather.py will most likely be switched to use requests before the next release.
