### ISSUE TITLE
help command returns ValueError after multiple times of running help or within 24h

### ISSUE THREAD

**Issue by eanxgeek** [sopel-irc/sopel#1008]
When running help (or .commands) we'll get the expected results for several runs; however, after a number of runs (or within 24 hours, which ever comes first) help (and .commands) will start to return a ValueError.

> ValueError: max() arg is an empty sequence (file "/usr/lib/python2.7/site-packages/sopel/modules/help.py", line 53, in help)

Running 6.2.1

**Comment by maxpowa** [comment]
Are you running `.reload` at all between this working and not working?

**Comment by eanxgeek** [comment]
I have tried to run .reload when the problem surfaces, to try and correct.  .reload does not fix the issue, I must kill sopel and restart.

Aside from that, I do run .reload on occasion but not often enough to notice if there some relation between .reload and help failing.

**Comment by thomastanck** [comment]
Incidentally, the line where the error occurs, line 53 in help, uses bot.command_groups, which needs to be deprecated.
```python
53:        name_length = max(6, max(len(k) for k in bot.command_groups.keys()))
54:        for category, cmds in collections.OrderedDict(sorted(bot.command_groups.items())).items():
```

**Comment by Guyverix** [comment]
I have also found this to happen on my installation with version 6.2.1 if that helps at all.  Exact same point and error.  Reload does not fix the issue.  A full restart of the daemon is required..

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/usr/local/lib/python2.7/dist-packages/sopel/modules/help.py", line 53, in help
    name_length = max(6, max(len(k) for k in bot.command_groups.keys()))
ValueError: max() arg is an empty sequence

**Comment by mossarelli** [comment]
I ran `print(repr(bot.command_groups.keys()))` to get the array of commands.
Output:
`[u'rand', u'wiktionary', u'help', u'currency', u'seen', u'8ball', u'coretasks', u'dice', u'clock', u'movie', u'wikipedia', u'etymology', u'version', u'units', u'calc', u'tell', u'roulette', u'search', u'reload', u'admin', u'fringe', u'adminchannel', u'url', u'isup', u'unicode_info', u'remind']`
After .reload:
`[]` empty array.
This is still an issue on 6.3.1

**Comment by jsnprstn** [comment]
Just add the helloworld module from https://github.com/sopel-irc/sopel/wiki/Sopel-tutorial,-Part-2 to ~/.sopel/modules and reload.  Then ask for .commands in a query and you should see this.

**Comment by dgw** [comment]
The help module has been significantly rewritten since this issue was filed. Feel free to reopen with new details if this issue still occurs with version 6.5.2 or above (which will include further tweaks to `help`).
