### ISSUE TITLE
weather doesn't work fully.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1018]
Examples:
...
11:07AM <ulic> .weather
11:07AM <URL> I don't know where you live. Give me a location, like .weather London, or tell me where you
          live by saying .setlocation London, for example.
11:07AM <ulic> .weather Denver
11:07AM <URL> ulic: I don't know where that is.
11:07AM <ulic> .weather Denver, CO
11:07AM <URL> ulic: I don't know where that is.
11:08AM <ulic> .setlocation Denver, CO
11:08AM <URL> ulic: I don't know where that is.
11:08AM <ulic> URL is dumb
[11:10am] <Ant> URL, you're dumb.
11:11AM <R_Daneel> .weaTHER 90035
11:11AM <URL> R_Daneel: I don't know where that is.
[11:12am] <Ant> .version
11:12AM <URL> Ant: Sopel v. 6.2.1
11:12AM <R_Daneel> .setlocation 48237
11:12AM <URL> R_Daneel: I don't know where that is.
[11:12am] <Ant> .weather Southfield, MI
11:12AM <URL> Ant: I don't know where that is.
[11:13am] <Ant> .setlocation 90631
11:13AM <URL> Ant: I don't know where that is.
11:13AM <R_Daneel> .setlocation Oak Park, MI
11:13AM <URL> R_Daneel: I don't know where that is.
[11:13am] <Ant> .help .setlocation
[11:13am] <Ant> .help setlocation
11:13AM <URL> Ant: Set your default weather location.
11:13AM <URL> Ant: e.g. .setlocation Columbus, OH
[11:13am] <Ant> .setlocation Columbus, OH
11:13AM <URL> Ant: I don't know where that is.
[11:13am] <Ant> oy
...

$ python
Python 3.4.2 (default, Oct  8 2014, 10:45:20)
[GCC 4.9.1] on linux

Thank you in advance. :)

**Comment by dgw** [comment]
Sounds like already-fixed #1006. Next release should work again.

**Comment by maxpowa** [comment]
Fixed in [6.3.0](https://pypi.python.org/pypi/sopel/6.3.0)
