### ISSUE TITLE
url: UnicodeEncodeError

### ISSUE THREAD

**Issue by maxpowa** [sopel-irc/sopel#1021]
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2014' in position 352:    | ordinal not in range(128) (file "/usr/local/lib/python2.7/dist-packages/sopel/modules/url.py", line | 191, in find_title)	

https://github.com/sopel-irc/sopel/blob/master/sopel/modules/url.py#L191

**Comment by jordan-rosenfeld** [comment]
I also encountered this but with \u2019 (right single quotation mark).

**Comment by elad661** [comment]
I guess I didn't test this enough on python 2.7

People should really be switching to 3 though!

**Comment by br0ziliy** [comment]
@elad661 Elad, I fixed it, works on botth 2.7 and 3 now.

**Comment by fgsch** [comment]
Any plan to include this on a release? It's a bit annoying

**Comment by elad661** [comment]
Sorry for the delay - real life takes priority over software projects.

I'll review this pull request now.
