### ISSUE TITLE
Sopel spams exceptions when disconnected on Windows

### ISSUE THREAD

**Issue by dewiniaid** [sopel-irc/sopel#1024]
While doing some development work on Windows, my internet connection dropped briefly.  This yielded a bunch of repeated spam, followed by the bot giving up due to encountering too many exceptions.  Any sort of auto-reconnection behavior is broken as a result.

```
ERROR:sopel.modules.sopel.irc:Fatal error in core, please review exception log
Traceback (most recent call last):
  File "C:\Python34\lib\asynchat.py", line 117, in handle_read
    data = self.recv(self.ac_in_buffer_size)
  File "D:\git\pipsqueak\sopel-venv\lib\site-packages\sopel\irc.py", line 276, in _ssl_recv
    data = self.socket.read(buffer_size)
  File "C:\Python34\lib\ssl.py", line 625, in read
    v = self._sslobj.read(len or 1024)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

The "too many errors" spam message breaks under Python 3, but I'll post a separate issue for that.

**Comment by Exirel** [comment]
It's old, it's on windows, no comments for 4 years: I give myself the right to close it. If anything new happens, feel free to open a new issue with as much logs as possible with the latest version of Sopel (7.0 at least).
