### ISSUE TITLE
Incompatible python 2.x-style print causes an exception when attempting to complain about too many exceptions under Python 3

### ISSUE THREAD

**Issue by dewiniaid** [sopel-irc/sopel#1025]
`handle_error` in `irc.py` contains these lines:

```python
        if self.error_count > 10:
            if (datetime.now() - self.last_error_timestamp).seconds < 5:
                print >> sys.stderr, "Too many errors, can't continue"
                os._exit(1)
```

This ends up being valid syntax in Python 3 (probably why this wasn't found sooner), but does something entirely different than the Python 2 version: It attempts to compare `print` to `sys.stderr`, rather than printing to sys.stderr:
```
  File "D:\git\pipsqueak\sopel-venv\lib\site-packages\sopel\irc.py", line 402, in handle_error
    print >> sys.stderr, "Too many errors, can't continue"
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and 'OutputRedirect'
```
The fix should be as simple as changing offending line to read:
```print("Too many errors, can't continue", file=sys.stderr)```

**Comment by elad661** [comment]
Fixed, thanks.
