### ISSUE TITLE
[Bug] Sopel spams on 'disconnected by services'

### ISSUE THREAD

**Issue by disconnect3d** [sopel-irc/sopel#1026]
Hey,

I am a user called `disconnected` on freenode irc server. From time to time a `sopel` bot spams me with:

> by

As time passes by, it gets more and more annoying...

Version of the bots who has messaged me:
```
<WorfBot> disconnected: Sopel v. 6.2.1 at commit: 
22:33:09 76886574cfdecd3bcf904750b5cb93a1f42a2af3
<LQYBot> disconnected: Sopel v. 6.3.0
<B0tly> disconnected: Sopel v. 6.3.0
<Sopel> disconnected: Sopel v. 6.3.0
```

Example "by" messages logs:
```
$ cat irc\:WorfBot.log | grep by$
1454868394 <WorfBot> by
1454920319 <WorfBot> by
1455088471 <WorfBot> by
1455114188 <WorfBot> by
1455156376 <WorfBot> by
1455260640 <WorfBot> by
1455288649 <WorfBot> by
1455293223 <WorfBot> by
1455505714 <WorfBot> by
1455549474 <WorfBot> by
1455562173 <WorfBot> by
 ```

Some information from one of the bot owner:
```
1455569715 <disconnected> _joe: Could you send me ~/.sopel/logs, so that could be tracked better?
1455569823 <_joe> disconnected: i've already checked them and they don't contain a record of WorfBot PMing you
1455569850 <_joe> but it looks like, per the timestamps you provided, it's happening when people here get "disconnected by services"
1455569865 <_joe> <<1455562172.47	:badon!~badon@pdpc/supporter/active/badon QUIT :Disconnected by services
1455569872 <disconnected> ok thanks, probably that's enough :)
```

About the OS/installation...:
```
<_joe> it's running on linux, and i am running sopel code from git
```

I have tried to reproduce the bug with no luck using `pip install sopel` -> launching the bot with default config and quiting from the channel manually... but that's not really 'disconnected by services'...

**Comment by elad661** [comment]
Ouch, this is really bad. Thanks for letting us know. I'll look into it.

**Comment by elad661** [comment]
Fixed! This was fun to debug, you can see the full explanation in the commit message.

Now all you need to do is to pester all these people to update their bots. I guess we'll need a release soon, since this is (at least in my opinion) a major bug.

**Comment by disconnect3d** [comment]
Cool, thanks!
