### ISSUE TITLE
.setlocation gives an error and fails: AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by yoosi** [sopel-irc/sopel#1029]
yoosi: `.setlocation london`

sopel: `AttributeError: 'NoneType' object has no attribute 'get' (file "/home/sopel/sopel/sopel/modules/weather.py", line 181, in update_woeid)`

**Comment by yoosi** [comment]
Here's stderr from Sopel when user does a `.setlocation london`

> Function get is deprecated.
>   File "/usr/lib/python3.4/threading.py", line 888, in _bootstrap
>     self._bootstrap_inner()
>   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
>     self.run()
>   File "/usr/lib/python3.4/threading.py", line 868, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/carter/sopel/sopel/bot.py", line 441, in call
>     exit_code = func(sopel, trigger)
>   File "/home/carter/sopel/sopel/modules/weather.py", line 161, in update_woeid
>     first_result = woeid_search(trigger.group(2))
>   File "/home/carter/sopel/sopel/modules/weather.py", line 21, in woeid_search
>     dont_decode=True)
> Traceback (most recent call last):
>   File "/home/carter/sopel/sopel/bot.py", line 441, in call
>     exit_code = func(sopel, trigger)
>   File "/home/carter/sopel/sopel/modules/weather.py", line 181, in update_woeid
>     uzip = first_result.get('postal').get('#text') or ''
> AttributeError: 'NoneType' object has no attribute 'get'

**Comment by thomastanck** [comment]
http://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20geo.places%20where%20text=%22London%22

first_result has a postal tag, but nothing else

**Comment by yoosi** [comment]
```
15:33 yoosi .weather
15:33 Sopel AttributeError: 'NoneType' object has no attribute 'get' (file "/opt/rh/python33/root/usr/lib/python3.3/site-packages/sopel/modules/weather.py", line 144, in weather)
```

Now I'm getting errors after location is properly set when I try to get the weather. Last tried in a PM with Sopel on freenode as well as my personal bot after running a git pull today.
