### ISSUE TITLE
[remind] .in confirms using user's tz; .at, using UTC

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1036]
It's weird that the `.at` and `.in` commands use different timezones when confirming the time at which the reminder will be sent, especially because the absolute reminder (`.at`) interprets the time given as being in the user's timezone but then outputs UTC.

Would be pretty trivial to make both of the reminder commands confirm the same way. Just looking for any preferences people might have toward using UTC or using the calling user's timezone (my preference)—and for cases I haven't thought of where the current behavior is desirable.

**Comment by thomastanck** [comment]
My personal preference would be to report both UTC and local time.

**Comment by dgw** [comment]
Fixed by #1185 (though the commit message incorrectly said that `.at` was fixed).
