### ISSUE TITLE
Sopel's requirements include packages not necessary for the core functionality

### ISSUE THREAD

**Issue by ayust** [sopel-irc/sopel#1037]
It seems odd to require modules like `pyenchant` when using `pip install sopel` - it makes it harder to work with sopel for projects that aren't necessarily using the default modules.

Perhaps it'd be worth moving these sorts of modules to "extras" as optional dependencies rather than making them a core requirement?
- The spellcheck module which uses `pyenchant` already has an import check and fails gracefully if it's not available.
- The ip module would need to be changed to fail gracefully if `pygeoip` is not available.
- The reddit module would need to be changed to fail gracefully if `praw` is not available.

None of these 3 modules seem like they're a central, core piece of functionality that every user would necessarily want.

**Comment by elad661** [comment]
The reason why we added these requirements is that when we made them non-mandatory, we got a lot of people complaining about them not working, or people complaining about sopel showing "errors" on startup, and we had to explain again and again that these "errors" are non fatal - just modules failing to load because of a missing dependency.

Having three extra libraries installed from PyPi even if you don't use them is not such a big deal.

**Comment by ayust** [comment]
It actually results in sopel failing to install on more minimal Linux distributions that don't have some of the libraries they're depending on. (E.g. if you're working with Docker and the Alpine Linux minimal python base images.

Perhaps instead it would make more sense to not load the spellcheck/ip/reddit modules by default?

**Comment by elad661** [comment]
If you're skilled enough to run a very minimal distribution, you're skilled enough to install sopel not via PyPi, which is the only method of installing it which enforces dependency requirements.

In my personal opinion, supporting a bunch of very minimal distributions is not worth the amount of time we'll have to spend supporting users who are completely clueless about optional dependencies and won't read the docs.

**Comment by ayust** [comment]
I can see that line of reasoning and can't really object to it. (Though I do think that even people with advanced knowledge like not having to do things the hard way when possible!)

**Comment by dgw** [comment]
One of the long-term ideas I've had is to move most of the core modules into separate PyPI packages that can be installed separately. That idea has its own thread in #1291, but doing so would effectively solve this issue. Each separately-installed module would simply require what it needs, leaving the main Sopel requirements file to list _only_ stuff needed to run the framework (and perhaps a couple of truly indispensable administration-related modules).

**Comment by Exirel** [comment]
As pointed out by @dgw this will be effectively fixed when #1291 will be fixed, in Sopel 8.x. The roadmap isn't written in stone, but we have a pretty clear overview of what to do and how to achieve our goal.

Without further ado, I close this one, but its intent still live in #1291!

**Comment by Exirel** [comment]
Note: #1291 takes care of tracking that effort.
