### ISSUE TITLE
Getting PMed by sopel and willie based bots a lot

### ISSUE THREAD

**Issue by PixelToast** [sopel-irc/sopel#1038]
my username on IRC is "ping" and i have been constantly getting "timeout:" messages from bots
http://i.imgur.com/Sj8601X.png
http://i.imgur.com/vNoU7jS.png
http://i.imgur.com/DCHrXQA.png

if you would like me to get more information on these bots (version, etc) let me know and ill try to contact the owners

**Comment by Erethon** [comment]
Related to #1026 I guess.

**Comment by PixelToast** [comment]
SageBot was running Sopel v. 6.3.0 so this is still not fixed

**Comment by maxpowa** [comment]
@embolalia can we get a 6.3.1 release to fix this bug?

**Comment by elad661** [comment]
This is fixed in 6.3.1, which will hopefully be up on PyPi later today (once I overcome a small technical issue on my end). The fix was on git master for a few weeks now, and I've made the release on github just now.
