### ISSUE TITLE
Command "sopel" not running

### ISSUE THREAD

**Issue by Gustavo6046** [sopel-irc/sopel#1046]
I'm running Windows 10 Pro 64-bit x64. When I try to run the sopel command in CMD, it says "sopel: command not recognized".

I just had a fresh sopel install from PyPI.

**Comment by maxpowa** [comment]
Is the python scripts directory on your path? Can you confirm other scripts installed through pypi work on your system?

**Comment by Gustavo6046** [comment]
Most other scripts installed through pypi works in my system. And yes, python's lib directory is on the environment %path% variable.

**Comment by Gustavo6046** [comment]
I will see if I can use the source code in the latest Sopel GitHub release and use setup.py to see if I can make this work.

**Comment by maxpowa** [comment]
Can you clarify "does not work"? Is it erroring? If so can you provide that error?

**Comment by Gustavo6046** [comment]
Basically the same thing happened, but nevermind, because I learnt to do my own socket IRC wrapper, GusPIRC, and it's perfect right now :)

Rock on!
