### ISSUE TITLE
weather now requiring oauth

### ISSUE THREAD

**Issue by dasu** [sopel-irc/sopel#1050]
The weather module seems to be requiring oauth now.
Manually running through the command would yield this: "Please provide valid credentials. OAuth oauth_problem='OST_OAUTH_PARAMETER_ABSENT_ERROR', realm='yahooapis.com'"

From yahoo's dev portal: [https://developer.yahoo.com/weather/](https://developer.yahoo.com/weather/)
"To increase the security measure and better serving our YDN customers, weather data source will enforce OAuth 1 starting March 15, 2016. Please update your API calls with OAuth 1 enabled (via the OAuth /v1/yql end point if using YQL) using your Yahoo App key and secret."

**Comment by dgw** [comment]
API keys are the bane of sopel's existence this quarter, it seems. This might need to be split into an external module, like I just did with wolfram.py.

**Comment by dasu** [comment]
I made a drafty modification that used forecast.io api, and has a couple of new features.
Would require a forecast.io api key and google url shortener api key.
https://github.com/dasu/syrup-willie-modules/blob/master/weather2.py if anyone is interested.

**Comment by ridelore** [comment]
works fine - thx

**Comment by blancNoir** [comment]
@dasu  got your script working, thank you.

**Comment by antdude** [comment]
Is this related to what I am seeing?
...
03:08PM <Mousey> .weather
03:08PM <URL> AttributeError: 'NoneType' object has no attribute 'get' (file
          "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/weather.py", line
          144, in weather)
...
