### ISSUE TITLE
How dare you add a non-encoding bug to phenny!

### ISSUE THREAD

**Issue by ncouture** [sopel-irc/sopel#1057]
My IRC nickname is 'remote' and I'm a quite popular figure among your bots.

Phenny used to reach out to me only when I needed it, Sopel turned into a monster!

> 05:55 <_Ultrabot> host
> 06:03 <_Ultrabot> host
> 13:51 <_Ultrabot> host
> 13:54 <_Ultrabot> host
> 13:56 <_Ultrabot> host
> 14:29 <_Ultrabot> host
> 15:13 <_Ultrabot> host
> Day changed to 24 Mar 2016
> 04:07 <_Ultrabot> host
> 16:21 -!- _Ultrabot [~ultrabot@195.66.82.9]
> 16:21 -!-  ircname  : _Ultrabot
> 16:21 -!-  server   : kornbluth.freenode.net [Frankfurt, Germany]
> 16:21 -!-           : is using a secure connection
> 16:21 -!-  idle     : 0 days 3 hours 49 mins 15 secs [signon: Wed Apr  6 12:32:13 2016]
> 16:21 -!- End of WHOIS

> Day changed to 16 Mar 2016
> 02:35 <Glaaki> host
> 02:49 <Glaaki> host
> 07:40 <Glaaki> host
> 12:15 <Glaaki> host
> 15:08 <Glaaki> host
> 18:18 <Glaaki> host
> Day changed to 17 Mar 2016
> 13:30 <Glaaki> host
> 13:57 <Glaaki> host
> 17:19 <Glaaki> host
> 20:29 <Glaaki> host
> Day changed to 18 Mar 2016
> 07:50 <Glaaki> host
> 09:54 <Glaaki> host
> 11:27 <Glaaki> host
> 11:41 <Glaaki> host
> 13:31 <Glaaki> host
> 16:22 -!- Glaaki [~BotViperr@62-210-222-203.rev.poneytelecom.eu]
> 16:22 -!-  ircname  : Bot-Viperr, http://viperr.org
> 16:22 -!-  server   : holmes.freenode.net [London, UK]
> 16:22 -!-  idle     : 0 days 0 hours 20 mins 29 secs [signon: Wed Apr  6 10:33:03 2016]
> 16:22 -!- End of WHOIS

> Day changed to 05 Apr 2016
> 16:14 <B0tly> host
> 18:16 <B0tly> host
> 23:52 <B0tly> host
> Day changed to 06 Apr 2016
> 02:33 <B0tly> host
> 07:10 <B0tly> host
> 11:44 <B0tly> host
> 12:46 <B0tly> host
> 13:22 <B0tly> host
> 15:02 <B0tly> host
> 15:33 <B0tly> host
> 15:36 <B0tly> host
> 15:54 <B0tly> host
> 16:23 -!- B0tly [~sopel@c-50-148-0-158.hsd1.in.comcast.net]
> 16:23 -!-  ircname  : Sopel: http://sopel.chat
> 16:23 -!-  server   : holmes.freenode.net [London, UK]
> 16:23 -!-  idle     : 0 days 0 hours 11 mins 59 secs [signon: Wed Apr  6 10:31:33 2016]
> 16:23 -!- End of WHOIS

> Day changed to 10 Mar 2016
> 16:15 <Jeeves> host
> 18:48 <Jeeves> host

> Day changed to 09 Feb 2016
> 16:47 <qverzion> host
> 17:04 <qverzion> host
> 17:08 <qverzion> host
> 17:36 <qverzion> host
> 18:57 <qverzion> host
> 19:02 <qverzion> host
> 19:12 <qverzion> host
> 20:50 <qverzion> host
> 21:42 <qverzion> host
> Day changed to 10 Feb 2016

> Day changed to 04 Apr 2016
> 01:59 <RotiPrata> host
> 02:08 <RotiPrata> host
> 02:09 <RotiPrata> host
> 02:39 <RotiPrata> host
> 07:53 <RotiPrata> host
> 12:23 <RotiPrata> host
> 20:01 <RotiPrata> host
> Day changed to 05 Apr 2016
> 12:58 <RotiPrata> host
> 20:00 <RotiPrata> host
> 20:00 <RotiPrata> host
> Day changed to 06 Apr 2016
> 14:04 <RotiPrata> host
> 16:24 -!- RotiPrata [~HSG-NAS@118.189.63.230]
> 16:24 -!-  ircname  : HackerspaceSG (http://hackerspace.sg)
> 16:24 -!-  server   : asimov.freenode.net [TX, USA]
> 16:24 -!-  idle     : 0 days 2 hours 20 mins 8 secs [signon: Sat Apr  2 03:06:12 2016]
> 16:24 -!- End of WHOIS

> Day changed to 10 Feb 2016
> 00:04 -!- Moonglum is now known as Hawkmoon
> 00:04 <Hawkmoon> host
> Day changed to 11 Feb 2016

> Day changed to 05 Apr 2016
> 04:47 <SickRage> host closed the connection :KeyError: Identifier('p0psicles_') (file 
>                  "/usr/local/lib/python2.7/dist-packages/sopel/tools/target.py", line 63, in clear_user)
> 20:00 <SickRage> host closed the connection :KeyError: Identifier('sragan') (file 
>                  "/usr/local/lib/python2.7/dist-packages/sopel/tools/target.py", line 63, in clear_user)
> Day changed to 06 Apr 2016
> 09:13 <SickRage> host closed the connection :KeyError: Identifier('ahtanu') (file 
>                  "/usr/local/lib/python2.7/dist-packages/sopel/tools/target.py", line 63, in clear_user)
> 11:07 <SickRage> host closed the connection :KeyError: Identifier('supergonkas') (file 
>                  "/usr/local/lib/python2.7/dist-packages/sopel/tools/target.py", line 63, in clear_user)
> 16:25 -!- SickRage [~SickRage@2001:470:1f07:55d::24]
> 16:25 -!-  ircname  : SickRage
> 16:25 -!-  server   : wolfe.freenode.net [Stockholm, SE]
> 16:25 -!-           : is using a secure connection
> 16:25 -!-  idle     : 0 days 1 hours 50 mins 2 secs [signon: Thu Mar 31 07:22:42 2016]
> 16:25 -!-  account  : SickRage
> 16:25 -!- End of WHOIS

> Day changed to 06 Apr 2016
> 00:28 <LQYBot> host
> 01:24 <LQYBot> host
> 02:00 <LQYBot> host
> 02:13 <LQYBot> host
> 02:15 <LQYBot> host
> 02:27 <LQYBot> host
> 02:52 <LQYBot> host
> 03:34 <LQYBot> host
> 03:40 <LQYBot> host
> 03:45 <LQYBot> host
> 04:08 <LQYBot> host
> 06:21 <LQYBot> host
> 06:37 <LQYBot> host
> 08:47 <LQYBot> host
> 08:49 <LQYBot> host
> 09:14 <LQYBot> host
> 09:22 <LQYBot> host
> 10:15 <LQYBot> host
> 10:18 <LQYBot> host
> 10:21 <LQYBot> host
> 10:32 <LQYBot> host
> 11:31 <LQYBot> host
> 11:32 <LQYBot> host
> 11:37 <LQYBot> host
> 11:37 <LQYBot> host
> 11:48 <LQYBot> host
> 11:51 <LQYBot> host
> 11:51 <LQYBot> host
> 12:45 <LQYBot> host
> 14:00 <LQYBot> host
> 14:29 <LQYBot> host
> 14:48 <LQYBot> host
> 16:25 -!- LQYBot [~lqybot@li1202-108.members.linode.com]
> 16:25 -!-  ircname  : LQYBot from felixonmars
> 16:25 -!-  server   : wilhelm.freenode.net [FR]
> 16:25 -!-           : is using a secure connection
> 16:25 -!-  idle     : 0 days 1 hours 37 mins 2 secs [signon: Thu Mar 17 08:24:48 2016]
> 16:25 -!- End of WHOIS
> 16:26 <remote> why are you doing this to me?

> Day changed to 12 Feb 2016
> 14:34 <NotJedlicka> host

> Day changed to 13 Feb 2016
> 19:31 <WorfBot> host
> Day changed to 14 Feb 2016
> 04:31 <WorfBot> host
> 05:27 <WorfBot> host
> 23:19 <WorfBot> host
> Day changed to 15 Feb 2016
> 06:43 <WorfBot> host

> 16:28 -!- WorfBot [~alpha5@softcheese.net]
> 16:28 -!-  ircname  : WorfBot
> 16:28 -!-  server   : verne.freenode.net [NL]
> 16:28 -!-  idle     : 0 days 0 hours 6 mins 33 secs [signon: Wed Apr  6 10:41:52 2016]
> 16:28 -!-  account  : WorfBot
> 16:28 -!- End of WHOIS

> 04:26 -!- Irssi: Starting query in freenode with __kitty__
> 04:26 <__kitty__> host
> 15:42 <__kitty__> host

> Day changed to 31 Mar 2016
> 01:25 <plzbum> host
> 03:16 <plzbum> host
> 15:23 <plzbum> host
> Day changed to 01 Apr 2016
> 09:44 <plzbum> host
> Day changed to 02 Apr 2016
> 17:26 <plzbum> host
> Day changed to 03 Apr 2016
> 02:38 <plzbum> host
> Day changed to 04 Apr 2016
> Day changed to 05 Apr 2016
> Day changed to 06 Apr 2016
> 01:25 <plzbum> host
> 16:28 -!- plzbum [~bum@103.242.245.32]
> 16:28 -!-  ircname  : can't bum a bummer
> 16:28 -!-  server   : verne.freenode.net [NL]
> 16:28 -!-  idle     : 0 days 0 hours 3 mins 42 secs [signon: Sat Apr  2 21:36:45 2016]
> 16:28 -!- End of WHOIS

> Day changed to 03 Mar 2016
> 18:19 <Sopel> host
> 18:50 <Sopel> host
> Day changed to 04 Mar 2016
> 03:17 <Sopel> host
> 05:58 <Sopel> host
> 16:29 -!- Sopel [~sopel@eagle.embolalia.com]
> 16:29 -!-  ircname  : Sopel: http://sopel.chat
> 16:29 -!-  server   : weber.freenode.net [US]
> 16:29 -!-           : is using a secure connection
> 16:29 -!-  idle     : 1 days 23 hours 10 mins 50 secs [signon: Sun Mar 20 23:40:44 2016]
> 16:29 -!-  account  : willie
> 16:29 -!- End of WHOIS

> 16:59 <langbotijo> host
> 17:13 <langbotijo> host
> Day changed to 13 Feb 2016
> 16:31 <langbotijo> host
> 20:07 <langbotijo> host
> 22:54 <langbotijo> host
> 22:58 <langbotijo> host
> Day changed to 14 Feb 2016
> 09:01 <langbotijo> host
> Day changed to 15 Feb 2016
> 17:37 <langbotijo> host
> 20:20 <langbotijo> host
> 22:52 <langbotijo> host
> Day changed to 16 Feb 2016
> 07:57 <langbotijo> host
> 18:49 <langbotijo> host
> 19:34 <langbotijo> host
> 23:36 <langbotijo> host
> Day changed to 17 Feb 2016
> 04:55 <langbotijo> host

> Day changed to 21 Mar 2016
> 02:03 <chobot> host
> 09:25 <chobot> host
> 09:34 <chobot> host
> 17:42 <chobot> host
> 18:29 <chobot> host
> Day changed to 22 Mar 2016
> Day changed to 23 Mar 2016
> Day changed to 24 Mar 2016
> 11:00 <chobot> host

> 09:29 <SickRage-> host closed the connection :KeyError: Identifier('fernandog') (file 
>                   "/usr/local/lib/python2.7/dist-packages/sopel/tools/target.py", line 63, in clear_user)
> 

> Day changed to 01 Apr 2016
> 03:20 <jeezbel> host
> 15:27 <jeezbel> host
> 18:18 <jeezbel> host
> Day changed to 02 Apr 2016
> Day changed to 03 Apr 2016
> Day changed to 04 Apr 2016
> 14:59 <jeezbel> host
> 16:26 <jeezbel> host
> 17:44 <jeezbel> host
> Day changed to 05 Apr 2016
> 18:39 <jeezbel> host

**spoiler** php brazil are using a Python IRC bot
> 11:54 <php-br> host
> Day changed to 23 Feb 2016
> 15:51 <php-br> host
> Day changed to 24 Feb 2016
> Day changed to 25 Feb 2016
> Day changed to 26 Feb 2016
> Day changed to 27 Feb 2016
> Day changed to 28 Feb 2016
> Day changed to 29 Feb 2016
> Day changed to 01 Mar 2016
> Day changed to 02 Mar 2016
> 13:35 <php-br> host

> Day changed to 07 Mar 2016
> 08:19 <crudebutt> host closed the connection :KeyError: Identifier('pikochuu') (file 
>                   "/usr/lib/python2.7/site-packages/sopel-6.3.0-py2.7.egg/sopel/tools/target.py", line 65, in clear_user)
> 20:43 <crudebutt> host closed the connection :KeyError: Identifier('pikochuu') (file 
>                   "/usr/lib/python3.4/site-packages/sopel-6.3.0-py3.4.egg/sopel/tools/target.py", line 65, in clear_user)
> Day changed to 08 Mar 2016
> 12:12 <crudebutt> host closed the connection :KeyError: Identifier('onenerdyguy') (file 
>                   "/usr/lib/python3.4/site-packages/sopel-6.3.0-py3.4.egg/sopel/tools/target.py", line 65, in clear_user)
> 18:18 <crudebutt> host closed the connection :KeyError: Identifier('E-werd') (file 
>                   "/usr/lib/python3.4/site-packages/sopel-6.3.0-py3.4.egg/sopel/tools/target.py", line 65, in clear_user)
> 23:47 <crudebutt> host closed the connection :KeyError: Identifier('pikochuu') (file 
>                   "/usr/lib/python3.4/site-packages/sopel-6.3.0-py3.4.egg/sopel/tools/target.py", line 65, in clear_user)
> 

> 19:52 <Chozo> host
> 20:50 <Chozo> host
> 21:33 <Chozo> host
> Day changed to 29 Feb 2016
> 01:29 <Chozo> host
> 11:28 <Chozo> host
> Day changed to 01 Mar 2016
> Day changed to 02 Mar 2016
> Day changed to 03 Mar 2016
> 18:19 <Chozo> host

> Day changed to 12 Mar 2016
> 18:11 <moobot> host
> Day changed to 13 Mar 2016
> 11:35 <moobot> host
> 17:37 <moobot> host
> 18:25 <moobot> host
> 20:32 <moobot> host
> 21:03 <moobot> host
> 21:27 <moobot> host
> 16:33 -!- moobot [~LDC@162.243.194.120]
> 16:33 -!-  ircname  : Moo Hubert Bot, https://www.linuxdistrocommunity.c
> 16:33 -!-  server   : orwell.freenode.net [NL]
> 16:33 -!-           : is using a secure connection
> 16:33 -!-  idle     : 0 days 0 hours 8 mins 34 secs [signon: Wed Apr  6 13:42:19 2016]
> 16:33 -!-  account  : moobot
> 16:33 -!- End of WHOIS
> 

> Day changed to 15 Mar 2016
> 12:46 <librepel> host
> Day changed to 16 Mar 2016
> 01:47 <librepel> host
> 07:29 <librepel> host
> Day changed to 17 Mar 2016
> Day changed to 18 Mar 2016
> Day changed to 19 Mar 2016
> 08:55 <librepel> host
> 

> 07:53 <TuxemonBot> host
> 07:53 <TuxemonBot> host
> 07:53 <TuxemonBot> host
> 13:53 <TuxemonBot> host
> Day changed to 05 Apr 2016
> Day changed to 06 Apr 2016
> 16:34 -!- TuxemonBot [sopel@2600:3c01::f03c:91ff:feae:4b2c]
> 16:34 -!-  ircname  : Sopel: http://sopel.chat
> 16:34 -!-  server   : wolfe.freenode.net [Stockholm, SE]
> 16:34 -!-  idle     : 1 days 7 hours 12 mins 15 secs [signon: Tue Apr  5 09:22:03 2016]
> 16:34 -!- End of WHOIS
> 

> 16:19 <mog> host closed the connection :KeyError: Identifier('cm2') (file "/usr/lib/python3/dist-packages/sopel/tools/target.py", line 
>             65, in clear_user) I  IIII I I I    II  I   II  II
> 16:21 <mog> host closed the connection :KeyError: Identifier('FrozenCow') (file "/usr/lib/python3/dist-packages/sopel/tools/target.py", 
>             line 65, in clear_user) I  IIII I I I    II  I   II  II
> 16:21 <mog> host closed the connection :KeyError: Identifier('barjac') (file "/usr/lib/python3/dist-packages/sopel/tools/target.py", 
>             line 65, in clear_user) I  IIII I I I    II  I   II  II
> 16:25 <mog> host closed the connection :KeyError: Identifier('MobileKittuns') (file 
>             "/usr/lib/python3/dist-packages/sopel/tools/target.py", line 65, in clear_user) I  IIII I I I    II  I   II  II
> 16:28 <mog> host closed the connection :KeyError: Identifier('Bruce___') (file "/usr/lib/python3/dist-packages/sopel/tools/target.py", 
>             line 65, in clear_user) I  IIII I I I    II  I   II  II
> 16:30 <mog> host closed the connection :KeyError: Identifier('Mr_Ed') (file "/usr/lib/python3/dist-packages/sopel/tools/target.py", line 
>             65, in clear_user) I  IIII I I I    II  I   II  II
> 

> 16:34 -!- mog [~mog@fsf/member/mog]
> 16:34 -!-  ircname  : mog
> 16:34 -!-  server   : barjavel.freenode.net [Paris, FR]
> 16:34 -!-           : is using a secure connection
> 16:34 -!-  idle     : 0 days 0 hours 3 mins 17 secs [signon: Sun Apr  3 20:24:19 2016]
> 16:34 -!-  account  : mog
> 16:34 -!- End of WHOIS
> 

> 
> 23:36 <gcl-bot> host
> Day changed to 05 Apr 2016
> 03:09 <gcl-bot> host
> 03:31 <gcl-bot> host
> 03:32 <gcl-bot> host
> 06:37 <gcl-bot> host
> 07:45 <gcl-bot> host
> 08:08 <gcl-bot> host
> 10:30 <gcl-bot> host
> 10:58 <gcl-bot> host

> 11:10 <gcl-bot> host
> 13:57 <gcl-bot> host
> 14:51 <gcl-bot> host
> 15:24 <gcl-bot> host
> 16:56 <gcl-bot> host
> 18:01 <gcl-bot> host
> 19:25 <gcl-bot> host
> 21:13 <gcl-bot> host
> 22:12 <gcl-bot> host
> Day changed to 06 Apr 2016
> 00:35 <gcl-bot> host
> 02:58 <gcl-bot> host
> 04:32 <gcl-bot> host
> 06:04 <gcl-bot> host
> 09:13 <gcl-bot> host
> 09:23 <gcl-bot> host
> 10:59 <gcl-bot> host
> 12:09 <gcl-bot> host
> 12:29 <gcl-bot> host
> 12:39 <gcl-bot> host
> 13:09 <gcl-bot> host
> 13:12 <gcl-bot> host
> 14:29 <gcl-bot> host
> 16:35 -!- gcl-bot [~sopel@162.243.101.122]
> 16:35 -!-  ircname  : Sopel: http://sopel.chat
> 16:35 -!-  server   : barjavel.freenode.net [Paris, FR]
> 16:35 -!-           : is using a secure connection
> 16:35 -!-  idle     : 0 days 2 hours 5 mins 46 secs [signon: Wed Apr  6 02:00:19 2016]
> 16:35 -!-  account  : gcl-bot
> 16:35 -!- End of WHOIS
>

**Comment by maxpowa** [comment]
Should have been fixed with 6.3.1, message bot owners to update.
