### ISSUE TITLE
YouTube URLs' titles do not get posted by Sopel v6.3.1.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1066]
Hello.

...
[05:31am] [Ant> https://www.youtube.com/watch?v=WZHGeg_0Rlo
05:31AM [URL> [ https://www.youtube.com/watch?v=WZHGeg_0Rlo ] - www.youtube.com
[05:32am] [Ant> Also, Closer tune.
[05:33am] [Ant> http://www.youtube.com/watch?v=9e9NSMY8QiQ
05:33AM [URL> [ http://www.youtube.com/watch?v=9e9NSMY8QiQ ] - www.youtube.com
[05:33am] [Ant> Weird that URL doesn't post the titles.
...
05:37am] [Ant> .version
05:37AM [URL> Ant: Sopel v. 6.3.1
...

Thank you in advance. :)

**Comment by dasu** [comment]
The youtube module was removed because it requires an API key now.  
You can find it here: https://github.com/sopel-irc/sopel-youtube

**Comment by maxpowa** [comment]
Following up on what @dasu said, you can use `pip install sopel_modules.youtube` to install the new module.

**Comment by antdude** [comment]
Thanks guys, but I have an error:

$ pip install sopel_modules.youtube
Collecting sopel-modules.youtube
  Downloading sopel_modules.youtube-0.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-l8j2yh0q/sopel-modules.youtube/setup.py", line 7, in <module>
        from sopel_modules.youtube import __version__
      File "/tmp/pip-build-l8j2yh0q/sopel-modules.youtube/sopel_modules/youtube/__init__.py", line 8, in <module>
        from .youtube import *
      File "/tmp/pip-build-l8j2yh0q/sopel-modules.youtube/sopel_modules/youtube/youtube.py", line 12, in <module>
        import apiclient.discovery
    ImportError: No module named 'apiclient'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-l8j2yh0q/sopel-modules.youtube/


:(

**Comment by maxpowa** [comment]
`pip install google-api-python-client` unfortunately the setup.py isn't written correctly right now and causes that error.

**Comment by antdude** [comment]
Thanks Maxpowa. That worked and was able to install:
...
Successfully built sopel-modules.youtube
Installing collected packages: sopel-modules.youtube
Successfully installed sopel-modules.youtube-0.1.1

However, it still didn't see the results after restarting my Sopel to retry:
...
[09:27am] * Ant tests URL's youtube URL parser.
[09:27am] <Ant> https://www.youtube.com/watch?v=kCbPhALDC14
09:27AM <URL> [ https://www.youtube.com/watch?v=kCbPhALDC14 ] - www.youtube.com
[09:27am] <Ant> hmm
...

What else am I missing?

**Comment by maxpowa** [comment]
Did you configure the api key? Run `sopel -w` and it will guide you through the config for it.

**Comment by antdude** [comment]
Maxpowa: No. Is there a way to only do that module instead of all? with "sopel --configure-modules"? If so, then what's the module name for Sopel?

**Comment by maxpowa** [comment]
No way to configure only a specific module, but if you do `sopel --configure-modules`, you can just type `n` when it asks if you want to configure a module you don't want to configure. The module name for `sopel-youtube` is just `Sopel YouTube`.

**Comment by antdude** [comment]
It would be nice to do only configure specific modules instead of going through every prompt.

Hmm, Enter your Google API key. ... Where would I get that from? I am not familiar with this. :/

**Comment by dgw** [comment]
There's a [guide](https://developers.google.com/youtube/v3/getting-started) directly from Google in the YouTube help center.

**Comment by antdude** [comment]
Thanks dgw. That is sure complex just to show YouTube's video URLs' titles. :(
