### ISSUE TITLE
ai.py not works

### ISSUE THREAD

**Issue by Dropsik** [sopel-irc/sopel#1067]
When I try to run ai.py I got:
`Error in ai setup procedure: 'Config' object has no attribute 'ai' (config/__init__.py:165)`

I tried configure this module with sopel -w but not works (I not see this module in wizard)

**Comment by maxpowa** [comment]
Please create an issue on https://github.com/sopel-irc/sopel-extras as `ai.py` is not part of sopel's base module set.
