### ISSUE TITLE
Does not connect to channels with ## prefix.

### ISSUE THREAD

**Issue by mB-PiBox** [sopel-irc/sopel#1073]
Any channels in the list with ## prefix for channel name.
ie: #freenode,#archlinux,##arkwiki,#mmopg
all channels are connected to except ##arkwiki.

**Comment by mossarelli** [comment]
Could you copy the entry for channels from the default.cfg?
We run a bot that only connects to one channel with a double # and it works fine.
`channels = ##fringe`

**Comment by mB-PiBox** [comment]
channels = #arkwiki,##ArkBot,#arksurvival

**Comment by mossarelli** [comment]
Try putting the ##channel first, put spaces between the commas.

`channels = ##arkbot, #arksurvival, #arkwiki`

**Comment by maxpowa** [comment]
I'm unable to reproduce this, Sopel 6.3.1. Tried with the `##` channel first, middle and end of the channel list and they all worked fine. There's many reasons why the server could be preventing you from joining, we'd need at least a fresh raw.log output from your bot to determine if the `JOIN` commands are being rejected by the server.

**Comment by maxpowa** [comment]
No info provided so I'm closing.
