### ISSUE TITLE
failed with error code 1 in /tmp/pip-build-w7ragg3t/xmltodict/

### ISSUE THREAD

**Issue by dannymichel** [sopel-irc/sopel#1078]
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-w7ragg3t/xmltodict/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-otnixdb9-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-w7ragg3t/xmltodict/

**Comment by maxpowa** [comment]
Sounds like you might need to update your setuptools/pip. What versions of those are you running?

**Comment by maxpowa** [comment]
No info provided so closing.
