### ISSUE TITLE
Sopel Twitch connection issues

### ISSUE THREAD

**Issue by thely** [sopel-irc/sopel#1079]
Apologies if this isn't the right place to ask, but I'm having a hell of a time trying to get Sopel to work with Twitch IRC. I've been able to connect to my channel's chat as both my account and the bot account through irssi, so I'm fairly sure it's not the IRC servers being down. Whenever I run sopel, I get this:

```
Could not open CA certificates file. SSL will not work properly.

Welcome to Sopel. Loading modules...

Error loading ipython: No module named IPython (modules/ipython.py:23)

Registered 41 modules,
1 modules failed to load

Connecting to irc.chat.twitch.tv:6667...
Connected.
Calling shutdown for 0 modules.
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...
```

This continues to loop, forever. If I do `/names` or check the viewer list, the account never appears. And this is my config file, with names edited so it's clear who's who:

```
[core]
nick = mybotname
host = irc.chat.twitch.tv
auth_password = oauth:scrambledgarbage
use_ssl = false
port = 6667
owner = mytwitchname
channels = mytwitchname
prefix = !
```

I did try installing ipython, but it doesn't change the eternal `Connected/Closed!` loop. If it changes anything, sopel is installed in a local virtualenv, because whatever dependency hell came from installing it with `sudo` on OSX 10.9.5 made it traceback whenever I ran it.

**Comment by maxpowa** [comment]
Try setting `auth_method = server` in the config. 

Side note: :+1: on virtualenv, I definitely recommend running from one.

**Comment by thely** [comment]
It worked! Thank you. Looking at raw.log answered the other questions I was about to ask.

**Comment by alexwidener** [comment]
Also running into this issue with the following config: 

```
[core]
nick = nickname
host = irc.chat.twitch.tv
use_ssl = false
port = 6667
auth_method = server
auth_password = oauth:stuff
owner = twitchusername
channels = twitchusername/channel
prefix = !
```

OSX 10.12.2, Python 2.7.11 virtualenv with sopel, (had to manually pip install iPython) - any light you could possibly shed on this, @thely ? Thanks!

**Comment by thely** [comment]
Did you try `channels = #twitchusername`? I haven't run mine in awhile (but hey, new year new streamer), but unless they changed the API around I'm pretty sure the channel should be your username with a pound sign in front of it.

**Comment by alexwidener** [comment]
I have done that, yes. Unfortunately, it's a constant disconnect - and I tried with Willie as well, same result as in Sopel.
