### ISSUE TITLE
[help] Bot can be DoS'd by spamming .help / .commands

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1080]
Perhaps it's at least partially a symptom of running my bot behind ZNC, but I recently had to remove the `help` module from active use because users were sending many `.help` commands in succession and causing the bot to appear unresponsive for long periods of time while the sending queue worked through the excessive number of lines generated when listing commands.

I don't recall seeing any other module generate anywhere near that much output in response to a single command, so I think it's worth bringing up. In 1252d5c, the output was converted from a simple alphabetical list of commands to a list of modules, each with their own command list. This increased the output of `.commands` on my instance from 4 lines to 44 lines. In addition, `.commands` is no longer a separate trigger; it was merged into `.help`, so now both trigger an absurdly long response.

Even if my bot wasn't behind a bouncer, Sopel's internal flood prevention still appears insufficient to prevent issues. It appears to be a trade-off between sending too slowly (and appearing to be unresponsive—this issue) or sending too quickly (and getting killed for excess flood—see #952).

While I love the idea of listing modules separately, giving a clearer indication of what commands are from which modules, and thus making it more obvious what they might do, producing nearly 15 times the output by line count is crippling; even when only one user is listing commands, it takes more than 30 seconds for the bot to output everything. Even taking Espernet's limits (10 messages per 5 seconds) and removing ZNC's admittedly cautious defaults from the picture, it would take around 20 seconds to send a command list to a single user.

One possible solution (which I and one of my users both thought of) is to dump the command list to a text or HTML file that the bot could link to. Obviously that's not possible for all Sopel instances, but it would be great to have as an option (and I just might prototype it for my own bot, since I already set up HTTP support for `meetbot`). The other major idea was to rate-limit use of the command-list function, but that gets messy. Is it limited per-user? per-channel? globally?

Anyone have thoughts? I'm happy to just leave `help` unloaded until I get around to implementing text/HTML dumping, but this is probably going to affect other bots too to some degree. (And it would be nice to know if I should PR the dump feature, too.)

**Comment by dasu** [comment]
I have also ran into the same issue when 2 users decide to run .help at the same time.  Made worse if you have a lot of custom modules with help commands.  
In my situation a text/HTML dump file that I can host on my web server would be ideal.  Although that may not be the case for everyone.

**Comment by mossarelli** [comment]
Use `@rate(seconds)` to limit the repetition of a command.
Also add rate to the `from sopel.module import commands, example`

**Comment by dgw** [comment]
@mossarelli Even a global rate limit wouldn't solve the problem. The bot simply sends out too much text in response to the single command. And since Sopel's built-in rate limiting silently ignores the commands with no feedback whatsoever, anyone trying to use `.help` during the cool-down period after someone else has used it will be very confused.

**Comment by mossarelli** [comment]
@dgw yes I tested it on my own bot. I triggered .help twice and the two outputs mixed together into a soup of letters.
According to the documentation, rate should prevent the command from being executed more than once in a certain time period, but I don't know if rate takes into account, a command that is currently running a for loop compared to a command that has been run.

If you know how to code, put a global variable in the _init_ called help_command_run and import it into the help module. Then make a checker to make sure the help command are not run twice so to limit the help command being used.
I'd put a simple true or false in the variable to prevent the script from being run twice while it's running, combined with the @rate identifier to make sure that help can't be run in 300 seconds after it first been used.

Thing is, I've rewritten most modules in Sopel to make sure it has consistency and implemented argument checking, so my modules standard is different. But if you know how to code, you can implement these fixes yourself.

If you want, I can make the fix and share my help module here so that you can prevent people from DDOSing your bot. Also an IRC server doesn't like a user that spams multiple people and might kick it for spamming.

**Comment by mossarelli** [comment]
So here's a solution to prevent the help command from firing:

In the __init__.py in modules, put this line:
`help_trigger_bool = 0`

Then in help.py put:
`
from sopel.modules.__init__ import help_trigger_bool
global help_trigger_bool
help_trigger_bool = 0
`
somewhere before the @command identifier.
Inside the function put after the documentation, put:
`
global help_trigger_bool
`
then put:
`
if help_trigger_bool == 1:
    bot.notice('The help command is currently being sent to another user', trigger.nick)
    return 0
`
where you want the script to exit if the command is being used.
Put:
`
help_trigger_bool = 1
`
where you want the script to block requests, usually before the for loop that starts digging the commands out. Then put:
`
help_trigger_bool = 0
`
where you want the script to be done, usually at the bottom of the function before return.

Here's how it looks like when I use it:
`
┌Mossarelli┘: .help
├Bot┤ All available commands are sent to you in a private message.
Bot: \-------------------------------------------------------------------------------/
Bot:  
Bot:   HELP:
Bot: The command .help gives you a list of all available commands to use on the bot in the channel and in private messages to the bot.
Bot:  
Bot: Each command starts with a "." character, i.e.: .help, .tell, .seen, etc.
┌Mossarelli┘: .help
├Bot┤ The help command is currently being sent to another user
Bot:
Bot: Some commands needs arguments. Use space to sepparate arguments.
Bot: i.e.: .tell someone message
`

**Comment by maxpowa** [comment]
@mossarelli This only works because .notice bypasses the sending rates and sends immediately. Normal commands other than .help will still appear to be unresponsive until .help is done outputting to one user.

**Comment by dgw** [comment]
I'm not really sold on using gists for this, but if it would be likely to get merged I can add an option to dump out a local HTML/text file instead. Let me know and I'll open a PR when I get the chance to work on it.
