### ISSUE TITLE
URL Announcer not Announcing

### ISSUE THREAD

**Issue by slamanna212** [sopel-irc/sopel#1081]
When i paste URLs in chat, it does not announce the title in chat. It does not work with https or http. I have no errors in the window my bot is running in either

**Comment by dgw** [comment]
I take it the issue was solved. Would you mind sharing the solution in case someone else encounters a similar issue in the future?

**Comment by slamanna212** [comment]
The issue was i included the excepting config option but left it blank, so
everything was an exception.

Don't setup new stuff on little to no sleep

**Comment by dgw** [comment]
Ah, yeah, that's an issue. Glad you sorted it out, and welcome to the Sopel-verse!

And I have done that, lol.
