### ISSUE TITLE
Receiving whispers on Twitch irc servers

### ISSUE THREAD

**Issue by wdm** [sopel-irc/sopel#1088]
Sopel does not receive /w on Twitch irc servers. I'm sending `CAP REQ :twitch.tv/tags twitch.tv/commands` capabilities in irc.py, but that alone doesn't seem to work.
It might have to do with their implementation of whispers. Does anyone have a workaround for receiving them?

**Comment by maxpowa** [comment]
Make sure you're requesting the right caps, might need `twitch.tv/membership` so Sopel knows its presence. `twitch.tv/commands` seems pretty useless as the commands it adds aren't supported by IRC spec or Sopel.

**Comment by harrymilne** [comment]
Whispers are sent via a different server connection.

**Comment by maxpowa** [comment]
Closing this as I don't think Twitch is worth supporting, they insist on being different and refuse to implement proper IRCv3 spec. If anyone wants to submit a PR to make this work feel free, but I don't think it's worth supporting.
