### ISSUE TITLE
[Suggestion] Multi network support

### ISSUE THREAD

**Issue by jacnoc** [sopel-irc/sopel#1094]
I've seen this feature in other bots and I think it's really useful. The ability to connect to multiple networks with one config file.

A possible way to implement it, is suggested below:

```
[freenode]
nick = Bot
host = irc.freenode.net
use_ssl = true
port = 6697
bind_host = 2604:180:1:94e:1337:0:df7b:a
modes = +Rp-ix
channels = ##Joshua
auth_method = sasl
auth_username = Bot
auth_password = passwordhere

[espernet]
nick = Bot2
host = irc.esper.net
use_ssl = true
port = 6697
bind_host = 2604:180:1:94e:1337:0:df7b:a
modes = +Rp-ix
channels = #Joshua
auth_method = sasl
auth_username = Bot2
auth_password = passwordhere
```

**Comment by maxpowa** [comment]
This isn't very reasonable with the current structure of the bot or config. The core of the bot is not designed to be connected to multiple servers at once and would likely require a lot of work to make it so. It's far easier to just run multiple instances with each pointing to its own config file (`sopel -c config.cfg`).

**Comment by dgw** [comment]
I'd say this is mostly covered by #1059 (or otherwise running multiple instances manually). But I'll leave it open as a feature request for some future major release, I guess.

**Comment by Exirel** [comment]
Yeah, I agree, it's way easier to run multiple instance of Sopel, each with its own configuration file.
I think there is room for improvement on how Sopel is configured, how to select configuration, etc. but overall, it's fairly easy to connect to multiple server with Sopel.

I think it's safe to close the issue, clean up is good for you! :D

**Comment by dgw** [comment]
Yep, the scale of rewrite this would require is out of the question. Overhead from running multiple instances connected to different networks is pretty minimal, so no reason to devote dev hours to that.
