### ISSUE TITLE
SSLError with https sites. 

### ISSUE THREAD

**Issue by iampureevil** [sopel-irc/sopel#1099]
It looks like SSL verification fails on HTTPS enabled sites. Using Python 2.7 I get the following error:

_SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (file "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 477, in send)_

**Comment by dgw** [comment]
This is likely related to using Python 2.7 without the requirements for SNI. https://stackoverflow.com/questions/18578439/using-requests-with-tls-doesnt-give-sni-support/18579484#18579484

**Comment by maxpowa** [comment]
@iampureevil Can you verify this is still happening after installing the requirements for SNI?

**Comment by TaxiZaphod** [comment]
I can verify that these SSL errors went away for me after I installed the packages in the stackoverflow page that dgw linked to above.

**Comment by maxpowa** [comment]
I'm going to close this since the solution appears to be installation of the requirements for SNI.
