### ISSUE TITLE
IPython error

### ISSUE THREAD

**Issue by Nuvelle** [sopel-irc/sopel#1100]
I have a fresh install of Sopel running on 2.7.

I installed IPython using pip install (it didnt install with Sopel).

I now get the following when running the bot:

> Welcome` to Sopel. Loading modules...
> 
> /usr/local/lib/python2.7/site-packages/IPython/utils/io.py:86: DeprecationWarning: IOStream is deprecated since IPython 5.0, use sys.{stdin,stdout,stderr} instead
>   stdin = IOStream(sys.stdin, fallback=devnull)
> /usr/local/lib/python2.7/site-packages/IPython/utils/io.py:87: DeprecationWarning: IOStream is deprecated since IPython 5.0, use sys.{stdin,stdout,stderr} instead
>   stdout = IOStream(sys.stdout, fallback=devnull)
> /usr/local/lib/python2.7/site-packages/IPython/utils/io.py:88: DeprecationWarning: IOStream is deprecated since IPython 5.0, use sys.{stdin,stdout,stderr} instead
>   stderr = IOStream(sys.stderr, fallback=devnull)
> Error loading ipython: 'OutputRedirect' object has no attribute 'isatty' (../IPython/terminal/interactiveshell.py:77)
> 
> Registered 40 modules,
> 1 modules failed to load
> 
> Connecting to

**Comment by maxpowa** [comment]
Seems like somewhere the workaround we're doing to pass regular stdout/stdin to iPython isn't working anymore. Might require some working around, or just adding `isatty` to OutputRedirect.

**Comment by blip** [comment]
New install, quick summary: 
- CentOS 6.8 (yum update)
- yum install python27
- pip install sopel

Same error... +1 interested in a solution.

**Comment by dgw** [comment]
@alanhuang122 If you have further interest in working on IPython stuff after #1263, this would be a great place to start. :)

**Comment by dgw** [comment]
Preemptively closing this as we get closer to merging #1684 and/or #1678. One way or the other, this bug will be rendered a non-issue Soon™.
