### ISSUE TITLE
Gist .help instead of privately messaging the user with flood.

### ISSUE THREAD

**Issue by Zarthus** [sopel-irc/sopel#1105]
Not only does the help at some times take a minute to send, it is also very floody and fits better as something posted to a pastebin service.

Relevant to #1080, where it describes the same issue but that issue is described and labelled as a bug, and this is more a feature request and enhancement. Feel free to merge the issues if you think it is a duplicate issue.

**Comment by dgw** [comment]
Specifically, #1080 looks at it as a regression—`.help` was nowhere near as floody before the overhaul to output commands for each module on a separate line.

I'm generally in favor of this. Even though I would prefer a generated `.txt` or `.html` file stored in Sopel's home directory that a web server could then serve up, I realize not all Sopel instances will be running on httpd-capable hosts.

**Comment by embolalia** [comment]
Yeah, a generated HTML that could be served up would be best, but you're right that it wouldn't work for everyone. A gist is a really good idea.

**Comment by Zarthus** [comment]
Hey @embolalia, thanks for fixing this!

I've got only a few minor bullet points that you might wish to work in to a future patch; but I've no association with Sopel's codebase at all, and honestly none of them are very pressing issues.

- There seems to be a mixing of " and ' type strings.
- I would personally make the gists anonymous, considering it's a lot of the same content repeatedly.
- There's a small amount of duplicate code on failure (specifically to `bot.say`). Personally I'd let the user know why it went wrong to begin with.
  - The alternative solution is to drop all the "Sorry something went wrong" `bot.say`, and reply the message [here](https://github.com/sopel-irc/sopel/commit/fa89eb733b39415248aaa9f07d5259d2e3bd49d2#diff-fc2412297d1c1c156e2a0aa40ff2bdcbR65) instead
- If you want to optimize it a little bit, you could cache the first time you've pasted the command list successfully (assuming commands don't change dynamically, and that there's no way to hook into module loading/unloading), and returning that link. Flooding gist a little bit less, and also having a faster response overall.
