### ISSUE TITLE
Sopel not aware of topic changes

### ISSUE THREAD

**Issue by dword4** [sopel-irc/sopel#1107]
As far as I can tell Sopel only keeps track of the topic upon entering a channel, if I use either /topic from my IRC client or .topic to make it change the topic its completely unaware of any changes and if I run the command I built to show the current topic (ideally to be run before invoking another command to change the topic) it never detects changed topics even if I force a reload of the bot, the only way it will detect a new topic is if I kill it and restart it or join/part the channel.

Running Sopel 6.3.1 on Centos 7.2.1511 and its been installed and updated via pip

Code in question that I used to test this is here 

https://gist.github.com/dword4/3e0d38421cf81822af18d698adc3e709

**Comment by dgw** [comment]
There is topic tracking near the end of `coretasks.py` (around line 700 in current master), but it only updates `bot.channels`, not `bot.privileges`.

**Comment by dword4** [comment]
That is where I pull the topic from in my test code but as far as I can tell its only updated when the bot first joins a channel

**Comment by maxpowa** [comment]
@dword4 may I ask what network you're experiencing this on? If I recall correctly there's some ircds which handle topic changes differently and send non-spec reply codes.

**Comment by dword4** [comment]
InspIRCd-2.0 is what it identifies as when I connect, if necessary I can get the full version if it will make a difference.

**Comment by maxpowa** [comment]
InspIRCd sends topic updates using the `TOPIC` prefix. Should be easy enough to add support for it in the existing code, just another `@event` decorator.
