### ISSUE TITLE
nick_blocks

### ISSUE THREAD

**Issue by rinzes** [sopel-irc/sopel#1108]
Sopel v. 6.3.1 nick_blocks not working in core cfg ie: nick_blocks = nick1,nick2,nick3

When any of the above nicks post a url Sopel posts the url results

**Comment by psachin** [comment]
@rinzes It works as expected

![1108](https://cloud.githubusercontent.com/assets/909861/17246342/fbe49c7e-55a8-11e6-9047-55d33f9447c6.png)

Nick 'cshastri' is blocked on BB-8_

@maxpowa NOTABUG

**Comment by maxpowa** [comment]
No info provided, I'm going to close this.
