### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'

### ISSUE THREAD

**Issue by psachin** [sopel-irc/sopel#1112]
for BZ

https://bugzilla.redhat.com/show_bug.cgi?id=1334618

```
Signature: TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode' (file "/usr/lib/python2.7/site-packages/sopel/modules/bugzilla.py", line 80, in show_bug)
from psachin at 2016-07-28 15:07:21.534591. Message was: https://bugzilla.redhat.com/show_bug.cgi?id=1334618#c15
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sopel/bot.py", line 441, in call
    exit_code = func(sopel, trigger)
  File "/usr/lib/python2.7/site-packages/sopel/modules/bugzilla.py", line 80, in show_bug
    (bug.get('priority') + ' ' + bug.get('bug_severity')),
TypeError: unsupported operand type(s) for +: 'NoneType' and 'unicode'
```

**Comment by maxpowa** [comment]
Unfortunately the given bugzilla bug no longer exists. If you can reproduce with another, can you please provide it?

**Comment by psachin** [comment]
@maxpowa I see that the bug no longer exists in latest code. But, I don't see any reply from the bot(for this particular bug-id)
![sopel_bz_no_reply_from_bot](https://cloud.githubusercontent.com/assets/909861/17238922/874c6b56-557d-11e6-93ec-eb402655f3f7.png)

All I see is the deprecated warning, which is expected.

**Comment by psachin** [comment]
I see the error

> WARNING:sopel.modules.bugzilla:Bugzilla error: NotPermitted

May be because it is private?

**Comment by psachin** [comment]
@maxpowa How about this?

![bz_is_private](https://cloud.githubusercontent.com/assets/909861/17245371/d5f4606c-55a3-11e6-8d6c-92e67058d4f1.png)
