### ISSUE TITLE
Missing `verify_ssl` 

### ISSUE THREAD

**Issue by psachin** [sopel-irc/sopel#1118]
I see few more module where we need to take care of `verify_ssl`

```
find_updates.py:    info = requests.get(version_url).json()
movie.py:    data = requests.get(uri, params={'t': word}, timeout=30).json()
translate.py:    result = requests.get(url, params=query, timeout=40, headers=headers).text
xkcd.py:    data = requests.get(url).json()
```

Also, if `verify_ssl=False`, we can disable warning.

[https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings](https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings)

**Comment by elad661** [comment]
This makes no sense. At all. 

There's absolutely no good reason to disable TLS verification in these modules or any other modules. verify_ssl should only be for core, for people who, for some weird reason, wish to connect to IRC servers with self signed certificates over TLS.

On the long term, it'd be better to implement certificate pinning for this usecase, and *not* provide an option to disable TLS verification completely.

**Comment by anarcat** [comment]
this is still happening in the xkcd module:

```
14:49:23 <@anarcat> http://xkcd.com/1779/
14:49:23 <peoplesmic> TypeError: numbered_result() missing 1 required positional argument: 'verify_ssl' (file "/usr/lib/python3/dist-packages/sopel/modules/xkcd.py", line 124, in get_url)
```

PR coming up.

**Comment by antdude** [comment]
When will this fix be released?

**Comment by tylerhoot** [comment]
kinda still needed and issue still lives in xkcd AND in url

**Comment by antdude** [comment]
Still no fix? :(

**Comment by psachin** [comment]
@anarcat  The fixed is merged -- https://github.com/sopel-irc/sopel/pull/1123

@tylerhoot It is fixed for xkcd in -- https://github.com/sopel-irc/sopel/pull/1123, if you still encounter this in url can you raise an issue?
