### ISSUE TITLE
Sopel v6.3.1 quits and fails to reconnect after being disconnected for a while?

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1125]
Basically, my cable's Internet got disconnected for a bit.  After my Internet came back, I noticed Pip (Python v3)'s Sopel process was not running so it could never reconnect. :(

**Comment by maxpowa** [comment]
Post your stdio.log to gist.github.com and paste the link here.

**Comment by antdude** [comment]
My unstable Internet connection just happened again. It seems like Sopel process goes away during the Internet outages. Here you go: https://gist.github.com/antdude/540f333902bb2d3ae52d2fe45cd0ebbc

**Comment by maxpowa** [comment]
Looks like your system completely loses the ability to resolve the host you've given. It's intended that sopel quits in this case as it's a network failure that is unlikely to happen in a regular environment (and usually unlikely for the network to recover on its own). If you need to restart sopel in cases like this, you can wrap it with a bash keep alive script.

**Comment by antdude** [comment]
Thanks Maxpowa. Do we have an existing script already? I am not a coder. :( I know my cable modem becomes responsive during Internet outages.

**Comment by maxpowa** [comment]
http://stackoverflow.com/a/697064/6684400

**Comment by antdude** [comment]
Also: " Ping timeout reached after 120 seconds, closing connection
Calling shutdown for 0 modules.
Closed!"

I just noticed two minutes. Is there a way to make that longer?
