### ISSUE TITLE
New sopel-rss module

### ISSUE THREAD

**Issue by RebelCodeBase** [sopel-irc/sopel#1128]
When I was looking around for an rss2irc app I came across the sopel framework and recognized its power and stamina. Thanks a lot for all your work! 

I've looked around for an rss module but was disappointed to see that it had been deprecated (#693). I looked around for a new implementation and found [f4bio/sopel-rss](https://github.com/f4bio/sopel-rss) which was very basic but provided at least a starting point. 

After some pull request f4bio granted me permission for his repo and I happily coded away. But after some time I noticed that I did not like the approach he suggested any more and so I've created my own project: [RebelCodeBase/sopel-rss](https://github.com/RebelCodeBase/sopel-rss)

The module hashes rss feed items and stores these hashes in a ring buffer per feed in memory and in an sqlite table on disk. One can set a format that determines which feed item fields will be hashed and which feed items will be posted to the channel associated to the feed. It uses [feedparser](https://github.com/kurtmckee/feedparser) as backend.

There is a git-like subcommand structure and detailed documentation: in IRC, as a [README](https://github.com/RebelCodeBase/sopel-rss/blob/master/README.md) and through lots of comments in code. The module is based on Python 3 and it is extensively tested through py.test.

Currently, I see this project as version 0.1 so it needs some real life testing. I am already running it "in production" but I am sure that there are still bugs. I'd be happy if you could have a look and provide feedback.

**Comment by maxpowa** [comment]
Awesome! Thanks for posting this here. You can distribute your module on pypi if you restructure it as a [sopel-cookiecutter](https://github.com/sopel-irc/sopel-cookiecutter) module, then anyone could just do `pip install sopel_modules.rss`

I'm going to close this though because it's not an issue per se.
