### ISSUE TITLE
do not set restart bot delay in systemd

### ISSUE THREAD

**Issue by anarcat** [sopel-irc/sopel#1130]
systemd has pretty good settings to keep runaway processes from going crazy. for example, there are `StartLimitInterval=, StartLimitBurst=` settings that keep a process from being spawned more than 5 times in 10 seconds, at which point it is deactivated.

I believe that the 30 seconds delay present in the sample `.service` file should be removed for this setting to work. i am not sure why that delay is present, it feels it just makes everything more sluggish without good reasons, unless I am missing something.

I would suggest the following patch:

```
diff --git a/contrib/sopel.service b/contrib/sopel.service
index 27e7d98..4686b21 100644
--- a/contrib/sopel.service
+++ b/contrib/sopel.service
@@ -10,7 +10,6 @@ PIDFile=/run/sopel/sopel-sopel.pid
 ExecStart=/usr/bin/sopel -c /etc/sopel.cfg
 Restart=on-failure
 RestartPreventExitStatus=2
-RestartSec=30
 Environment=LC_ALL=en_US.UTF-8

 [Install]
```

**Comment by maxpowa** [comment]
I _think_ the reasoning behind the 30 second delay is to allow the IRC server to process the bot leaving, before having the bot connect again (to prevent nick conflict). A shorter delay would probably be fine in most cases though.

**Comment by anarcat** [comment]
ah yes, okay that makes sense... but then yes, maybe 5 or 10 seconds should be enough?

**Comment by anarcat** [comment]
i can confirm the patch given fails: systemd fails to restart sopel under certain circumstances...

```
[1002]anarcat@marcos:~$ sudo service sopel status
[sudo] password for anarcat:
● sopel.service - Sopel IRC bot
   Loaded: loaded (/etc/systemd/system/sopel.service; enabled)
   Active: failed (Result: start-limit) since ven 2016-09-23 10:52:42 EDT; 21h ago
     Docs: http://sopel.chat/
  Process: 30844 ExecStart=/usr/bin/sopel -c /etc/sopel.cfg (code=exited, status=0/SUCCESS)
 Main PID: 30844 (code=exited, status=0/SUCCESS)

sep 23 10:52:42 marcos systemd[1]: sopel.service holdoff time over, scheduling restart.
sep 23 10:52:42 marcos systemd[1]: Stopping Sopel IRC bot...
sep 23 10:52:42 marcos systemd[1]: Starting Sopel IRC bot...
sep 23 10:52:42 marcos systemd[1]: sopel.service start request repeated too quickly, refusing to start.
sep 23 10:52:42 marcos systemd[1]: Failed to start Sopel IRC bot.
sep 23 10:52:42 marcos systemd[1]: Unit sopel.service entered failed state.
```

i am testing now with delay=10, but maybe this whole thing is actually necessary as is after all.

**Comment by dgw** [comment]
Closing per the past discussion indicating that the delay is probably needed.
