### ISSUE TITLE
error on first run

### ISSUE THREAD

**Issue by Rimann91** [sopel-irc/sopel#1134]
`Traceback (most recent call last):`
  `File "/usr/local/bin/sopel", line 5, in <module>
    from pkg_resources import load_entry_point`
  `File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()`
 ` File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)`
  `File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())`
  `File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 632, in resolve`
    `raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.`

`VersionConflict: (requests 2.2.1 (/usr/lib/python2.7/dist-packages), Requirement.parse('requests>=2.3.0'))`

I see that i'm having a version conflict? But my python version is within the requested requirements? I believe that i am not understanding this error. Do i not have the right version of sopel?

**Comment by rinzes** [comment]
Requests for python 2.7 is version 2.11.1

**Comment by maxpowa** [comment]
@Rimann91 the problem you're experiencing is because you already have requests `2.2.1` installed in your system but sopel requires at least `2.3.0`. Either install sopel inside a virtualenv or upgrade your system requests version.
