### ISSUE TITLE
Channel.privileges not being filled in

### ISSUE THREAD

**Issue by johnlage** [sopel-irc/sopel#1136]
Every nick in Channel.privileges is being marked as 0 (no privileges).
This needs to be fixed because the docs tell you to use bot.channels over bot.privileges, and some people may become confused by the bot not recognizing anyone as op/voice.

Sopel Version: current master.
Python Version: 3

**Comment by dgw** [comment]
I figured this was already on the radar, but good to have the issue in case it wasn't.

It's the reason all of my modules that access privileges still use the deprecated array.

**Comment by dgw** [comment]
Note: At time of issue opening, current master was v6.4.0.

**Comment by dgw** [comment]
Definitely needs testing and sorting (if it still exists in 6.5.x) before 7.0. Looooong before, ideally.

**Comment by dgw** [comment]
I just tested it. (Finally, a use for the `ipython` module! lol) The results aren't pretty.

````
In [3]: bot.channels['#dgw'].privileges
Out[3]:
{Identifier('dgw'): 0,
 Identifier('GlaD0S'): 0,
 Identifier('Internets'): 0,
 Identifier('Kaede'): 0,
 Identifier('Sopel'): 0}

In [4]: bot.privileges['#dgw']
Out[4]:
{Identifier('dgw'): 20,
 Identifier('GlaD0S'): 12,
 Identifier('Internets'): 0,
 Identifier('Kaede'): 12,
 Identifier('Sopel'): 0}
````

This needs a test when fixed, too, to make sure it _keeps_ working.

**Comment by dgw** [comment]
Hey @johnlage, I could use a tester for https://github.com/sopel-irc/sopel/compare/master...dgw:fix-bot.channels.privileges to see if I missed any cases.
