### ISSUE TITLE
Is there a manual for sopel_modules.github sopel_modules.idlerpg?

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1137]
How do I use it? All I have is: .irpg <start|resume|pause> - Resume or pause idlerpg in the current channel

Thank you in advance. :)

**Comment by dgw** [comment]
Best to ask @maxpowa or poke around the [maxpowa/sopel-github](https://github.com/maxpowa/sopel-github) and [maxpowa/sopel-idlerpg](https://github.com/maxpowa/sopel-idlerpg) repos.

**Comment by antdude** [comment]
Thanks. :)
