### ISSUE TITLE
Ability to request custom capabilities

### ISSUE THREAD

**Issue by jotumn** [sopel-irc/sopel#1141]
Needed mainly for the twitch integration. To properly support some twitch features, bot has to request
```
CAP REQ :twitch.tv/tags twitch.tv/commands
```

**Comment by maxpowa** [comment]
If you're writing your own module you can use `bot.cap_req` in the `setup` function of your module. https://sopel.chat/docs/bot.html#sopel.bot.Sopel.cap_req

**Comment by jotumn** [comment]
Ah, wonderful. I need to start reading documentation more carefully.
