### ISSUE TITLE
cannot install on windows because of 'enchant' module error

### ISSUE THREAD

**Issue by tsvikas** [sopel-irc/sopel#1142]
'enchant' does not install on 64bit windows (https://github.com/rfk/pyenchant/issues/42 ), so it prevents my `pip install sopel`. 

If the dependency was optional, it would solve the issue.

**Comment by alanhuang122** [comment]
I rewrote the spellcheck module to use aspell (#1164), and I could probably add in the code to make it optional, like remind does with pytz.

**Comment by dgw** [comment]
Will either be "fixed" by moving to aspell in Sopel 7, or the issue will simply change from one bad dependency to another… We'll see once the `spellcheck` rewrite is finalized.

**Comment by dgw** [comment]
#1164 is merged to `master` now, with the switch to `aspell` included, so now's a good time to determine if we need to do anything more regarding installing on Windows. Unfortunately it looks like the `aspell` Python bindings are not any more "currently maintained" than the `enchant` ones—last commit was in 2016.

**Comment by Exirel** [comment]
@dgw reading things on the Internet tells me that aspell is as annoying to install on Windows than enchant is. So same problem, it appears.

I still think the solution is also the same: extract `spellcheck` in its own Sopel plugin.

**Comment by dgw** [comment]
I'm gonna close this because we don't use `enchant` any more, and we soon won't use `aspell` either (see #1642). No point in keeping this issue open; we're going to eliminate the problem one way or another.
