### ISSUE TITLE
Amazon.com URLs show "500 Service Unavailable Error" error results.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1143]
Hello.
...
11:30AM <R_Daneel> https://smile.amazon.com/dp/B01BNPT1EG/ref=wl_it_dp_o_pC_nS_ttl?
11:30AM <URL> [ 500 Service Unavailable Error ] - smile.amazon.com
[11:30am] <Ant> Oh, I thought\ he picks the one for you.
[11:30am] <Ant> -\
[11:30am] <Ant> https://smile.amazon.com/dp/B01BNPT1EG/
11:30AM <URL> [ 500 Service Unavailable Error ] - smile.amazon.com
[11:30am] <Ant> weird
[11:30am] <Ant> https://amazon.com/dp/B01BNPT1EG/
11:30AM <URL> [ 500 Service Unavailable Error ] - amazon.com
[11:30am] <Ant> http://amazon.com/dp/B01BNPT1EG/
11:30AM <URL> [ 500 Service Unavailable Error ] - amazon.com
11:30AM <R_Daneel> http://www.nexcess.net
11:30AM <URL> [ Magento Hosting – WordPress Web Hosting | Nexcess ] - www.nexcess.net
...
[11:33am] <Ant> http://amazon.com
11:33AM <URL> [ 500 Service Unavailable Error ] - amazon.com
...
[11:34am] <Ant> .version
11:34AM <URL> Ant: Sopel v. 6.4.0
...

Using Python 3.4.2 (default, Oct  8 2014, 10:45:20). Thank you in advance. :)

**Comment by maxpowa** [comment]
This is due to Amazon rejecting the user agent Sopel uses in `url.py`. Not sure if we want to fake being a browser, but it would end up being more accurate.

**Comment by dasu** [comment]
Seems like it only fails on request's default User-Agent ('python-requests/2.10.0')
If we set a User-Agent in the header to something like 'Sopel IRC bot', it will go through (tested and works).
Although Amazon may end up banning it if they see a huge uptick in that user-agent...unlikely though.

**Comment by embolalia** [comment]
Fixed in c8ef3d54917cd7cdd243bb15456c3b8634b3e6f2
