### ISSUE TITLE
feature request: prevent parallel execution of interval

### ISSUE THREAD

**Issue by IARI** [sopel-irc/sopel#1144]
My bot is polling some info via http request every couple of seconds.
I noticed that at least at startup the bot issues multiple polls concurrently - a behavior that I would like to prevent.
This is a simplified version of my approach:

``` python
@sopel.module.interval(5)
def poll_dpm(bot):
    state = botstate()
    if state.POLLING:
        print("polling already ...", flush=True)
        return

    state.POLLING = True
    print("polling ...", flush=True)
```

`state = botstate()` is getting an object which fetches a boolean from the bots memory, bot checks a Threading.Lock which is also stored in the bots memory.

Usually this works, but when the bot is starting, sometimes i still notice that two polls happen in paralell before my lock is set.

Output at startup:

> ...
> Connected.
> Initializing POLLING=False
> polling ...polling ...
> polling already ...

Without the lock this happens a lot more often. Still im facing a mutual exclusion problem.
I believe it could make sense, to natively support enforcing non-paralell execution of scripts.

**Comment by dgw** [comment]
There's `@sopel.module.thread(False)`, but for a function running every five seconds that could prove to slow down the rest of the bot considerably.

**Comment by Exirel** [comment]
With the new interface for job scheduling, this feature is becoming easier: jobs are represented by the `sopel.tools.jobs.Job` class, and a job is run if and only if its method `Job.is_ready_to_run()` returns true.

It means that if we allow to use a different type of job, we can make an implementation of that method that would check on something like "hey, are you already running or something?".

Anyway, that's doable. :+1:

**Comment by Exirel** [comment]
I postpone that to Sopel 7.1. I still think that's doable, but I'd rather spend time on other priorities for now.

**Comment by dgw** [comment]
@Exirel Still 7.1 or wait for 8.0? (Will it be easier to do after we drop old Pythons?)

**Comment by Exirel** [comment]
Sopel 7.1. I'll do it.
