### ISSUE TITLE
How do I let Sopel invite a user?

### ISSUE THREAD

**Issue by ghost** [sopel-irc/sopel#1145]
^

**Comment by dgw** [comment]
#1157 is a start on this. If @converge is no longer willing to work on it, implementing the feature will be up for grabs. (Or maybe I'll just finish that PR myself.)

**Comment by dgw** [comment]
I'd include the rewritten code from #1157 in 6.6.0, but it's not done. The `1157-rebase` branch is safe in my Sopel repo, and I'll work on it more after version 6.6.0 is out.

**Comment by dgw** [comment]
Revived the implementation of this in #1497.
