### ISSUE TITLE
version issue?

### ISSUE THREAD

**Issue by g1lby** [sopel-irc/sopel#1146]
any idea on this?:

[root@centos sopel]# pip install sopel
DEPRECATION: Python 2.6 is no longer supported by the Python core team, please upgrade your Python. A future version of pip will drop support for Python 2.6
Collecting sopel
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/lib/python2.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
  Using cached sopel-6.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-18K5pI/sopel/setup.py", line 5, in <module>
        from sopel import **version**
      File "sopel/**init**.py", line 17, in <module>
        if sys.version_info.major > 2:
    AttributeError: 'tuple' object has no attribute 'major'

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-18K5pI/sopel/

machine is running centos 6.8
with kernel x86_64 Linux 2.6.32-042stab092.3
and the following python packets via repos installed:
python-pycurl-7.19.0-9.el6.x86_64
python-iniparse-0.3.1-2.1.el6.noarch
python-urlgrabber-3.9.1-11.el6.noarch
python-inotify-0.9.1-1.el6.noarch
python-setuptools-0.6.10-3.el6.noarch
python-lxml-2.2.3-1.1.el6.x86_64
python-2.6.6-66.el6_8.x86_64
python-pip-7.1.0-1.el6.noarch
python-libs-2.6.6-66.el6_8.x86_64
python-dns-1.12.0-centos6.15081418.noarch

even though python suggests me to update python itself, it is not possible. yum says that it is already the latest version installed

**Comment by dgw** [comment]
Yes: Update the system to Python 2.7 (and install SSL requirements - see #1099) or Python 3.4+. The problem is described by the error messages before the "error" in Sopel's setup routine.

**Comment by embolalia** [comment]
Sopel does not support Python 2.6. It looks like you're running an old version of CentOS, so the easiest solution for this is to use a [Python 3 SCL](https://www.softwarecollections.org/en/scls/rhscl/rh-python35/).
