### ISSUE TITLE
[remind] .at does not accept a future date, limiting reminders to next 24 hours

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1148]
I do not see any past (closed) issue about this, but the possible use cases beg the question: Why doesn't `.at` take a date in addition to a time?

It would allow scheduling reminders at a specific time more than 24 hours in the future, without first manually calculating the time difference and feeding it to `.in` instead.

**Comment by alanhuang122** [comment]
I actually wondered that myself, and hacked together a fix that addresses this issue. The referenced PR fixes this issue, though I have not tested it on machines where pytz is not installed. (I was originally only writing the code for personal use, and didn't think to include support for that)

**Comment by dgw** [comment]
Pushed to 7.0.0, because #1162 was pushed there.

**Comment by Exirel** [comment]
I'll work on that, reusing code from @alanhuang122
