### ISSUE TITLE
Add private option to .tell

### ISSUE THREAD

**Issue by ghost** [sopel-irc/sopel#1151]
Or at least add a setting or something that way the channel doesn't get spammed by people telling each other stuff.

**Comment by dgw** [comment]
PMs would probably be better than notices, for the reason that many clients, by default, don't put notices in particularly noticeable places (and sometimes don't even notify the user that they've received one).

That said, the real issue IMO is that people are using `.tell` when they shouldn't be, if the channel is getting "spammed".

**Comment by dgw** [comment]
Probably not `NOTICE`, but I can definitely see a global setting for whether messages sent using `.tell` or `.ask` should be sent in `PRIVMSG` to the channel or the user only.

**Comment by Exirel** [comment]
I'm on it! 👍
