### ISSUE TITLE
[etymology] HTML entities not decoded before output

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1153]
The `etymology` module does not decode HTML entities in the snippet before sending it to the channel. This results in printing snippets like this:

````
<Sopel> "Old English w&aelig;ter, from Proto-Germanic *watar (source also
        of Old Saxon watar, Old Frisian wetir, Dutch water, Old High German
        wazzar, German Wasser, Old Norse vatn, Gothic wato 'water'), from
        PIE *wod-or, from root *wed- (1) 'water, wet' (source also of
        Hittite [...]" - http://etymonline.com/?term=water
````

**Comment by Vault108** [comment]
Hello,

I added
` s = s.replace('&aelig;', "\u00E6")`
under
` def unescape(s): `

so it now reads: 


```
def unescape(s):
    s = s.replace('&gt;', '>')
    s = s.replace('&lt;', '<')
    s = s.replace('&amp;', '&')
    s = s.replace('&aelig;', "\u00E6")
    return s
```

Giving us the Following output:

> <@VaultsBot>: "Old English wæter, from Proto-Germanic *watar (source also of Old Saxon watar, Old Frisian wetir, Dutch water, Old High German wazzar, German Wasser, Old Norse vatn, Gothic wato 'water'), from PIE *wod-or, from root *wed- (1) 'water, wet' (source also of Hittite watar, [...]" - http://etymonline.com/?term=water

**Comment by dgw** [comment]
Frankly, I don't think this module should implement its own `unescape(s)` function when there are stdlib tools that do it already. So I implemented a solution that uses the built-in methods.
