### ISSUE TITLE
remind: certain characters break loading the "database"

### ISSUE THREAD

**Issue by phixion** [sopel-irc/sopel#1154]
Adding this line as a reminder breaks remind.py:

`( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ ^B^]^_ITS CARDBACK TIME!!!!!!!!!!!!!!!!!!!!!!!^B^]^_( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ( •ᴗ•)ψ`

it breaks with:

Error in remind setup procedure: need more than 1 value to unpack (modules/remind.py:38)

**Comment by ridelore** [comment]
It is probably related to https://github.com/sopel-irc/sopel/issues/1055 - sorry should've searched first

**Comment by dgw** [comment]
Issue history mess brought to you by late-night @dgw brain.

Closing as "duplicate" of #1055, but I'll put the example given here into that issue.
