### ISSUE TITLE
.ddg results coming back with encoding problems.

### ISSUE THREAD

**Issue by UncleanlyCleric** [sopel-irc/sopel#1167]
The best examples I can provide is this:

<Junya_Work> .ddg testing
<Minerva> Junya_Work: /l/?kh=-1&uddg=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSoftware_testing
<Junya_Work> .g testing
<Minerva> Junya_Work: /l/?kh=-1&uddg=https%3A%2F%2Fen.wikipedia.org%2Fwiki%2FSoftware_testing
<Junya_Work> .search testing
<Minerva> Junya_Work: - (b), /l/?kh=-1&uddg= (d)

I've checked to make sure that I'm not using version 4.0 or greater with PRAW, and as far as I'm aware there's been no major version jumps on Python.

junya@suspiration:$ pip show praw
Name: praw
Version: 3.5.0
Summary: PRAW, an acronym for `Python Reddit API Wrapper`, is a python package that allows for simple access to reddit's API.
Home-page: https://praw.readthedocs.org/
Author: Bryce Boe
Author-email: bbzbryce@gmail.com
License: GPLv3
Location: /usr/local/lib/python2.7/dist-packages
Requires: six, decorator, requests, update-checker

junya@suspiration:$ python --versionPython 2.7.12

Is there anything else I should check on?

**Comment by spockers** [comment]
Same here. I updated earlier and had to downgrade PRAW to get reddit working, now this. ;/

**Comment by UncleanlyCleric** [comment]
I tried rolling back to 3.4.0 and that didn't change the behavior.  I'm thinking that's not the issue here.

**Comment by spockers** [comment]
No, it's not, I only mentioned it because you did. PRAW is only for reddit, unless I missed something. The encoding issue is with the search module, nothing to do with PRAW afaik.

**Comment by UncleanlyCleric** [comment]
I realized that right as I left work. :)

The problem seems to be with the way search is being interpreted by python.  I'm guessing somewhere along the way I updated to a version that search.pl doesn't like.  

I'll keep poking.

**Comment by jfleach** [comment]
DuckDuckGo changed their APIs, someone in #sopel (freenode) is working on a fix.

**Comment by dasu** [comment]
I have a modified version of search.py for my bot, but the fix for me was inserting a fake user-agent for the request in duck_search function.  Seems like it doesn't like requests' default user-agent.  (I used a popular chrome user-agent, not sure if a sopel user-agent similar to what was used implemeneted in url.py recently would potentially work.)

**Comment by spockers** [comment]
Can you share it?

**Comment by alanhuang122** [comment]
User-Agent 'Sopel' does not work; can confirm that using a Chrome user-agent does, though.

**Comment by dasu** [comment]
@spockers Nope, it differs too greatly.  I was also trying the fix via sopel's intended way, but was running into issues.   However I did seem to find the issue, and proposed solution:
If you were to add a custom headers to web.get(), it doesn't seem to go through.  A [closer look at web.py](https://github.com/sopel-irc/sopel/blob/master/sopel/web.py#L119) seems to show that the headers are being set to blank by accident, if a custom header is set.  The resolution is remove the 'headers =' from that line, and that'll allow you to set a popular headers in search.py, which should make it function again.

**Comment by JonnyPtn** [comment]
I'm by no means a python expert, so apologies if I'm barking entirely up the wrong tree, but using urrlib.unquote instead of web.decode tidies the link up, except for the "/l/?kh=-1&amp;uddg=" which seems to prepend every link.

could it perhaps be the URL format returned by ddg is just different?

**Comment by UncleanlyCleric** [comment]
Here's our temporary solution to the issue.  In web.py we ended up changing the user agent string directly as such:

`#USER_AGENT = 'Sopel/{} `(http://sopel.chat)'.format(__version__)`
`USER_AGENT` = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.95 `Safari/537.36'.format(__version__)`
`default_headers` = {'User-Agent': `USER_AGENT}`
`ca_certs` = None  # Will be overriden when config loads. This is for an edge case.`

I'm sure this isn't a /great/ solution.  But we're going to use it short term until there's a patch or something.

**Comment by dasu** [comment]
Just created #1171,
 I don't like the idea of having a fake user-agent for every single module that might use the web module, so only setting it to the duck_search function in search.py.

**Comment by UncleanlyCleric** [comment]
I don't either really, but my users were getting pissed and that was the most expedient solution.  :)

I plan on removing it as soon as something official comes up.

**Comment by UncleanlyCleric** [comment]
And actually, your solution is more elegant.  I think we'll try it as well.

**Comment by antdude** [comment]
$ locate search.py
/home/ant/SopelPython3/lib/python3.4/site-packages/pip/commands/search.py
/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/search.py
/usr/lib/python2.7/dist-packages/pip/commands/search.py
/usr/lib/python2.7/dist-packages/pip/commands/search.pyc
/usr/share/doc/python-xapian/examples/simplesearch.py

**Comment by dgw** [comment]
I can no longer reproduce this with the details given in this thread. Feel free to come back with more examples and we can reopen.
