### ISSUE TITLE
call sopel from python

### ISSUE THREAD

**Issue by vladfi1** [sopel-irc/sopel#1175]
Is there a way to call sopel from my own python code or vice-versa? Simply adding `import myfile` from a sopel module doesn't work. Neither does creating a `sopel.config.Config` object in my own python code.

To clarify: I would like to run sopel completely independently of any config files on the host machine.

**Comment by ralienpp** [comment]
My current understanding is that the entry point for Sopel is `run_script`, which calls the `run` function on line 200.
 
https://github.com/sopel-irc/sopel/blob/master/sopel/run_script.py line 200
https://github.com/sopel-irc/sopel/blob/master/sopel/__init__.py line 57


In theory, if you create your config object artificially, you can feed it to `run` to  start the bot.

**Comment by dgw** [comment]
I'm not sure why this has been left open for so long. Sopel has never been intended for use as anything other than a standalone program.
