### ISSUE TITLE
Disable Sopel's "you guys" answers...

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1181]
...
10:50AM AfterShock> R_Daneel: except for the obnoxious attempt to police how people talk
10:50AM R_Daneel> agreed
10:50AM AfterShock> "you guys" is a completely legitimate colloquialism
10:50AM URL> AfterShock: Did you mean you folks?
��� URL was kicked off #linux by AfterShock (URL)
...

How do I disable this "you guys" module from Sopel? It's quite annoying. I cannot even find its module. :(

Thank you in advance. :)

**Comment by maxpowa** [comment]
Disable the 'pronouns' module

https://github.com/sopel-irc/sopel/blob/master/sopel/modules/pronouns.py

**Comment by antdude** [comment]
Thanks. I just ran "pip uninstall sopel_modules.inclusivity" to remove it. :)
