### ISSUE TITLE
Invalid http URLs make Sopel puke crazy results.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1190]
Example (also reproduced in freenode.net's official sopel bot via /msg command):
...
[01:43pm] <Ant> http://test
01:43PM <URL> requests.exceptions.ConnectionError: HTTPConnectionPool(host='test', port=80): Max
          retries exceeded with url: / (Caused by
          NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at
          0x7f9bd822d390>: Failed to establish a new connection: [Errno -2] Name or service not
          known',)) (file "/home/ant/SopelPython3/lib/python3.4/site-packages/requests/adapters.py",
          line 487, in send)
...
These should be in logs, not IRC.

Thank you in advance. :)

**Comment by dgw** [comment]
The in-progress rewrite of title fetching in #1244 (not sure if it'll stay in that PR) would fix this.

**Comment by Exirel** [comment]
I can't reproduce this bug with Sopel from the master branch. @dgw can you?

**Comment by antdude** [comment]
I can't reproduce it anymore in my Sopel v. 6.6.4. I get nothing now. I think it got fixed?

**Comment by antdude** [comment]
I am going to close this then since none of us can reproduce it. Thanks all. :)

**Comment by Exirel** [comment]
Thank you @antdude :)

**Comment by antdude** [comment]
You're welcome, Exirel. I'm glad Sopel is alive again unlike others (e.g., rbot). :)

**Comment by dgw** [comment]
@Exirel I'm sure this _was_ a bug at some point, that was simply fixed by rewritten title fetching code. Let's reserve "Invalid" for issues that really are invalid :)

**Comment by Exirel** [comment]
@dgw deal. ;)
