### ISSUE TITLE
Sopel's web lookups should not work with internal addresses like http://192.168.1.1

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1191]
Example (also reproduced in freenode.net's official sopel bot via /msg command):
[01:51pm] <Ant> http://192.168.1.1
01:51PM <URL> [ 401 Unauthorized ] - 192.168.1.1
[01:51pm] <Ant> http://192.168.100.1
01:51PM <URL> [ Touchstone Status ] - 192.168.100.1

**Comment by dgw** [comment]
Indeed, this is a potential security concern for Sopel instances running on machines with LAN access to other, possibly internal-only, services.

**Comment by antdude** [comment]
When will v7 be out?

**Comment by dgw** [comment]
When it's done.

**Comment by antdude** [comment]
Is there a roadmap or anything to watch?

**Comment by dgw** [comment]
The milestone this issue belongs to…

**Comment by deathbybandaid** [comment]
@antdude Please refer to https://github.com/sopel-irc/sopel/milestone/13
