### ISSUE TITLE
kotaku links not resolving titles properly

### ISSUE THREAD

**Issue by dasu** [sopel-irc/sopel#1197]
17:39 <user> http://kotaku.com/a-practical-guide-to-video-game-trash-talk-1795235044
17:39 <sopel> [ deadspin-quote-carrot-aligned-w-bgr-2 ] - kotaku.com

Seems to be placeholder title tags in the CSS near the beginning of the source.  The real title is at the very end.  Might be a tricky one to 'fix'.

**Comment by kwaaak** [comment]
Same as https://github.com/sopel-irc/sopel/issues/1213, try https://github.com/sopel-irc/sopel/pull/1215

**Comment by dasu** [comment]
Nice, thank you.
