### ISSUE TITLE
imdb module not working anymore

### ISSUE THREAD

**Issue by jwinterm** [sopel-irc/sopel#1198]
I just noticed that anytime you make a call to imdb now the bot responds: 

> [MOVIE] No API key provided.

I know it used to work, not sure how recently. Maybe it can be switched to a different database that doesn't require an API key?

**Comment by NeoMahler** [comment]
OMDb API made the API private :/ Read more here: https://www.omdbapi.com

El dg., 28 de maig 2017 a les 21:18, jw (<notifications@github.com>) va
escriure:

**Comment by antdude** [comment]
Private? That's dumb. :(

**Comment by NeoMahler** [comment]
It is. But I guess they need to get the money from somewhere!

El dc., 21 de juny 2017 a les 20:06, Ant (<notifications@github.com>) va
escriure:

**Comment by NeoMahler** [comment]
Rbot doesn't use the ombd API but instead read the imdb page directly. This
is a "dirtier" way to do it in my opinion, but the only (free) option at
the moment.

**Comment by antdude** [comment]
Might as well use that method. :/

**Comment by NeoMahler** [comment]
If you know Python, go on! I could probably do it if I had time, but I
think that I will have some busy weeks this summer.

**Comment by antdude** [comment]
"... Can someone port it to Sopel's Python? I am not a coder. :/ ..." in my original post. ;) However, I am willing to test it!

**Comment by NeoMahler** [comment]
Oops, I didn't read it, sorry. Well, I will add that to my to-do list.
Let's see if I find time to do it!

**Comment by kwaaak** [comment]
Works again with https://github.com/sopel-irc/sopel/pull/1195

**Comment by antdude** [comment]
Awesome. Now, I wait for the pip's release whenever that is. :/

**Comment by dgw** [comment]
I'm 95% sure there will be another pip release before the heat death of the universe, at least.

**Comment by antdude** [comment]
When is the heat death of the universe? ;)

**Comment by dgw** [comment]
[A very long time in the future.](https://en.wikipedia.org/wiki/Heat_death_of_the_universe#Time_frame_for_heat_death)

**Comment by dgw** [comment]
> I'm 95% sure there will be another pip release before the heat death of the universe, at least.

What I didn't know is that it would end up being my job to publish it, haha. Working toward 6.5.2 right now, which could include a fix for this issue if @kwaaak and/or @freeboson are available to rebase it and update the tests.

**Comment by dgw** [comment]
#1195 is scheduled for 6.6.0, so I'm punting this issue as well to match.

**Comment by antdude** [comment]
Thanks dgw. :)

**Comment by dgw** [comment]
Punting again, as #1195 no longer appears to work as-is (and was itself removed from 6.6.0).
