### ISSUE TITLE
.help only shows 1 example

### ISSUE THREAD

**Issue by hemna** [sopel-irc/sopel#1200]
Looking at the code for the calc command, it has declared several examples.  When I run ".help calc",  I always get one and only one example.

```
 <hemna> .help calc
 <pewp> hemna: Evaluate some calculation.
 <pewp> hemna: e.g. .c 5 / 2
```

The calc code is here: 
https://github.com/sopel-irc/sopel/blob/master/sopel/modules/calc.py#L22-L29

I'm writing my own module, and I am trying to get all of the examples to show, but it functions the same as the calc example above.  No matter how many `@example` decorators I have on the method, it only shows one.

**Comment by dgw** [comment]
The `@example` decorator is mostly for auto-generating tests, and the `help` module just kind of uses it too. I'm putting in a fair amount of work on `@example` for the next version, and might try to tackle this. (If I don't, @hekel might. :grin:)

**Comment by dgw** [comment]
Did some work on this in 3fe610c. Not final, subject to change, etc. Most importantly it kind of relies on #1303, so if that gets postponed so will this.

**Comment by dgw** [comment]
Pushed to Sopel 7, as my WIP solution requires a new argument to `@sopel.module.example()`, which I do not want to add in a point release.

**Comment by dgw** [comment]
Merged a fix for this that modules will have to opt into. See #1403.
