### ISSUE TITLE
Allow bot to be pinged and respond

### ISSUE THREAD

**Issue by Reception123** [sopel-irc/sopel#1211]
A nice feature would be a ping/converse function. So for example if you ping "Sopelbot" it should say "Hey {user}, do you need anything from me" or something like that.

**Comment by dgw** [comment]
````Python
from sopel.module import rule

@rule('.*$nickname.*')
def ping_converse(bot, trigger):
    bot.say("Hey, %s, do you need anything from me?" % trigger.nick)
````

Save that as `converse.py` or whatever in the modules directory and restart.

**Comment by Reception123** [comment]
Thank you!

**Comment by Reception123** [comment]
@dgw One more question, would it be possible to make the bot scan the chat and when it detects a word for example "test" in any message a user sends, it says something?

**Comment by dgw** [comment]
Sure, just replace `$nickname` with the word.

**Comment by Reception123** [comment]
Yeah, figured it out, but thanks!
