### ISSUE TITLE
help: using a pastebin should be optional

### ISSUE THREAD

**Issue by kkirsche** [sopel-irc/sopel#1212]
Not all environments are public environments where it is appropriate to post commands  publicly. It would be extremely helpful if this behavior (print to channel or gist) was configurable.

**Comment by dgw** [comment]
Also additional options, like outputting to a text or HTML file on the local filesystem instead, would be useful. Maybe I should just bite the bullet and implement all that.

**Comment by dgw** [comment]
As an aside, this issue might be obsolete. See #1254.

**Comment by dgw** [comment]
Switched to a different pastebin provider for the time being. This will stick around as a feature request.

**Comment by Exirel** [comment]
I feel like this has been fixed by #1451

**Comment by dgw** [comment]
@Exirel Nope. We still want to add locally-hosted HTML or something that doesn't touch a pastebin at all.

**Comment by dgw** [comment]
Punting this. The implementation should add an option without changing the existing behavior if not configured, so no rush to get this into the next major version.

**Comment by Exirel** [comment]
The more I think about that one, the more I'd like to create a separated package for the help plugin, and to have a dedicated `[help]` config section. I've plenty of ideas for that kind of plugins, and I think it would help (...) a lot to be able to update such plugin whenever a paste service become unavailable, or when they change their interface, and so on.

For instance, I'd love to allow third-party devs to implement their own help publishing backend, so whenever someone have a new use-case that is solely for them and their group, they could do it more easily.

Also, I'd use it as an excuse to push Sopel's internals to always be better - as one may say "eat your own food".

**Comment by dgw** [comment]
Aren't we already pulling a bunch more stuff out of core for 8.0? `help` can be part of that.

**Comment by Exirel** [comment]
Yes, but I'd love to start with `sopel-help` for Sopel 7.1: it's easy to do, and since almost everyone use it from time to time, if anything goes wrong it won't be silent.

Also, "help" is another name for "documentation". 😛

**Comment by dgw** [comment]
Feel free to play around in the new `sopel-help` repo, @Exirel. Whatever you come up with in there, the only real question is whether it takes effect in 7.1 or 8.0.

**Comment by dgw** [comment]
We'll consider this fixed by [sopel-irc/sopel-help](https://github.com/sopel-irc/sopel-help), which includes several pastebins, adds local HTML output (to be served by the user's chosen external HTTPd), _and_ resurrected direct-to-IRC output as well.

Since the new plugin only supports Python 3.5+, I'll mark this for Sopel 8.0 (which will drop support for older Python versions) and note it prominently in the release notes for that version, then close the issue.
