### ISSUE TITLE
Sopel IRC post delay?

### ISSUE THREAD

**Issue by Jaydee1977** [sopel-irc/sopel#1216]
Hi Guys,

I love the sopel irc bot but there is one thing i cannot find in the documentation so i hope maybe u guys can help me.

I need my bot to say , lets say for example, 10 lines.

Now it says those lines with a certain IRC post delay. Probaply to prevent triggering flood protection. Now my question / issue is that i want to lower the post delay to IRC and I am wondering if it can be done. 

Someone knows ? maybe U guys have a configuration example ? Thanx in advance.

Regards Jay

**Comment by kwaaak** [comment]
https://github.com/sopel-irc/sopel/blob/78ed01f8dd3757ac63dcc27bd92ea042d457bd90/sopel/bot.py#L310

**Comment by Jaydee1977** [comment]
Ok thanx kwaaak ... so if i'm correct i have to alter bot.py and for example lower this:

wait = 0.8 + penalty

to for example

wait = 0.5 + penalty

**Comment by dgw** [comment]
I'm guessing this question has been resolved. If not, feel free to chat away, I'm just closing this to get it off the list of open issues that need solving for 6.5.2 and beyond. :)

**Comment by kwaaak** [comment]
This could be a configurable option instead of a hardcoded value. 0.8 seconds is very conservative.
