### ISSUE TITLE
How to change Sopel's default . for its commands?

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1218]
Hello.

How does one change Sopel's default period (.) to another character to use its commands (e.g., .version and .help)?  I cannot find the answer in my ~/.sopel/default.cfg and online. Maybe I missed it?

Thank you in advance. :)

**Comment by dgw** [comment]
https://github.com/sopel-irc/sopel/wiki/Core-configuration-settings

tl;dr: `core.prefix`: The prefix to add to the beginning of commands. (i.e, the `.` in `.t`) Regular expression syntax is used. Default: `\.`

**Comment by antdude** [comment]
Thank you, dgw! :)
