### ISSUE TITLE
help command should not include the IRC server address.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1219]
Even though help command uploaded its results to https://gist.github.com/ web server anonymously, it should not include the IRC server name. There should be an option to include it. Not all IRC servers are meant to be public.

**Comment by dgw** [comment]
@hekel Would you like to work this in alongside updating the help module to use another pastebin service?

**Comment by dgw** [comment]
Cross-reference: #1459

Assigning **7.0.0** milestone to match.

**Comment by Exirel** [comment]
This might need documentation, but it looks fixed in master.

**Comment by dgw** [comment]
Fixed by new option added in #1459. Thanks for the nudge, @Exirel!
