### ISSUE TITLE
help: output should be sent to requester privately

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1220]
IIRC, the older version of Sopel (or Willie?) used to send the long help results privately to the user who requested the help command list results. Or at least make it optional to admin who wants gisthub or privately.

Thank you in advance. :)

**Comment by dgw** [comment]
Help was indeed sent by PM/query before the conversion to gist.

@hekel Thoughts on including this in your rewrite?

**Comment by RaggyDoo** [comment]
Has this been covered somewhere else since this issue was raised? This was one of those things that annoyed me when I re-built my bot and have been meaning to tackle it.

**Comment by dgw** [comment]
No, nothing has really touched the help module since the pastebin conversion. If you want to implement this, you go right on ahead!

**Comment by dgw** [comment]
This can be part of my Hacktoberfest slate, what the hell. I envision a `ListAttribute` for `output_method` with "channel", "notice", and "query" as possible values.

I guess an option is maybe overkill for this, but it sounds like the sort of thing that different communities of users might want handled differently, maybe to match other bots already on the network/channel.
