### ISSUE TITLE
Sopel v6.5.0's .g command showed strange results.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1224]
...
[01:03pm] <Ant> .version
01:03PM <URL> Ant: Sopel v. 6.5.0
[01:03pm] <Ant> .g test
01:03PM <URL> Ant: /l/?kh=-1&uddg=https%3A%2F%2Fwww.speedtest.net%2F
[01:04pm] <Ant> .help g
01:04PM <URL> Ant: Queries Duck Duck Go for the specified input.
01:04PM <URL> Ant: e.g. .duck privacy or .duck !mcwiki obsidian
...

I was able to reproduce it in my own (Python v3.4.2 (default, Oct  8 2014, 10:45:20)) and my friend's Sopel v6.5.0 (v2.7) bots.

Thank you in advance. :)

**Comment by dgw** [comment]
#1167, #1210

**Comment by antdude** [comment]
dasu: No kidding. I don't want have to fiddle with all these .py files. I just want to download stable Sopel via pip! :(

**Comment by dasu** [comment]
Yup... Also forgot to mention, the definitive fix is actually this: https://github.com/sopel-irc/sopel/pull/1171/commits/12adfa052e0a59970c6e52cb1171044f4d0505bf , editing search.py , the other commits in that merge request is just to fix something slightly related.

**Comment by antdude** [comment]
I assumed v6.5.1 fixed this bug.
