### ISSUE TITLE
Unable to connect with Python >= 3.6

### ISSUE THREAD

**Issue by Glandos** [sopel-irc/sopel#1230]
I'm using Debian/testing. Since the default python 3 is now Python 3.6, my sopel instance is unable to connect to chat.freenode.net:6697 with `use_ssl = true`. It just waits indefinitely after the server CAP response.

Does anyone experience this?

**Comment by kitten77** [comment]
Is there a error log on this?

**Comment by dgw** [comment]
This issue will be closed after the next release if no additional information is provided. We cannot debug this without a log.

**Comment by Glandos** [comment]
Yep, you're right. I've waited for Sopel 6.5.1 to land into Debian/testing. Now, everything seems OK, but I have to admit that since I'm using systemd, the `LC_ALL` was set to `en_US.UTF-8` by the default service unit, and my system didn't have that locale generated. I generated it in the meantime, and a lot of module now loads…

Anyway, this is fixed.
