### ISSUE TITLE
Include changelog in documentation

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1233]
It would be nice to have them somewhere to see what were changed and new betrween versions (e.g., v6.5.0 and v6.5.1).

**Comment by embolalia** [comment]
https://github.com/sopel-irc/sopel/blob/master/NEWS They're not exhaustive but there's always the commit log. Right now I'm more focused on actually getting something out.

**Comment by antdude** [comment]
Thank you! This should be posted somewhere on the web site. :)

**Comment by dgw** [comment]
I won't be giving the documentation too much attention until it actually needs updating, but a changelog on the website (in addition to the NEWS file here and the log displayed on PyPI) is a good idea.

**Comment by Exirel** [comment]
> I won't be giving the documentation too much attention until it actually needs updating

Heh. Good thing you aren't alone anymore. :smile:

**Comment by dgw** [comment]
And this has been a thing for some months now. We have https://sopel.chat/changelog/ entries generated from the NEWS file in each release, as they come out. See sopel-irc/sopel.chat#7.
