### ISSUE TITLE
Chanserv auth_method?

### ISSUE THREAD

**Issue by wgordon17** [sopel-irc/sopel#1237]
Is there an option for the [auth_method](https://sopel.chat/docs/config.html#the-core-configuration-section) that's equivalent to `chanserv`?

**Comment by dgw** [comment]
Doesn't look like it, but what would you expect `chanserv` auth to do?

**Comment by wgordon17** [comment]
It turns out I was confused. The bot needs to be registered and authed with [userserv](https://github.com/sopel-irc/sopel/pull/1238) to allow chanserv to auto-op it. These services are managed by https://services.ratbox.org

**Comment by dgw** [comment]
UserServ auth is coming in #1217, at which point will this issue be resolved @wgordon17?

**Comment by dgw** [comment]
Whoa, there, it's not merged yet (and won't be until after 6.5.2 releases). Let's keep this issue open for visibility until the code actually lands.
