### ISSUE TITLE
FreeBSD [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

### ISSUE THREAD

**Issue by kitten77** [sopel-irc/sopel#1246]
sopel/config/core_section.py
#  python3.6 [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
```
from sys import platform

if 'freebsd' in platform:
    certs = '/etc/ssl/cert.pem'

def _find_certs():
    certs = '/etc/pki/tls/cert.pem'
    if not os.path.isfile(certs):
        certs = '/etc/ssl/certs/ca-certificates.crt'
        if not os.path.isfile(certs):
            return None
    return certs

```
Seems like there is missing a good validation on what platform it is running on and where the certs are stored.

**Comment by diveyez** [comment]
Still got this issue
Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

**Comment by diveyez** [comment]
That is with a certbot letsencrypt certificate

**Comment by kitten77** [comment]
the path for letsencrypt certificates need to be set, on freebsd the certificates are
/usr/local/etc/letsencrypt/live/domain/fullchain.pem

**Comment by dgw** [comment]
@kitten77 If #1249 gets merged, should that resolve (close) this issue?

@diveyez Can you also try with the changes from #1249 and see if you still have the issue?

**Comment by kitten77** [comment]
Connection error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) 
seems to point to the cert file not found error.
@diveyez if he is using a different certificate than the standard os openssl he will need to add that part to the list inside #1249 before he tries to connect. I would recommend pushing the fix cause it is a cleaner way to fix this issue, and there should be a error handler placed on this pointing to the list for easy find and fixing these issues on a later point

**Comment by alanhuang122** [comment]
@kitten77 That's not correct, unless you're assuming the server in question is serving an incomplete chain. In order for a Let's Encrypt certificate to be verified, a certificate bundle with DST Root CA X3 in it needs to be trusted, and the Let's Encrypt Authority X3 certificate needs to be presented by the server.

You cannot use `fullchain.pem` on the client side to accomplish anything, unless you explicitly add Let's Encrypt Authority X3 to a trust store, which you really shouldn't be doing.

**Comment by kitten77** [comment]
@alanhuang122 for me it makes no sense using a let's encrypt ceritifcate on the client side. changed my answer to cert.pem, thank you for pointing out my error
