### ISSUE TITLE
[unicode_info] Emoji lookup doesn't work on Python 2.7

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1276]
With Python 2 (tested in 2.7.13 interactive console), `len("👌")` is 2, so the `unicode_info` module incorrectly tries to look up the emoji as a numerical codepoint (which returns no result, of course, because it isn't a number).

Under Python 3 (tested in 3.6.2 interactive console), `len("👌")` is 1, so the lookup is done on the character.

For the time being, both py2 and py3 are officially supported, and having functionality differ between the two versions is less than ideal. There's probably a workaround for this, and if someone else finds it before I get around to doing so, then by all means send a pull request. (Please include an example using emoji, as well, so it will be tested in CI and any regressions will be caught in the future.)

**Comment by kwaaak** [comment]
https://stackoverflow.com/a/31280521 (not worth doing)

**Comment by alanhuang122** [comment]
And in fact, a0c567c running on  can process that specific character just fine, even though `len('𠤪')` is `4`. (`len(u'𠤪')`, however, is `1`.)
```
[00:59:29] <~Alan> !u 𠤪
[00:59:32] <hotbot-upstream> U+2092A CJK UNIFIED IDEOGRAPH-2092A (𠤪)
```
I think this might be an invalid issue.

**Comment by dgw** [comment]
Hmm, I think you might be right, @alanhuang122.

So, this does look like a difference between Python versions. I'd be happy to rewrite the module using an up-to-date lookup (installed from PyPI, maybe), but couldn't find anything that would actually fit that bill. We'll probably just have to accept that running Sopel on older Python can never achieve 100% parity with running on Python 3.
