### ISSUE TITLE
Increase nick length for .tell

### ISSUE THREAD

**Issue by dasu** [sopel-irc/sopel#1304]
Currently .tell has a limit on the tellee's nick length (20 characters), there are servers that accept longer nick lengths (rizon, 30, and that seems to be the largest I've seen so far).  Can we bump nick length for the module up to 30?  I don't believe any other module has this restriction.

**Comment by dgw** [comment]
I don't see why not. I'll commit that shortly for 6.5.3.

In a future version of Sopel I would like to have a module-accessible property that provides the server's maximum nick length. That's a separate issue though, for a future Sopel version.
