### ISSUE TITLE
.help command fails

### ISSUE THREAD

**Issue by ralienpp** [sopel-irc/sopel#1309]
Sending `.help` to the bot results in `ERROR:sopel.modules.help:Invalid result {u'documentation_url': u'https://developer.github.com/v3/gists/#create-a-gist', u'message': u'Requires authentication'}
`, this is shown on stdout of v6.5.1.

**Comment by dgw** [comment]
Fixed in 6.5.2, see #1254. (Sopel 6.5.1 is essentially over a year old; it contains very few changes from 6.5.0.)
