### ISSUE TITLE
A general way to truncate messages and stay within the maximum length

### ISSUE THREAD

**Issue by kwaaak** [sopel-irc/sopel#1328]
After being rightfully scolded by @dgw for hijacking another issue, I am opening a separate one.

It would be nice to have a tool that automatically cuts off the bot responses which are going to be too long, adds a "[…]" at the end, and continues in private message or adds a web link.

There are a few modules which use their own logic to accomplish this.

**Comment by dgw** [comment]
The bot needs to know the length of its hostmask to do this, so this should be implemented with #1322.
