### ISSUE TITLE
.title command should say an error if no title is found

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1340]
Example: http://zimage.com/~ant/temp/notitle.html

Sopel should say there was no web page title found.

**Comment by dgw** [comment]
That page does have a title…

````HTML
<head>
<title>Error 404</title>
</head>
````

I'm not sure there's a whole lot of benefit to spitting out anything if a link has no title. That would also mean spitting out "No title found" (or whatever the message would say) for links that never have titles, like images, video, PDFs, etc.

Granted, Sopel could output the error only if the link actually returns `text/html` or related MIME-type. But mostly, I think the `url` module should simply say nothing if it can't say something useful.

But I won't close this immediately, for visibility. Tagging for 6.6.0, and a final decision will be made closer to release of that version based on any further comments made between now and then.

**Comment by antdude** [comment]
dgw: Sorry, I had to change the original link. I replaced it with http://zimage.com/~ant/temp/notitle.html as an example.

**Comment by dgw** [comment]
Why not both? :)

Either way, I still don't think `url` should say anything unless it's functionally useful. Arguably (and this is where feedback from other users comes in), "No title found" is not functionally useful and could be considered just channel noise.

**Comment by kwaaak** [comment]
Makes sense if you use the ".title" command but not for links that appear by themselves or as a part of a message in the channel.

**Comment by dgw** [comment]
OK, I'm going to update the issue title because I agree with @kwaaak. `.title` should return an error of some kind if there is no title found, but URLs just fetched from chat shouldn't output anything in that case.

Patches welcome, adding to 6.6.0 release target.
