### ISSUE TITLE
Plugin API: Allow declaring output prefix

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1352]
This has come up enough times in just my own work on modules (most recently sopel-wolfram & sopel-github) that I think it's time to open a proper issue.

I think it would be useful for Sopel's module API to support declaring an output prefix, such that any calls to `bot.say()` or `bot.reply()` automatically get prefixed with the module's choice of string. (`bot.msg()` and other lower-level calls, maybe not. I'm still thinking about that.)

Why? It would eliminate having to hard-code, for example, `[GitHub]` (see sopel-irc/sopel-github#9) or `[W|A]` all over the place. The prefix string would be defined only once.

Modules can, of course, roll their own version of this. But just like with #1346 (proposing the addition of `web.unquote()` to mirror `web.quote()`), there are some things that happen often enough across modules to warrant inclusion in Sopel's library. I think prefixing the output is one of those things.

Obviously the idea that this API functionality should exist is the easy part. The hard part is figuring out how it should work, but there's plenty of time between now and when Sopel 6.6.0 drops to think, plus all the time between then and Sopel 7 (when I'd like to actually release this) to iterate on it.

Considerations I've thought of so far:

  * Should square brackets be added automatically, for consistency, or should modules be allowed to define the entire prefix string? Including the trailing space between it and the rest of the message?
  * If prefixes get bracket-wrapped automatically, should there be an override mechanism?
  * Where should this be set up? The module `setup()` function is a logical place, I guess, though it would mean setting the prefix would need to be a function of the `bot` object. Hmm…

(As I said, the idea is the easy part!)

**Comment by Exirel** [comment]
This feature requires the bot to know, when it triggers a rule or a command callable, which output prefix should be used for this callable.

And then, you need to be able to activate/deactivate it for a given plugin and/or callable, to take it into account when building your message (because of the limited length you have).

I'd suggest a decorator, that could be used on a per-callable basis, like that:

``` python
from sopel import module

@module.command('echo')
@module.output_prefix('[e]')
def echo_message(bot, trigger):
    bot.say('echo')
    bot.say('ech')
    bot.say('ec')
    bot.say('e')
```

The output would be:

```
<Exirel> .echo
<Sopel> [e] echo
<Sopel> [e] ech
<Sopel> [e] ec
<Sopel> [e] e
```

**Comment by dgw** [comment]
I don't think the decorator should assume a space after the prefix, but other than that, 👍.
