### ISSUE TITLE
A more precise function for the bot to send messages

### ISSUE THREAD

**Issue by deathbybandaid** [sopel-irc/sopel#1357]
I had difficulty remembering the order of things for `bot.msg(target, message)` versus `bot.notice(message, target)`

I also needed the ability to store a `['list','of','things']` for the bot to say.

I also needed a way for the bot to fit as much onto a single line, and then say it on multiple lines instead of cutting it off. This also makes sure a string doesn't exceed a certain length.

I also needed a way to privately message multiple people the same content.

I also wanted a way to precede some notices with `usernick + ", " + message`

I proceeded to develop a function to manage bot.say bot.action bot.msg and bot.notice :

````
osd_limit = 420  # Amount of text allowed to display per line

def osd(bot, target_array, text_type, text_array):

    # if text_array is a string, make it an array
    textarraycomplete = []
    if not isinstance(text_array, list):
        textarraycomplete.append(str(text_array))
    else:
        for x in text_array:
            textarraycomplete.append(str(x))

    # if target_array is a string, make it an array
    texttargetarray = []
    if not isinstance(target_array, list):
        if not str(target_array).startswith("#"):
            target_array = nick_actual(bot,str(target_array))
        texttargetarray.append(target_array)
    else:
        for target in target_array:
            if not str(target).startswith("#"):
                target = nick_actual(bot,str(target))
            texttargetarray.append(target)

    # Make sure we don't cross over IRC limits
    for target in texttargetarray:
        temptextarray = []
        if text_type == 'notice':
            temptextarray.append(target + ", ")
        for part in textarraycomplete:
            temptextarray.append(part)

        # Make sure no individual string ins longer than it needs to be
        currentstring = ''
        texttargetarray = []
        for textstring in temptextarray:
            if len(textstring) > osd_limit:
                chunks = textstring.split()
                for chunk in chunks:
                    if currentstring == '':
                        currentstring = chunk
                    else:
                        tempstring = str(currentstring + " " + chunk)
                        if len(tempstring) <= osd_limit:
                            currentstring = tempstring
                        else:
                            texttargetarray.append(currentstring)
                            currentstring = chunk
                if currentstring != '':
                    texttargetarray.append(currentstring)
            else:
                texttargetarray.append(textstring)

        # Split text to display nicely
        combinedtextarray = []
        currentstring = ''
        for textstring in texttargetarray:
            if currentstring == '':
                currentstring = textstring
            elif len(textstring) > osd_limit:
                if currentstring != '':
                    combinedtextarray.append(currentstring)
                    currentstring = ''
                combinedtextarray.append(textstring)
            else:
                tempstring = str(currentstring + "   " + textstring)
                if len(tempstring) <= osd_limit:
                    currentstring = tempstring
                else:
                    combinedtextarray.append(currentstring)
                    currentstring = textstring
        if currentstring != '':
            combinedtextarray.append(currentstring)

        # display
        textparts = len(combinedtextarray)
        textpartsleft = textparts
        for combinedline in combinedtextarray:
            if text_type == 'action' and textparts == textpartsleft:
                bot.action(combinedline,target)
            elif str(target).startswith("#"):
                bot.msg(target, combinedline)
            elif text_type == 'notice' or text_type == 'priv':
                bot.notice(combinedline, target)
            elif text_type == 'say':
                bot.say(combinedline)
            else:
                bot.say(combinedline)
            textpartsleft = textpartsleft - 1

````

To break down what it does, `osd(bot, target_array, text_type, text_array)`:

target_array can either be passed as `trigger.nick`,`[trigger.nick]`,'[trigger.nick,playerb,playerc]` or `[#channel,#channelb]`

text_type can equal 'say', 'action', 'notice', or 'priv'

The difference between priv and notice, is the `usernick + ", " + message`

text_array can be passed as a normal string or it can contain a list containing messages to display.

There is likely a cleaner way to code this, but something like this built in to the bot would be pretty cool.

**Comment by dgw** [comment]
> I had difficulty remembering the order of things for `bot.msg(target, message)` versus `bot.notice(message, target)`

`bot.msg()` is [long deprecated](https://github.com/sopel-irc/sopel/commit/1217c40a7549660b26deb9a6858a90f7f11172b6#diff-5ca66e1c69a6af630a3309cc3385d2d8R388). Use `bot.say()` instead, and all the parameter orders will match. (Internally, `bot.msg()` literally just calls `bot.say()` with the arguments rearranged.)

Honestly, most of this doesn't sound especially difficult to do with loops and/or `','.join()` calls on the module side. You can already send to multiple targets (up to 4? I think, on most networks) by using comma-separated list of targets (like `nick1,nick2,#channel,#nick3`) as the `target` for `bot.say()`, `bot.notice()`, etc. There are reasonably simple ways to break a list of targets into chunks, e.g. https://stackoverflow.com/a/434411/5991. Doing the looping inside the module that needs it is more efficient than making core always set up a loop even when most calls will only need one iteration.

See [the `max_message` parameter to `bot.say()`](https://sopel.chat/docs/bot.html#sopel.bot.Sopel.say), which will probably work well enough until #1322 makes it possible to extract every possible byte.

At this time, I don't think any of this is likely to be implemented in core, so I will close this. If future discussion changes that outlook, the issue can be reopened then. :smile_cat:
