### ISSUE TITLE
How to make sopel autorun on raspberry pi?

### ISSUE THREAD

**Issue by Hoiro91** [sopel-irc/sopel#1396]
Could someone please explain how i can create a user for sopel and have sopel start (using that user) when raspberry pi boots?
Ive tried to see if there already exists a tutorial for this, but i was not able to find one.

Thanks!

**Comment by Hanicef** [comment]
A feature like this is not built into Sopel, but you can achieve this with systemd.
My unit file for systemd (named `sopel.service`, placed in `/etc/systemd/system`) looks like this:
```
[Unit]
Description=Sopel IRC bot
Documentation=https://sopel.chat/
After=network.target

[Service]
Type=forking
User=sopel
Group=sopel
PIDFile=/home/sopel/.sopel/sopel-default.pid
ExecStart=/usr/bin/python3 /home/sopel/sopel/sopel.py -d -c /home/sopel/.sopel/default.cfg
ExecStop=/usr/bin/python3 /home/sopel/sopel/sopel.py -q -c /home/sopel/.sopel/default.cfg
TimeoutStopSec=10
Restart=on-failure
RestartSec=3
```

This unit is not configured for autostart on boot, but by changing some things, you can make it so. But there is also another example in `contrib/sopel.service` in the project tree (https://github.com/sopel-irc/sopel/blob/master/contrib/sopel.service) which is configured for autostart.

You can find more info about unit files in systemd here: https://wiki.archlinux.org/index.php/Systemd#Writing_unit_files

**Comment by dgw** [comment]
Closing: inactive.
