### ISSUE TITLE
Remove Rate Limit

### ISSUE THREAD

**Issue by jeffreyroberts** [sopel-irc/sopel#1407]
I have read a few issues here about rate limiting, some say fork, some say add @rate(600) some say return sopel.module.NOLIMIT

however, I can not get any of those solutions to work yet, I haven't forked yet, but thats what is next if need be

     @sopel.module.commands('ohelp')
     def ohelp(bot, trigger):
         rate = 600
         bot.say('  _          _')
         bot.say(' | |__   ___| |_ __')
         bot.say(' | \'_ \\ / _ \\ | \'_ \\')
         bot.say(' | | | |  __/ | |_) |')
         bot.say(' |_| |_|\___|_| .__/')
         bot.say('              |_|')
         return sopel.module.NOLIMIT

Any ideas on how I can prevent the rate limit?

**Comment by dgw** [comment]
In this case, by "rate limiting", I assume you refer to the flood protection mechanism.

The `@sopel.module.rate()` decorator and `sopel.module.NOLIMIT` return value affect command rate-limiting—how often a given user can trigger a specific bot command/function. They do not affect the flood-protection, which is designed to keep Sopel from being kicked off networks for posting lines too fast.

At present, flood protection is not configurable (#1342).
