### ISSUE TITLE
Sopel dies after being disconnect instead of reconnecting

### ISSUE THREAD

**Issue by traumschule** [sopel-irc/sopel#1449]
The IRC server went off and sopel as well:
```
Connecting to $address:6667...
1547102674 ERROR torsocks[22917]: Connection timed out (in socks5_recv_connect_reply() at socks5.c:547)
Connection error: [Errno 110] Connection timed out
Calling shutdown for 1 modules.
calling instagram.shutdown
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...
Traceback (most recent call last):
  File "/home/user/sopel/sopel/__init__.py", line 76, in run
    p = bot.Sopel(config, daemon=daemon)
  File "/home/user/sopel/sopel/bot.py", line 134, in __init__
    self.scheduler.start()
  File "/usr/lib64/python3.6/threading.py", line 846, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```
Could this be related to modules?

**Comment by HumorBaby** [comment]
Something is spawing a bunch of threads and sople is hitting the per process thread limit. Is you sopel modified in any way?

**Comment by Exirel** [comment]
Quick note: can we change the issue's title? I just got a heart attack by reading it! :wink:

**Comment by traumschule** [comment]
valid point, i had hit enter too early before ;)

i am running with a the patch proposed in above issue. could this be relevant?

**Comment by traumschule** [comment]
yes, nothing else. is there a way to debug sopel's threads apart from gdb. it ran over several weeks.

**Comment by dgw** [comment]
pdb, maybe?

The error you posted says it can't create a thread, though, which is almost certainly caused by something outside of Sopel's own code. A system limitation or something. How busy is this system? Presumably Sopel isn't the only program it runs.

**Comment by dgw** [comment]
Two months without additional information, or any further reports of this happening.

@traumschule I'm going to close this, but do reopen if it happens again (hopefully you'll have more details).
