### ISSUE TITLE
Config filename is mis-parsed when running configuration wizard from command line

### ISSUE THREAD

**Issue by HumorBaby** [sopel-irc/sopel#1463]
~~`-w` / `--configure-all` and~~ `--configure-modules` does not drop the file extension `.cfg` from the specified file when searching for a config file to use (unlike just launching the bot, where as the extension does seem to be dropped, or at least accounted for when finding the config file).

A user stopped into #sopel (2019-01-29, ~14:15 UTC-5) who had a `default.cfg` and `custom_config.cfg`. They primarily used `custom_config.cfg` and when attempting to configure modules for said `custom_config.cfg`, the used the command `sopel -c custom_config.cfg --configure-modules`. Sopel could not find `custom_config.cfg.cfg`, and without error/warning, edited `default.cfg`. Launching the bot with `sopel -c custom_config.cfg` still used the correct file though, so any changes made with the configuration wizard were never propogated to the config file that was actually being loaded.

**EDIT**: the `--configure-all` flag will just make a new config file like `custom_config.cfg.cfg`

**Comment by dgw** [comment]
GitHub doesn't understand maintenance branches or something… Have to close this manually, I guess.
