### ISSUE TITLE
NAMESX support & better privilege tracking

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1496]
As a follow-up to #1482, I think it would be beneficial for Sopel to detect NAMESX support on the server, and activate it if available.

Servers with WHOX and NAMESX available would be ideal, but we should also update privilege tracking at the same time to make sure it does not remove mask bits added by (for example) a NAMES reply if a later WHO response includes only the highest mode prefix. Right now, if only one of WHO and NAMES includes multiple mode prefixes, it opens up Sopel to race conditions that result in different stored privilege information depending on the order in which replies were received and processed.

We should probably start parsing the 005 `RPL_ISUPPORT` numeric (see #1082), which would give us access to the server flags for NAMESX, WHOX, NICKLEN (see #1305), and a bunch of other useful stuff. For example, I found that irc-framework [handles NAMESX](https://github.com/kiwiirc/irc-framework/blob/1ba628acc6589fa9d0c23405fbbbb240c9f68e55/src/commands/handlers/registration.js#L70-L74) in a pretty nice way.

`coretasks` currently decides whether WHOX is available based on a set of enabled capabilities. This is OK, and it probably works—but enabling features based on ISUPPORT flags would be an ideal addition.

Tagging as high-priority and targeting for Sopel 7 because I think getting privilege-tracking correct is a really foundational piece of how well Sopel functions.

**Comment by dgw** [comment]
I think this is mitigated Enough™ by periodic WHO updates (see #1664) that we can leave it for 7.1.

**Comment by dgw** [comment]
ISUPPORT parameters are now available thanks to #1758. That was the minimum requirement for starting on this, so we're set for beginning early 7.1.

**Comment by Exirel** [comment]
So, I've read a bit about `NAMESX`, and it appears that it has been [deprecated for IRCv3](https://defs.ircdocs.horse/defs/isupport.html), and we should use the [`multi-prefix`](https://ircv3.net/specs/extensions/multi-prefix-3.1.html) capability instead.

For that to work, as I understand it:

1. request `multi-prefix` when available
2. make sure to store all privileges for a user instead of the higher one only
3. make sure to parse properly `RPL_NAMREPLY` event with more than one privilege

For `WHOX`, I haven't think about it yet.

**Comment by dgw** [comment]
Sopel has requested `multi-prefix` support for about 5 years already. In fact, all three of those points should already work, as the `RPL_NAMREPLY` handler checks for all privilege prefixes (from the hard-coded list currently in use) and ORs them together, then stores the whole thing when adding the `User` to that `Channel` object: https://github.com/sopel-irc/sopel/blob/a97fb649edda8c593fceb54357cd0dd96600be99/sopel/coretasks.py#L338-L353

Just because `NAMESX` is deprecated doesn't mean Sopel won't encounter servers that still use it. That very same defs page you linked says "gray for deprecated (however quite possibly _still in use_)" [emphasis added]. And there's no real reason not to support it: Parsing a `RPL_NAMREPLY` works the same whether the server sends basic, `NAMESX`, or `multi-prefix` messages to the bot. After capability negotiation, if the server did not `CAP Sopel ACK :multi-prefix` but the `NAMESX` value was sent in `RPL_ISUPPORT`, Sopel can just send `PROTOCTL NAMESX` and change nothing else.

`WHOX` might complicate things a bit more, we'll see. I'm in no position to start that research tonight, but wanted to make sure you don't go too far down the `NAMESX`/`multi-prefix` rabbit hole during the USA's night. 😸

**Comment by Exirel** [comment]
> if the server did not `CAP Sopel ACK :multi-prefix` but the `NAMESX` value was sent in `RPL_ISUPPORT`, Sopel can just send `PROTOCTL NAMESX` and change nothing else.
> 
> `WHOX` might complicate things a bit more, we'll see. I'm in no position to start that research tonight, but wanted to make sure you don't go too far down the `NAMESX`/`multi-prefix` rabbit hole during the USA's night. 😸

That's actually great! I didn't look into the code because I wanted your opinion first, and I'm glad I did - and even more that you answered with so much details. Anyway, here is some more ❤️ for you.

What I suggest now is to do as you said (send `PROTOCTL NAMESX` and change nothing else), and maybe split this issue in two? One for NAMESX, another one for `WHOX`?

**Comment by dgw** [comment]
So I misspoke a bit last night:

> After capability negotiation, if the server did not `CAP Sopel ACK :multi-prefix` but the `NAMESX` value was sent in `RPL_ISUPPORT`, Sopel can just send `PROTOCTL NAMESX` and change nothing else.

This isn't entirely accurate, since CAP negotiation happens before 001 `RPL_WELCOME` and therefore (more importantly) before 005 `RPL_ISUPPORT`. The server can send 005 multiple times, but there is no indicator that it's finished (no `RPL_ENDOFISUPPORT` numeric) nor a multiline continuation flag (like `CAP LS *` in CAP 302).

The best idea I can think of for enabling `NAMESX` involves putting an extra helper function call below [here](https://github.com/sopel-irc/sopel/blob/a97fb649edda8c593fceb54357cd0dd96600be99/sopel/coretasks.py#L249), and having that helper function do something like this:

```python
def _maybe_enable_namesx(bot):
    if bot.protoctl_namesx_sent:
        return

    if 'NAMESX' in bot.isupport:
        bot.write('PROTOCTL', 'NAMESX')
        bot.protoctl_namesx_sent = True
```

Couldn't think of a way to avoid needing to store that flag on the bot. It would be simple if there was an event guaranteed to signal the end of ISUPPORT, and the helper could just trigger on `@plugin.event('THAT_NUMERIC')` _once_, but the IRC protocol isn't that nice to us in this case. 😅

> and maybe split this issue in two? One for `NAMESX`, another one for `WHOX`?

Rather just make it a tracking issue and add a task list to the OP. Probably should do that anyway, since I don't think all of this is going to be done for 7.1.

**Comment by dgw** [comment]
So I _think_ this is already done, at least for 7.1. Both NAMESX and WHOX are handled when appropriate, and `multi-prefix` used if available. Early in 8.0, after cleaning up deprecated stuff, we can revisit this and run some serious stress tests to find edge cases.

**Comment by dgw** [comment]
Here we are near the end of 8.0 development, having never found any edge cases (but also having never technically run any stress tests). Still, I feel comfortable dropping this back into the 7.1 milestone and considering it as fixed then. Any bugs that come up, we will handle in (a) new ticket(s).
