### ISSUE TITLE
Enhancement: Configuring individual modules only?

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1519]
There should be a way to only configure individual modules only.

Thank you in advance. :)

**Comment by Exirel** [comment]
Yeah, once #1507 is merged I'll work on adding that. :)

(*wink wink* @dgw *wink wink*)

**Comment by Exirel** [comment]
So, I changed so many things in #1479 that now I also need this one to continue working on that... Good thing it's the last round of review!

**Comment by Exirel** [comment]
I think I'll update #1588 to include something like this:

    $ sopel-plugins configure <name>

It's fairly easy to do now that I've a proper wizard function, and a reliable way to know if a plugin has custom configuration or not.
