### ISSUE TITLE
Store real IRC server name

### ISSUE THREAD

**Issue by deathbybandaid** [sopel-irc/sopel#1532]
I think it is prudent to have a concise location of all things server related.

Servername would be nice to have. If a bot is connected to a bouncer like ZNC, reading the value in the config file isn't super helpful.

**Comment by dgw** [comment]
Is it more useful to have the server's hostname (like `asimov.freenode.net`) or the network name (meaning `freenode`)?

Both? It couldn't hurt to store both, I guess.

**Comment by deathbybandaid** [comment]
both would be super handy

**Comment by dgw** [comment]
OK, both. That didn't take much convincing.

You proposed `bot.server` to hold this stuff on IRC. Running with that, `bot.server.network` and `bot.server.hostname`?

**Comment by deathbybandaid** [comment]
I like it,,, might also be a cleaner place to store `bot.server.capabilities` than `bot.server_capabilites`

**Comment by dgw** [comment]
Could also make sense to use `bot.network`, but we can bikeshed the names later lol.
