### ISSUE TITLE
bot.hostmask

### ISSUE THREAD

**Issue by deathbybandaid** [sopel-irc/sopel#1533]
While bot.users.get(bot.nick).hostmask is nice to use, I think it would be slightly better to have a more direct approach like bot.hostmask .

**Comment by dgw** [comment]
Doesn't this duplicate #1322?

**Comment by dgw** [comment]
I mean, OK, I get where you're going with this (not wanting to lose this in the intent of that other ticket, which is to allow using the full line length).

Would be pretty easy to do just by making the "attribute" `bot.hostmask` a getter (via decorator, already used in other places) for `bot.users.get(bot.nick).hostmask`.
