### ISSUE TITLE
cli: legacy argument before subcommand breaks parser

### ISSUE THREAD

**Issue by HumorBaby** [sopel-irc/sopel#1584]
The current usage specifies: 
```
usage: sopel.py [options]                                                      
                                                                               
Sopel IRC Bot                                                                  
                                                                               
optional arguments:                                                            
 ...              
  -c filename, --config filename                                               
                        Use a specific configuration file                      

sub-commands:                                           
  List of Sopel's sub-commands                          
                                                        
  {start,configure,stop,restart}                        
    start               Start a Sopel instance          
    configure           Sopel's Wizard tool             
    stop                Stop a running Sopel instance   
    restart             Restart a running Sopel instance
```

If a user provides an option, then also specifies a subcommand (e.g., `sopel -c my_config.cfg start`), the parser may get confused and give an error like: <pre>error: unrecognized arguments: <i>name_of_subcommand</i></pre>

@Exirel pointed out on IRC that:
```
> it is due to Python 2's argparse. 
> to be more accurate: it's because of how argparse's subparsers in Python 2 are always required
> and they are not in Python 3
> so if you want (almost) the same behavior in both, you need to always provide a sub-parser action
> which you do only if someone provides an option first
```

Essentially, this "bug" (not-a-bug)™<sup> @dgw</sup>, is only due to legacy support that is being provided until (no later than) Sopel v8.0.0, at which point Sopel will stop supporting Python 2. 
> _Then, all of our problems will be solved_ :tada:
> --  _someone (probably...)_

**Comment by Exirel** [comment]
Working on that:

![image](https://user-images.githubusercontent.com/3259552/123512078-b627fb00-d685-11eb-99f6-04353fb206a2.png)

* legacy mode is gone
* a subcommand is now always required
* having a "default" command doesn't really work the way I wanted to, so there will be breaking changes
* the doc looks so much better now!

![image](https://user-images.githubusercontent.com/3259552/123512195-5bdb6a00-d686-11eb-896a-ad4fd1eec2cd.png)

**Comment by dgw** [comment]
Doc for `--config` should split up the default value to be clearer, whoops. The config dir (not homedir) and the config name are separate things; the default isn't `-c ~/.sopel/default.cfg`, but `--config-dir ~/.sopel -c default`.
