### ISSUE TITLE
clock: Invalid timezone name silently uses default

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1591]
This is kind of a bug in `tools.time.get_timezone()`, maybe, but it manifests like this:

```
<dgw>   !time this/doesnt_exist
<Pandy> Thursday, May 09, 2019 04:15:47 (EDT)
```

That's Sopel using the `core.default_timezone` set for the whole bot, silently, even though it was passed a timezone name. It should throw the error message that's defined for timezone names that can't be found by any means of lookup (whether nickname, channel name, or tzdata lookup):

https://github.com/sopel-irc/sopel/blob/eeb48f947f0421b70bcf4e472df1acfd5e8363c4/sopel/modules/clock.py#L65

Instead of a useful error, the calling user gets a misleading false-positive response.

**Comment by Exirel** [comment]
Oh, I used `sopel.tools.time.get_timezone()` recently, and if I find its behavior a bit odd, I can see why it is like that.

Looking at the `clock` built-in plugin, I think we can change that command to be more strict, and rely on `get_timezone` if and only if one isn't provided by the trigger.

**Comment by Exirel** [comment]
In #1592 I worked on the "what if the timezone is incorrect?" to raise an error, but I kept a lot of the initial behavior when it detects a user or a channel.

So I think the core issue is fixed, but as @dgw pointed out, we still use a default timezone if either the nick-based or channel-based timezone is not defined.

So, new issue? Or just a check-list at 50% completion?
