### ISSUE TITLE
Let config settings declare themselves private/protected

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1600]
There are a lot of things stored in Sopel's config object.

Some of them are passwords or other sensitive strings (OAuth secrets, sensitive API keys) that should be kept out of IRC logs "just in case", and not shown in full even to the bot's owner.

Others are access-control devices—the `core.owner` setting and its friends come to mind. These settings are OK to read, but should not be changeable at runtime.

This issue is a good place to start designing how this kind of thing will work at the API level. I'll work on fleshing out some ideas I have on the subject before sharing them in full, but others should feel free to chime in at any time!

Related: #1571, #1587, #1599; probably others

**Comment by dgw** [comment]
Spent far longer writing up another (new) issue and left myself much less time for this than I expected… but here's a brief summary of my ideas so far to get the wheels turning in other people's heads (maybe).

Our `BaseValidated` type is probably a good place to put this, so all setting types will inherit it. Some subtypes might want to override some of the logic (i.e. return the list without obscuring the number of values, but censor each item, in a `ListAttribute`).

We'll want at least two new optional constructor kwargs, tentatively named `secret` (don't allow reading the value) and `protected` (don't allow writing/modifying the value at runtime).

A third potential kwarg named `mask`/`censor`/some better idea, with a string to output instead of the setting value if it is `secret` and something tries to read it anyway.

**Comment by Exirel** [comment]
I like the `secret` kwargs. This could be set to "True" by default on a `SecretAttribute` (subclass of `ValidatedAttribute` maybe?).

```
class MyConfigSection(StaticSection):
    password = ValidatedAttribute('secret_password', secret=True)
    key = SecretAttribute('secret_key')
```

I'd also suggest to add a new method to this: `get_secret` (or `get_secret_value`), that would return the real value. This way, it would be explicit that this value is a secret and should not be displayed lightly. Then, such secret field would return a censored version on direct access.

Something like this:

```
# output "*******"
print(config.my_section.secret_password)
print(config.my_section.secret_key)
# output "S3CR37"
print(config.my_section.get_secret('secret_password'))
print(config.my_section.get_secret('secret_key'))
```

**Comment by dgw** [comment]
A new `SecretAttribute` type isn't a bad idea! At that point, though, we might drop the `secret` kwarg from the base type and override the getter in the subclass instead… which ties into my next thought.

I'm not sold on the mechanism of having a `get_secret()` method, since it would still allow reading the "secret" value from outside the plugin that defined it. Ideally, _only_ the plugin that defined the secret setting should be able to read its value. Everyone else should get back junk.

That said, I haven't done any research into the technical details of how to make that work yet. Since a `StaticSection` must be defined in a plugin's `setup()` function before use, I guess it's at least possible to keep track of which plugin registered a section. Theoretically, that's half the battle… but that's as much as I've thought through at present. (There's a reason this is targeted at Sopel 8—it's a non-trivial feature to design, and we want to get it right the first time!)

**Comment by Exirel** [comment]
Half of this will be done in #1879 but we still need to discuss/agree on the other half, which is:

> what to do exactly when a piece of code wants to do "print(secret)"?

**Comment by dgw** [comment]
Honestly, I don't think there is any reasonable solution to `print(secretvalue)`. We have the `SecretAttribute` type now. I think it would add far too much complexity to the `Config` and/or related types if we start trying to restrict what code can read them, especially as there's no guarantee of alignment between section names and plugin/module names.
