### ISSUE TITLE
Allow the disabling of repetition detection

### ISSUE THREAD

**Issue by predakanga** [sopel-irc/sopel#1618]
It would be useful for bot owners to be able to disable the repetition detection feature ("...").

We use Sopel primarily for devops and moderation, with modules which will often return repetitive answers (i.e. checking IPs or e-mails against blocklists), and thus far have had to fork Sopel to remove the "..." responses.

Other rate limits throughout Sopel are configurable (for instance, `@rate`); it would make sense to bring this in line with them, be it through a config option or a per-callable option to disable the feature.

Additionally, this would be very helpful for debugging modules.

**Comment by deathbybandaid** [comment]
This is something I've been doing for the past few weeks with my dev bot. This would be a good addition to the new flood controls in #1518 ,,, `config.core.message_loop_detection` (Name TBD) seems like a good idea to me.

I do agree heavily with #1559 that the current state of the bot does NOT uniformly rate limit, and that these flood tweaks should filter through `irc.bot.write` and not Sopel.say.

I think #1518 and this should be added, but moreso in the form that @HumorBaby proposes in #1559 .

**Comment by dgw** [comment]
This is a "nice to have" that we can work on for 7.1. It won't add anything backward-incompatible, and so we don't need to find time to build and ship it in 7.0.

**Comment by predakanga** [comment]
Just checking in on this - now that the custom flood protection patches have landed, I'd be happy to submit a PR for this (if welcome).

Would "repetition_filter" be an acceptable name for such a setting?

**Comment by dgw** [comment]
For a simple toggle, I'd name it something like `limit_repetition`. But if you're feeling ambitious _and_ you think more knobs might be useful to override the hard-coded limits [here](https://github.com/sopel-irc/sopel/blob/005a53452fdd96dde1dd266b1587d67170665317/sopel/irc/__init__.py#L625-L631), have at that. (I won't even _start_ bikeshedding names for such settings unless you actually want to go that way, though! 😁)

**Comment by Exirel** [comment]
@predakanga @deathbybandaid you can check the PR #2320 if you want. The code is pretty straightforward.
