### ISSUE TITLE
url: private-resolution inconsistencies

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1622]
- [x] Resolved hostnames are checked only for `is_private`, not `is_loopback` (bare IPs in URLs are checked for both)
- [x] No docstrings for settings added in #1439
- [x] No "magic" documentation about newly added settings in `configure()` docstring for website (it's just a Markdown table, pretty easy to fill in based on what's already there)
- [x] Also, [this typo](https://github.com/sopel-irc/sopel/pull/1439#discussion_r288448346) (`s/form/from/`)

/cc @RustyBower

**Comment by RustyBower** [comment]
I'll take a peek :)

**Comment by dgw** [comment]
All of these were done in #1624. Another one bites the dust!
