### ISSUE TITLE
test_db.py needs updating

### ISSUE THREAD

**Issue by deathbybandaid** [sopel-irc/sopel#1623]
test_db.py currently tests directly with sqlite. `sqlite3.connect(db_filename)` is heavily used in these tests. These tests should reflect the new database system via sqlalchemy.

The default DB for sopel is sqlite, and we only NEED to test a mockconfig set for sqlite.

**Comment by dgw** [comment]
It's late in the cycle for 7.0, so this is totally puntable if @RustyBower hasn't the time to work on it in the next several weeks.
