### ISSUE TITLE
Way to access all users in a channel

### ISSUE THREAD

**Issue by ThijsEigenwijs** [sopel-irc/sopel#1637]
I've been looking in the documentation, but cant find something to get all the users that are in a channel. 

And sorry for all my questions, dont know where to ask them!

**Comment by HumorBaby** [comment]
Feel free to join us in #sopel on Freenode 😄

**Comment by half-duplex** [comment]
https://sopel.chat/docs/bot.html#sopel.bot.Sopel.channels
`bot.channels["#sopel"].users.keys()`
