### ISSUE TITLE
Eliminate/discourage "naive" datetime objects

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1647]
In short, we should try to eliminate things like this from Sopel's API:

https://github.com/sopel-irc/sopel/blob/b105fe4aaa6c1cd258337e60a4f17c1a0751ecb5/sopel/tools/time.py#L107

`datetime` objects, both in core and in plugins, should someday always be "aware" (have a timezone associated, even if it's just UTC), not "naive" (unaware of their own timezone).

I'm putting this in milestone 7.0.0 with intent to punt it if it isn't done by the first indication that Sopel 7 is ready to go. If this makes it in, great; if not, fine. I don't care, really; I just want to get it on our radar for planning and discussion purposes.

Follow-up to #1645.

**Comment by dgw** [comment]
7.0 isn't "ready" yet, but I don't see us spending time on this in the next month.

**Comment by dgw** [comment]
@Exirel What do you think, will it be enough to just change documentation, or do we need a deprecation cycle and warnings? Unless you have more concrete thoughts about it, I'm honestly not sure what to do about this yet, and it's probably best left to 8.0.

**Comment by Exirel** [comment]
Last time I checked, I think we mostly use very basic timestamps, and we don't do any kind of timezone related manipulation. I mean, except for the `.time` command and stuff, but this part is already pretty good IIRC.

I guess I should dive a bit more into this issue and check if we need to do something or if we can just write something short and clear in the documentation.

**Comment by dgw** [comment]
From #2005:

> This is related to #1647. It doesn't fix it but we may consider it done nonetheless.

We do. Let's let this one rest.
