### ISSUE TITLE
Database Encoding: UnicodeEncodeError issue

### ISSUE THREAD

**Issue by deathbybandaid** [sopel-irc/sopel#1650]
As per this snippet of IRC chat:

> 11:43 \<deathbybandaid>  sqlalchemy+mysql seems to have a problem that the sqlite database didn't have:
> 11:43 \<deathbybandaid>  'latin-1' codec can't encode character '\u2019' in position 268: ordinal not in range(256) (../MySQLdb/connections.py:245)
> 11:44 \<deathbybandaid>  only happens when I try to save stuff like    ¯\_(ツ)_/¯  to the database
> 11:45 \<deathbybandaid>  not sure if there is something that can be tweaked in db.py to fix this,, or if there is something I can do in the interum to mitigate the issue
> 11:46 \<deathbybandaid>  I have a command `.me` that users can save catchphrases to and call via `.me 1` or `.me homer`
> 11:47 \<deathbybandaid>  so if there isn't a bot command for something, they can make their own
> 11:49 <+Exirel>  deathbybandaid: hm, we could set an encoding parameter
> 11:49 <+Exirel>  but for now you can create the database yourself with the right default encoding (ie. utf8, usually utf8_general_ci)
> 11:50 <+Exirel>  because by default MySQL create tables with latin1_swedish, IIRC
> 11:51 \<deathbybandaid>  I'll open an issue then,,, just needed validation

**Comment by deathbybandaid** [comment]
I'm pretty stumped with this, I've tried just about everything that I saw via stackoverflow, and still nogo.

I even went as far as to delete the database and recreate it between tests too, just in case.

**Comment by dgw** [comment]
@RustyBower I think we could use your eyes on this when you have some time.

**Comment by RustyBower** [comment]
Should be fixed in https://github.com/sopel-irc/sopel/pull/1652

**Comment by Exirel** [comment]
Yup, it's fixed for MySQL indeed.
