### ISSUE TITLE
etymology: Empty argument not handled

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1657]
Doing `.ety` with no or an empty argument doesn't behave properly.

On Python 2 (my old personal instance), it causes `TypeError: None object cannot be quoted (file "/usr/lib/python2.7/urllib.py", line 1255, in quote)`

On Python 3 ("official" Sopel instance on freenode), the command looks up the etymology of "None" (and gets no results, because of the capital letter).

This is a good, easy issue for first-time contributors to fix.

**Comment by dgw** [comment]
As a pointer for future new contributors: There's no check for empty argument, despite this check for whether the word is too long: https://github.com/sopel-irc/sopel/blob/f3906680ed72aabbf14be144ebe01ce24b91f081/sopel/modules/etymology.py#L43-L44 Before that is the place to add checking for empty argument.

**Comment by AlfredOnGitHub** [comment]
Hey, a newbie here! I want to help here, so I'll start now.

**Comment by dgw** [comment]
@AlfredOnGitHub It's all yours!

**Comment by AlfredOnGitHub** [comment]
Hey @dgw, I made a pull request a while ago, but if you want to talk about the changes, please, let me know.

Thank you.
