### ISSUE TITLE
Idea: module.py action_commands function decorator

### ISSUE THREAD

**Issue by deathbybandaid** [sopel-irc/sopel#1658]
I had an idea after looking at:

https://github.com/dgw/sopel-flipper/blob/master/flipper.py

I think it would be pretty cool to consolidate

````
@sopel.module.rule('^rolls (.+)')
@sopel.module.intent('ACTION')
````

to

````
@sopel.module.action_commands('rolls')
````

and add another format for potential command structures.

**Comment by dgw** [comment]
Could be useful, I guess.

Note that the plain old `@commands` decorator currently also works in `/me` actions, e.g. `* deathbybandaid .tell nick something` still runs the`.tell` command. If there is to be a dedicated decorator for commands that should trigger on actions, I wouldn't want such overlap to exist.

Actually, I wonder if any plugins out there specifically expect their commands to work in actions, or if most plugin authors are unaware that it does work. Maybe I should write up an issue about deprecating that behavior in Sopel 7 so we can clear the way for a dedicated action command decorator in Sopel 8.

**Comment by dgw** [comment]
#1660 was merged a month ago. This feature request should have been closed at that time.
