### ISSUE TITLE
Instagram URL sometimes shows KeyError

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1667]
Once in while my Sopel shows this from Instagram URLs:
```
[05:28pm] Ant> http://www.instagram.com/p/Bz9DBcphEui/
05:28PM URL> KeyError: 'edge_media_to_parent_comment' (file
          "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/modules/instagram.py", line 67, in
          parse_insta_json)
[05:36pm] Ant> http://www.instagram.com/p/Bz9DBcphEui/
05:36PM URL> [insta] Photo by Comics By Dane Johnson (@themiscgenius) | “She’s different... I
          swear...” You can’t change anybody; or so I’ve been told bunch of times. #oldiesbutgoodies
          #webcomics #comicstrip #dailydoodle #comicstrips #funnies #prayingmantis | 1080x1080 | Likes: 284
          | Comments: 4 | Uploaded: 2019-07-15 22:17:26
```

```
[07:03pm] Ant> .version
07:03PM URL> Ant: Sopel v. 6.6.9
```

**Comment by dgw** [comment]
Probably transient errors with Instagram that cause Sopel to receive an error page that doesn't contain the expected data.

If we can get a copy of the HTML from one of the page loads that triggers this error, we can try to build logic into the Instagram plugin to catch such errors and retry. I doubt you're set up to capture Sopel's network traffic in that way, though.

**Comment by dgw** [comment]
Just saw this on my own instance. Retrying maybe ten seconds later fixed it… Hmm. Definitely Instagram being some kind of flaky.

**Comment by Exirel** [comment]
A better error handling can't be bad.
