### ISSUE TITLE
Audit uses of verify_ssl

### ISSUE THREAD

**Issue by half-duplex** [sopel-irc/sopel#1704]
`verify_ssl` should only be used for the IRC server connection. If anyone needs to `verify_ssl=False` to talk to youtube, xkcd, etc. in 2019, they've got bigger problems they should fix first.

**Comment by dgw** [comment]
> If anyone needs to `verify_ssl=False` to talk to youtube, xkcd, etc. in 2019, they've got bigger problems they should fix first.

🙌🙌🙌🙌

There's a fair bit of nonsense to handle the case of SSL not being available, probably from the days of py2.4/2.5 or some other really old version from before even Willie (let alone Sopel) existed. We can probably ditch _all_ of it at this point. I don't think it's even possible to install Python without SSL on any system you'd want to connect to the Internet now.

**Comment by Exirel** [comment]
You can still do that (install without correct SSL support) thanks to Python 2.7. From my experience, at least on Ubuntu 18.04 you still have problems with it.
