### ISSUE TITLE
db: get_uri() assumes SQLite

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1745]
@RustyBower This slipped by me completely in the whole DB-overhaul process. Obviously this function is useless for instances not using SQLite, in its current state. Not that there will be any of those among upgrade instances (at least, not immediately), but…

https://github.com/sopel-irc/sopel/blob/b33173ca5f52905f9ca45c0890e9340779c0c06d/sopel/db.py#L189-L191

Honestly, is this function even still useful? Should we just deprecate it and move on?

**Comment by RustyBower** [comment]
I'll take a look :) This probably isn't useful, but while I'm under the hood, I can build some of the API calls for generating sessions and such for plugins
