### ISSUE TITLE
`rule` cannot match multiple times in one line

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1757]
We ran into this with using `@rule` instead of `@url` to match links (because the latter was somewhat broken in 6.x), and now we're running into it again with stuff like #1722.

I won't say that `@rule` should _always_ be allowed to match multiple times in the same line, but there definitely are use-cases where it would come in handy.

This should probably be implemented as an optional kwarg to the decorator.

**Comment by dgw** [comment]
Re-prioritized. The inconsistency between `@rule` (one match per line) and `@url` (multiple matches per line) is kinda ridiculous. Even if we can't make multiple matches per line the default because of old plugins that assume it can only match once (and therefore didn't write their regexes defensively).

**Comment by Exirel** [comment]
Thanks to #1873 we can now have rules that change how they match on a line. So I'll be working on that, and that should land in Sopel 7.1.
