### ISSUE TITLE
`trigger` should have an easy way to get plain-text (no formatting)

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1768]
Note that this is a distinct feature from #462, which requests the ability to match rules on the plain-text version of each line.

My notes from back when I wrote this idea down proposed `trigger.plain` as the home for this data. We could even parallel `trigger.group` with `trigger.plain.group`… Bikeshedding welcome, I guess. This isn't going into the next release (7.0), so there's time to consider and discuss.

**Comment by Exirel** [comment]
I assume it makes sense, but right now I'd like an example of what you mean by "no formatting".

**Comment by dgw** [comment]
> an example of what you mean by "no formatting"

Original:

    \x0301,01Spoiler text\x03 with \x02BOLD\x02 assumptions!

No formatting:

    Spoiler text with BOLD assumptions!

This obviously doesn't show _all_ formatting types, but at minimum the "plain" representation of the trigger's text should remove all known formatting characters and (for colors) their values. Perhaps it should also remove all non-printable characters just to be safe against future formatting extensions?

**Comment by dgw** [comment]
Might be best implemented as a new function in `tools`, which could be used in #462 also. For reference, we'd do [something like ZNC's `CString::StripControls()` method](https://github.com/znc/znc/blob/5fd7584e7c4efadc5e1e7153340c18810f91e2a2/src/ZNCString.cpp#L1393-L1440) (`StripControls_n` implementation shown, because that's where the logic is).
