### ISSUE TITLE
time format and timezone info are written to  and read from different places

### ISSUE THREAD

**Issue by sukiletxe** [sopel-irc/sopel#1803]
When I run `sopel` for the first time, it writes the dfault time format to `clock.time_format`, yet it reads it from `core.default_time_format` (as shown in `tools/time.py`. The same thing happens with timezone, it writes it to `clock.tz` and it reads it from `core.default_timezone`.

Sopel installed on Windows, v6.6.9, via pip.

**Comment by dgw** [comment]
We removed the unused settings from `clock` for the forthcoming 7.0 version, in #1696.
