### ISSUE TITLE
`@url` callables ignore some other plugin decorators

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1816]
### Description
The `@output_prefix` decorator has no effect when used with `@url`. Output from a `@url`-decorated function is not prefixed with the given string.

### Minimal demo case
```python
@module.url('https?://example.com/')
@module.output_prefix('[Example] ')
def example_url(bot, trigger, match):
    bot.say('I should be prefixed!')
```

### Actual behavior
Triggering the function makes Sopel say, "I should be prefixed!"

### Expected behavior
Triggering the function makes Sopel say, "[Example] I should be prefixed!"

### Environment
- Sopel `.version`: 7.0.0 (also confirmed on 7.0.1-dev @ 85c6a58aa8923922b125e0f65eb0ba5f8c196dd5)
- Sopel installed via: pip (also source)
- Operating system: Ubuntu 18.04 (WSL)
- Python version: 3.6.9
- IRCd `/version`: n/a
- Relevant plugins: n/a

### Additional notes
Decorators confirmed affected:
- `@echo`
- `@output_prefix`

Note that `@url` callables bypass nick/host blocks set with the `.blocks` command because of their unique dispatch logic path, too.

**Comment by dgw** [comment]
Messages containing URLs are handled inside a `@rule` callable in `coretasks.py`:

https://github.com/sopel-irc/sopel/blob/85c6a58aa8923922b125e0f65eb0ba5f8c196dd5/sopel/coretasks.py#L998-L1012

We'd need to rework that in one of two ways (that I can see): either move it to [`bot.py`'s first-class dispatch function](https://github.com/sopel-irc/sopel/blob/85c6a58aa8923922b125e0f65eb0ba5f8c196dd5/sopel/bot.py#L692) somehow, or make sure that URL callables get their own `SopelWrapper` instead of the one `handle_url_callbacks` itself got.

If we go the route of handling URL callables in the main dispatch function, we'd need to either change this exclusion and consider functions with `url_regex` as "triggerable":

https://github.com/sopel-irc/sopel/blob/85c6a58aa8923922b125e0f65eb0ba5f8c196dd5/sopel/loader.py#L135-L138

or make sure to set `output_prefix` on every function during loading _before_ the `is_triggerable` check:

https://github.com/sopel-irc/sopel/blob/85c6a58aa8923922b125e0f65eb0ba5f8c196dd5/sopel/loader.py#L50-L64

----

Note that I haven't investigated `@interval` callables for this behavior, but they might be similarly unable to take advantage of `@output_prefix`. It might be worth testing for that, too, when crafting a fix for this `@url` issue.

**Comment by dgw** [comment]
Retitled to reflect additional observations/tests: One cannot (for example) make a URL callable match on search results for certain sites with `@module.echo`, because the `coretasks` function responsible for dispatching URL matches won't trigger on echo-messages.

**Comment by dgw** [comment]
Another observation: `@url` callables also bypass the per-channel configuration settings.

**Comment by dgw** [comment]
Retitled again, and will shortly update the OP. #1812 fixes per-channel configuration, but nick/host blocks are enforced earlier in the dispatch pipeline and `@url` callables can still bypass those.

**Comment by Exirel** [comment]
Since #1873 has been merged, I think I should be able to include URL Callbacks into the new system, instead of having something on the side. That would fix the problem. And if it doesn't, I'll make it.

**Comment by Exirel** [comment]
As per #1904 this should be fixed.
