### ISSUE TITLE
Feature: Plugin compatibility check

### ISSUE THREAD

**Issue by deathbybandaid** [sopel-irc/sopel#1834]
A feature that would check the requirements file (or some other means) for the version of Sopel that a plugin author has tested a plugin as being compatible with.

Similarly to how ZNC handles this, output warnings that a plugin may not be compatible.

**Comment by dgw** [comment]
I like this in theory, even though installing via pip (the only truly supported method) will already warn the user if an installed plugin package's requirements don't include the newly installed Sopel version. (I experienced a lot of these warnings first-hand around when 7.0.0 dropped.)

**Comment by deathbybandaid** [comment]
But would you see these warnings if you only updated sopel?

**Comment by dgw** [comment]
Yes. pip will install the new sopel, then warn that (for example) sopel-modules.twitter has requirement sopel<7.0 but you'll have 7.0.0, which is incompatible.

Again, I saw these myself a lot until I got more plugins updated.

**Comment by Exirel** [comment]
I'm tempted to refuse that feature request. I feel like it's adding complexity while there are other way to "prevent", or "help" bot owner with plugin incompatibilities (such as version & dependencies requirement).

**Comment by dgw** [comment]
Let's leave Sopel version compatibility markers to the package manager (`pip`).

If we ever get around to reworking the plugin system (again) to support attaching Sopel-specific metadata, maybe we'll revisit.
