### ISSUE TITLE
Use the database to store seen nicks

### ISSUE THREAD

**Issue by deathbybandaid** [sopel-irc/sopel#1836]
Essentially, this would allow the bot to know a list of users that it had seen in the past, but cannot see currently.

This is something I've done with my sopel instance manually for quite a while for several of my plugins.

**Comment by RustyBower** [comment]
This already exists in the Nicknames table. It deeps a list of every nick that the bot has seen in any channel the bot is present in

**Comment by dgw** [comment]
Closing unless there's a different function not served by the existing data.
