### ISSUE TITLE
Topic command expects that bot needs to be a channel operator

### ISSUE THREAD

**Issue by Petteri** [sopel-irc/sopel#1842]
### Description
Topic command expects that bot needs to be channel operator, even when the channel does not have +t mode set.

### Reproduction steps
join a channel where +t is not set
```
<petteri> .topic test
<bot> petteri: I'm not a channel operator!
-- Mode #test [+o bot] by petteri
<petteri> .topic test
-- bot has changed topic for #test from "test" to "Welcome to: #test | Topic: test"
```

### Expected behavior
bot should be able to set the topic on a channel without +t even when it is not a channel operator

### Environment
- Sopel `.version`: [c705f450e56b9ddded10226c640a607249e33710]
- Sopel installed via: [source]
- Python version: [3.7.4]
- Operating system: [Ubuntu 19.04]
- IRCd `/version`: [oragono v2.0.0]

**Comment by dgw** [comment]
Rewriting our MODE tracking would be good to do for 7.1, now that we parse and expose ISUPPORT data. This would require adding real mode-tracking for channels, though; currently Sopel only pays attention to channel privileges.

Disclaimer: This could get bumped to a later release depending on how long it takes to design the interface for plugins to access channels' MODE info.

**Comment by dgw** [comment]
@Exirel Does this fruit seem low-hanging enough to get done for 7.1 yet, or do you wanna punt it?
