### ISSUE TITLE
Allow setting User_Agent via config

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel#1869]
### The problem
User agents should be custom to each user where possible, we can't do this with modules as there is no config option.

### The solution
Move url.py and anything else making a request to use a user agent from the bot's config

**Comment by dgw** [comment]
This isn't a Sopel feature request. You're asking us to add a configuration option to `requests`.

**Comment by RhinosF1** [comment]
It is. Sopel sets the user agent on it’s modules using USER_AGENT and adding it to a header but using a fixed one.

I’m asking for that to be changed to bot.config.core.useragent

**Comment by RhinosF1** [comment]
See https://github.com/sopel-irc/sopel/blob/master/sopel/modules/url.py#L30 for example

**Comment by dgw** [comment]
Plugins are free to use whatever user-agent they like; it's not required to use that constant. You can even skip all of the `DEFAULT_HEADERS` too.

**Comment by RhinosF1** [comment]
> Plugins are free to use whatever user-agent they like; it's not required to use that constant. You can even skip all of the `DEFAULT_HEADERS` too.

We can’t change what other peoples plugins (like core url.py) uses though at the moment. This ticket is about introducing config and making sopel core use it.

**Comment by dgw** [comment]
Saying that "Sopel sets" the user-agent on its plugins is not correct. Plugins choose to use either the `requests` default, the default Sopel provides as a constant, or a custom one if they need to spoof e.g. a browser.

**Comment by dgw** [comment]
You can't force other plugins to use a different user-agent. It's entirely outside Sopel's control as soon as they stop using the OPTIONAL constants in `sopel.tools.web`. This feature request makes no practical sense to me.

**Comment by RhinosF1** [comment]
> You can't force other plugins to use a different user-agent. It's entirely outside Sopel's control as soon as they stop using the OPTIONAL constants in `sopel.tools.web`. This feature request makes no practical sense to me.

How would a bot operator change the UA of sopel core modules then?

**Comment by dgw** [comment]
They don't? If the UA a core plugin uses is causing problems, I'd rather it be reported and fixed in upstream than hacked around with a config option in the field.
