### ISSUE TITLE
choose: IRC formatting can make weird output

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1877]
### Description
Input with certain formatting characters in certain locations can mess up the `choose` plugin's output:

```
<user>  .ch Sherlock, BBC's \x1DSherlock\x1D, \x1FTorchwood
<sopel> user: Your options: Sherlock, BBC's \x1DSherlock, Torchwood. My choice: Sherlock
```

Or, to recreate the IRC rendering using Markdown formatting:

> &lt;user&gt; &nbsp;.ch Sherlock, BBC's _Sherlock_, ~~Torchwood~~
> &lt;sopel&gt; user: Your options: Sherlock, BBC's _Sherlock, Torchwood. My choice: Sherlock_

Some IRC formatting characters get stripped here, but not all; Python considers _some_ control characters as "whitespace" for the purposes of `str.strip()`: https://github.com/sopel-irc/sopel/blob/d7bc97a94521fc4c7a4656fa8c0158e1833f72f4/sopel/modules/choose.py#L41
Combine that with formatting in the middle of a choice (obviously ignored by `strip()`) and we can get pretty messy output indeed.

For the example I gave above, the problem comes from Python removing the second `\x1D` (end italic) from the end of choice 2 and the `\x1F` (begin strikethrough) from the beginning of choice 3, meaning that the first `\x1D` (italic) is never canceled and gets applied through the end of the output line.

The obvious workaround is to tell users "don't use formatting for choices". That's probably not helpful.

The obvious _code_ workaround is to strip _all_ formatting from choices, forcing them all to be plain text. We most certainly can do that, but it would be better to find a solution that allows users to format choices however they want without breaking the plugin's output.

Perhaps the simplest solution is to apply a formatting reset (`\x0F`) before the comma, turning the first line here into `'\x0F, '.join(`: https://github.com/sopel-irc/sopel/blob/d7bc97a94521fc4c7a4656fa8c0158e1833f72f4/sopel/modules/choose.py#L45-L48
But it would be more elegant to only include a reset character when needed, and place it inside the quotes if the option contains a comma.

**Comment by Exirel** [comment]
Since I added a `plain` function to strip control code from a text in #1918 maybe we can do something about that.

**Comment by dgw** [comment]
(Don't know why I missed this last month but) I think the ideal case is to preserve the formatting, not remove it. The current code just sometimes tries to do _both_ depending on where the formatting characters appear, thanks to the behavior of built-in `str.strip()`.

Ideally we'd be able to take the "default" character set that `strip()` lops off the string's ends as "whitespace" and remove just the ones Sopel is aware of as formatting characters… but `strip()` is implemented in C, and can't be introspected to fetch that default value (and doesn't actually _have_ one, either, as implemented). There's also no nice way of getting the list of Unicode codepoints considered as "whitespace", which would be another way of building our own replacement for the default "argument". [I looked into this stuff while working on #1939, before taking a different direction due to these very limitations.]

**Comment by dgw** [comment]
Very close to opening a PR for this. Clearing assignment while I polish stuff.
