### ISSUE TITLE
reddit: floating point error in upvote ratio

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#1884]
https://github.com/sopel-irc/sopel/blob/d850844870ac62e4568b4743bd38f0f90d76af7d/sopel/modules/reddit.py#L183

Occasionally this code results in an output ratio like "57.99999999999999%".

Should be super easy for anyone who wants a quick PR.

**Comment by sanyam1997** [comment]
Hey, I would like to work on this issue. I am a first-time contributor. Can you suggest relevant resources to be studied for working on this issue? It seems simple though.

**Comment by cottongin** [comment]
@sanyam1997 using something like the Python built-in string formatting tools make this very simple e.g.:

``` python
percent = color("{:.2%}".format(s.upvote_ratio), point_color)
```

I have not tested this myself on my own bot instance but it should work

**Comment by sanyam1997** [comment]
So how can I test the code after installing it following git repo?
