### ISSUE TITLE
STATUSMSG not handled in `Identifier.is_nick()`

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel#1886]
### Description
Freenode adds a @ to the channel name in a +mz channel or +z channel where the user is quieted.

This means #channel becomes @#channel and the it's impossible to use trigger.sender to kick a user, for example, from the channel based on what they said.

### Reproduction steps
1. Create a +mz channel on Freenode and set log_raw to True
2. op your bot have a user who can only speak to ops say something.
3. You will see the channel is recorded as @#channel

### Expected behavior
The @ is dropped from trigger.sender (but maybe something like trigger.was_moderated is added to indicate it)

(PS: I can attempt it tonight)

### Logs
```
2020-06-05 22:47:01,739 << :test-lta!uid348912@gateway/web/irccloud.com/x-zbfyoyydyhcwvgmu PRIVMSG @#miraheze-overflow :sing and dance with me
```

### Environment
- Sopel `.version`: 7.0.1 & 7.0.4 tested
- Sopel installed via: pip (both)
- Python version: 3.5.3 (both)
- Operating system: Debian Stretch (9.7) for .1 & Debian 4.9.144-3 (2019-02-02) x86_64 for .4
- IRCd `/version`: Freenode (https://freenode.net/news/seven-118)

**Comment by dgw** [comment]
Going to leave these here for whoever first decides to work on implementing this (could be me, could be someone else): https://modern.ircdocs.horse/#statusmsg-parameter & https://modern.ircdocs.horse/#privmsg-message
