### ISSUE TITLE
Sopel sometimes doesn't get YouTube URLs' titles.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1896]
### Description
Sometimes, Sopel doesn't show YouTube's URL's titles.

### Reproduction steps
Example:
[02:41pm] Ant> http://www.youtube.com/watch?v=EiIUmQsHlOU
02:41PM URL> [ YouTube ] - www.youtube.com
[02:43pm] Ant> http://www.youtube.com/watch?v=EiIUmQsHlOU
02:43PM URL> [ Slow internet is way worse than no internet | Ivan Decker - YouTube
          ] - www.youtube.com
[02:43pm] Ant> https://www.youtube.com/watch?v=EiIUmQsHlOU
02:43PM URL> [ Slow internet is way worse than no internet | Ivan Decker - YouTube
          ] - www.youtube.com

### Expected behavior
Sopel should always show YouTube's valid URL's titles. 

### Logs
Nothing unusual in my ~/.sopel/logs

### Environment
- v7.0.4 (Python 3.4.2)
- pip
- Python 3.4.2
- Debian Jessie v8
- IRCd `/version`:
��� BitchX: Client: BitchX-1.2.1 (internal version 20141114)
��� ircd-ratbox-3.0.8(20121231_3-27427).: irc1.zimage.com eGHIKMpZ6 TS6ow 1ZI
��� CHANTYPES=&# EXCEPTS INVEX CHANMODES=eIb,k,l,imnpstS CHANLIMIT=&#:15
          PREFIX=(ov)@+ MAXLIST=beI:25 MODES=4 NETWORK=zImage KNOCK STATUSMSG=@+
          CALLERID=g :are supported by this server
��� SAFELIST ELIST=U CASEMAPPING=rfc1459 CHARSET=ascii NICKLEN=32 CHANNELLEN=50
          TOPICLEN=160 ETRACE CPRIVMSG CNOTICE DEAF=D MONITOR=60  are supported by
          this server
��� FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR:
          :are supported by this server

### Notes
Note that it sometimes works and not. I also noticed Reddit's link submissions has the same issue too like Sopel. I think this is a YouTube's issue that started a few weeks ago. However, is there a way to have Sopel to automatically retry after getting "[ YouTube ] - www.youtube.com" results?

Thank you for reading and hopefully answering and fixing. :)

**Comment by dgw** [comment]
As stated in your previous issue about title fetching issues (#1895), Sopel cannot guarantee that any given site will send correct title data (or any title data). Generic title data is a fairly common issue with Twitter links, too.

For YouTube specifically, install [sopel-youtube](https://github.com/sopel-irc/sopel-youtube) for video info.

**Comment by cottongin** [comment]
I _think_ this is likely caused by the page not being "loaded all of the way" when the bot finishes fetching the page (see how that is done [here](https://github.com/sopel-irc/sopel/blob/master/sopel/modules/url.py#L287-L298)).  

In short, in the current implementation a request for the page is opened and then closed once `</title>` exists in the response.  This works for the majority of sites, and especially for static sites, but for dynamic (JavaScript or otherwise) has the chance of failure like you are seeing here (and it is _not_ exclusive to YouTube).

An improvement could be made in the `url` plugin to look for the `<meta property="og:title">` or `<meta name="title">` tags and use that instead. Falling back to `<title>` tag if those are not present.  The "modern" web utilizes these tags almost universally, and often contain the _actual_ data the `url` plugin is attempting to fetch and parse.  This would require a bit of effort on refactoring/implementing however.

As @dgw mentioned, you could install the [sopel-youtube plugin](https://github.com/sopel-irc/sopel-youtube) to remedy this problem for YouTube links specifically - and gain more informative output as well!

**Comment by antdude** [comment]
Thanks. I did a "pip install sopel_modules.youtube" and .restarted my Sopel bot, but it gets the titles sometimes.  Do it need API key to make it work 100%?

**Comment by cottongin** [comment]
@antdude yes, you need an API key, as the instructions on the page state
https://github.com/sopel-irc/sopel-youtube#getting-your-api-key

**Comment by antdude** [comment]
Thanks. What's up with more web site sites wanting API keys these days? It's annoying. :(

**Comment by antdude** [comment]
Hmm, now YouTube links just show "[url] - YouTube | www.youtube.com". :(

**Comment by half-duplex** [comment]
Working fine for me. Make sure sopel and sopel-youtube are up-to-date, and check the bot's logs.

**Comment by dgw** [comment]
I'm fairly sure Ant just doesn't use the YT plugin and hopes `url` will just deal with it.

Which is flaky—and that's why sopel-youtube exists.

**Comment by antdude** [comment]
I can't seem to get it to work: 

11:57PM <URL> YouTube API key not authorized. Please make sure this key is enabled to access YouTube. (Note: If you have recently made changes to the API key's settings, they may take a few moments to propagate across Google's network.)

Is it because I just made it and have to wait? It's unrestricted. I used https://github.com/sopel-irc/sopel-youtube's instructions.

**Comment by dgw** [comment]
It says in the message you pasted that API key changes (including creation, or enabling a new service such as YouTube Data API) can take some time to propagate.

Double check that the required API is enabled for that key, and that the key itself is copied over correctly into Sopel's config. If the key is set up correctly and still doesn't work, though, all you can do is wait for Google to catch up with itself.

**Comment by antdude** [comment]
Yep, still the same error. I used "sopel-plugins configure youtube" and checked my ~/.sopel/default.cfg to verify. I guess I will have to wait more. :(

**Comment by dgw** [comment]
Really not sure what to tell you here. I tested two fresh keys, one restricted to the YT Data API v3, and one unrestricted:

![image](https://github.com/user-attachments/assets/e8345ad2-3431-44d1-9ed5-a7ce02555199)

Both worked:

![image](https://github.com/user-attachments/assets/41816e90-41ae-4317-9c5a-d261d1e41ac1)

Something is wonky, but it seems to be an issue with your configuration and not a problem with `sopel-youtube` itself. (This is assuming you have installed `sopel-youtube==0.6.0`, the latest version as of right now. If not… upgrade to it and try again.)

**Comment by antdude** [comment]
I also can't find anything in the logs of these errors in ~/.sopel/logs. Am I not seeing them?

**Comment by dgw** [comment]
The errors themselves are not logged. Authorization failure is raised as an exception by Google's API client library, and caught by the youtube plugin to display a friendly error message instead. You'd have to edit the plugin file (not recommended) or reproduce a stripped-down version of what it's doing in your own local Python repl (`python3 -i`) to inspect the raw exception.

The above is what I would try if I had a broken key in hand, assuming creating a fresh one didn't help. (And I feel compelled to repeat: This is not a support forum. IRC is the better place to ask for help with this.)

**Comment by dgw** [comment]
Experimenting with creating a new key, deleting it, restoring it, and changing the API restrictions revealed that you will meet the condition that triggers the specific "API key not authorized" message (HTTP 403) if _the key's restrictions_ do not allow it to access the YouTube Data API v3. If the key is _invalid_ (e.g. mistyped) or revoked, a different message condition ("YouTube API rejected the configured key. […]") will be met instead (HTTP 400).

_(To watchers: Sorry for double-email! I wanted to make sure this didn't get missed in an edit.)_
