### ISSUE TITLE
reddit: Support PRAW 7

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel#1903]
### The problem
I can't update praw to version 7
`$ pip3 check
sopel 7.0.4 has requirement praw<6.0.0,>=4.0.0, but you have praw 7.1.0.
praw 7.1.0 has requirement prawcore<2.0,>=1.3.0, but you have prawcore 0.14.0.
The command "pip3 check" exited with 1.`

### The solution
Support the latest version of praw

**Comment by dgw** [comment]
But why does it matter?

Haven't checked the API changes for newer PRAW versions, but if you have something else installed that needs more recent PRAW that's kind of what venvs are for.

**Comment by RhinosF1** [comment]
> But why does it matter?
> 
> Haven't checked the API changes for newer PRAW versions, but if you have something else installed that needs more recent PRAW that's kind of what venvs are for.

We just like to ensure things are kept up to date. It's 100% low priority and a nice to be.

**Comment by dgw** [comment]
Looks like the current `praw` version range was selected to match Sopel's Python release compatibility as closely as possible without needing to use environment specifiers. Slotting this for 8.0, since we'll be dropping old Pythons then.

**Comment by deathbybandaid** [comment]
I'd also want to thoroughly verify that everything in `reddit.py` still functions 100% without stripping functionality.

**Comment by dgw** [comment]
@deathbybandaid That's (theoretically) why we have tests. Missing examples should be added for code paths that aren't covered.
