### ISSUE TITLE
IMDB.com's episode URL shows an unexpected error.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#1907]
### Description
IMDB.com's episode URL shows an "Unexpected error ('Config' object has no attribute 'imdb') from Ant at... Message was:
          https://www.imdb.com/title..."

### Reproduction steps
Use any IMDB.com's TV series episode list like https://www.imdb.com/title/tt1811179/episodes, https://www.imdb.com/title/tt2364582/episodes, etc.
Example (URL is the name of my Sopel bot):
...
[11:07pm] Ant> https://www.imdb.com/title/tt2364582/episodes
11:07PM URL> Unexpected error ('Config' object has no attribute 'imdb') from Ant at
          2020-07-22 23:07:07.725907. Message was:
          https://www.imdb.com/title/tt2364582/episodes
[11:07pm] Ant> hm
[11:07pm] Ant> https://imdb.com
11:07PM URL> [ IMDb: Ratings, Reviews, and Where to Watch the Best Movies & TV Shows ] -
          imdb.com
...

### Expected behavior
No or a more specific clear error without having to view its ~/.sopel/logs/default.error.log, and/or showing "Agents of S.H.I.E.L.D. - Season 7 - IMDb" results for my example?

### Logs
```
2020-07-22 23:16:08,696] sopel.bot            ERROR    - Unexpected error ('Config' object has no attribute 'imdb') from Ant at 2020-07-22 23:16:08.695769. Message was: https://www.imdb.com/title/tt2364582/episodes
Traceback (most recent call last):
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/bot.py", line 606, in call
    exit_code = func(sopel, trigger)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/coretasks.py", line 1016, in decorated
    return function(bot, trigger, match=match)
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel_modules/imdb/imdb.py", line 118, in imdb_url
    if bot.config.imdb.api_key is None or bot.config.imdb.api_key == '':
  File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel/config/__init__.py", line 297, in __getattr__
    % (type(self).__name__, name))
AttributeError: 'Config' object has no attribute 'imdb'
```

### Environment
- v7.0.4 (Python 3.4.2)
- pip
- 3.4.2
- Debian Jessie v8
- IRCd `/version`: ��� BitchX: Client: BitchX-1.2.1 (internal version 20141114)
��� ircd-ratbox-3.0.8(20121231_3-27427).: irc1.[deleted since it's a private IRC server].com eGHIKMpZ6 TS6ow 1ZI
��� CHANTYPES=&# EXCEPTS INVEX CHANMODES=eIb,k,l,imnpstS CHANLIMIT=&#:15 PREFIX=(ov)@+
          MAXLIST=beI:25 MODES=4 NETWORK=zImage KNOCK STATUSMSG=@+ CALLERID=g :are supported by
          this server
��� SAFELIST ELIST=U CASEMAPPING=rfc1459 CHARSET=ascii NICKLEN=32 CHANNELLEN=50 TOPICLEN=160
          ETRACE CPRIVMSG CNOTICE DEAF=D MONITOR=60  are supported by this server
��� FNC TARGMAX=NAMES:1,LIST:1,KICK:1,WHOIS:1,PRIVMSG:4,NOTICE:4,ACCEPT:,MONITOR: :are
          supported by this server

### Notes
Please feel free to ask more questions for details? Thank you for reading and hopefully answering and fixng. :)

**Comment by RustyBower** [comment]
This probably belongs over https://github.com/RustyBower/sopel-imdb/issues

**Comment by RustyBower** [comment]
It looks you like you installed the sopel-imdb module but didn't configure it

**Comment by dgw** [comment]
\> `File "/home/ant/SopelPython3/lib/python3.4/site-packages/sopel_modules/imdb/imdb.py", line 118, in imdb_url`

Yep, that's not part of Sopel. Closing. Feel free to continue discussing, of course.

@RustyBower I'd transfer the issue, but we haven't done the thing (moved those few plugins to this org) yet.

**Comment by dgw** [comment]
> It looks you like you installed the sopel-imdb module but didn't configure it

BTW @RustyBower I'd avoid having `default=''` [here](https://github.com/RustyBower/sopel-imdb/blob/5f601da1b6ece4d28b2ab04192e31cd1ecd26352/sopel_modules/imdb/imdb.py#L21). You'd be better off with a required value, so the plugin will instead fail to load if not configured.

**Comment by RustyBower** [comment]
Yep! I haven't had a chance to fix this plugin yet :(
