### ISSUE TITLE
wikipedia: replace "w" alias with "wp"

### ISSUE THREAD

**Issue by xnaas** [sopel-irc/sopel#1912]
### The problem
Wikipedia module stole ~~our previous~~ the precious "w" alias which could be used for "weather" or something else.

### The solution
Remove "w" alias from Wikipedia module.

### Notes
```
21:19:56 <+dgw> Make an issue, I'll put it in 8
```

---

P.S. c bad

**Comment by dgw** [comment]
OK um, "our" refers to a previous bot run by @xnaas, not an older version of Sopel/Willie/Jenni/Phenny :P

Anyway I'm going to flesh this out with the whole context: We'd like to replace the `w` alias with `wp`, to match with `wiktionary`'s `wt`, and free up `w` for the much more common meaning of "weather", probably in `sopel-modules.weather` by @RustyBower.
