### ISSUE TITLE
Import file mismatch in testsuite

### ISSUE THREAD

**Issue by mweinelt** [sopel-irc/sopel#1926]
### Description
I'm running into an "import file mismatch" while running the testsuite.

### Reproduction steps
1. `pytest .`

### Expected behavior
The testsuite should find the right module to import.

### Logs
```
============================= test session starts ==============================
platform linux -- Python 3.8.5, pytest-5.4.3, py-1.8.2, pluggy-0.13.1 -- /nix/store/fjgnz0xfl04hsblsi4ym5y5akfh6mlmy-python3-3.8.5/bin/python3.8
cachedir: .pytest_cache
rootdir: /build/sopel-7.0.6
plugins: sopel-7.0.6
collected 215 items / 1 error / 214 selected

==================================== ERRORS ====================================
_____________________ ERROR collecting sopel/test_tools.py _____________________
import file mismatch:
imported module 'sopel.test_tools' has this __file__ attribute:
  /nix/store/apl4l88a2vy1d7m6d46ncimcqgcz9xqa-python3.8-sopel-7.0.6/lib/python3.8/site-packages/sopel/test_tools.py
which is not the same as the test file we want to collect:
  /build/sopel-7.0.6/sopel/test_tools.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules
=========================== short test summary info ============================
ERROR sopel/test_tools.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 1.07s ===============================
builder for '/nix/store/1b8lz3vgqi6qclpyq9by7z37m8dsfq45-python3.8-sopel-7.0.6.drv' failed with exit code 2
```

### Environment
- Sopel `.version`: 7.0.6
- Sopel installed via: source
- Python version: 3.8.5
- Operating system: NixOS 20.09

### Notes
-

**Comment by Exirel** [comment]
I can't reproduce, and reading from a google search on `import file mismatch`, it appears that's it's more 1) a limitation of pytest and 2) something to do with your environment

Can you tell use more about what you are doing? It looks like you are trying to build something and you have some duplicate files here and there.

**Comment by mweinelt** [comment]
I'm pulling the tarball for 7.0.6 from pypi, the package manager of my distro is resolving the dependencies for me. But running the tests I run into the issue above.

We're building in a sandbox, so there will be no __pycache__ or .pyc files pollution.

I wonder how what particular thing about my environment could cause this, do you have a source for that statement?

From reading search results it could be about these two files having the same name:
- `sopel/test_tools.py`
- `tests/test_tools.py`.

**Comment by Exirel** [comment]
Your are pulling the tarball... but are you installing it too? It feels like you have installed Sopel, then you are trying to run the test from another directory but within the same Python environment. Reading the log it doesn't talk about `tests/test_tools.py`, it talks only about one single **module**: `sopel.test_tools`.

Look again:

```
imported module 'sopel.test_tools' has this __file__ attribute:
  /nix/store/[...]/lib/python3.8/site-packages/sopel/test_tools.py
which is not the same as the test file we want to collect:
  /build/sopel-7.0.6/sopel/test_tools.py 
```

One is in a `/nix/[... python install dir ...]/site-packages` directory, the other is in a `/build/sopel-7.0.6/` directory.

Note: Sopel *does not* provide any kind of support for tests run from the tarball from PyPI. We run the tests directly from source, *after* we have installed Sopel with `python setup.py develop` or `python setup.py install -e`. Anything else might fail.

> I wonder how what particular thing about my environment could cause this, do you have a source for that statement?

Yes: you have a bug I can't reproduce, and that isn't shown in our Travis environment either. So by elimination, it's tied to your environment.

**Comment by Exirel** [comment]
Note: if it was a problem between `sopel/test_tools.py` and `test/test_tools.py`, py.test would talk about that, which is not the case here.

**Comment by mweinelt** [comment]
It was well explained by @drewrisinger over at https://github.com/NixOS/nixpkgs/pull/95689#issuecomment-675220146 and fixed on our end. Sorry for the noise!

**Comment by Exirel** [comment]
Don't worry, it's cool to see people using Sopel and building packages out of it. I'm happy to see it's resolved on your end.
