### ISSUE TITLE
add ability to disable sed

### ISSUE THREAD

**Issue by serif** [sopel-irc/sopel#1957]
I've made a sopel bot on a server that already has a bot which responds to `s/search/replace/` sed syntax, so it's redundant for my sopel bot to do the same. I can't figure out how to disable that.

I tried adding this to default.cfg:

```
[core]
exclude =
    sed
```

When that didn't work I tried to override it by adding `s\/` to triggers and then to my module:

```
@module.commands(r"\w+\/\w+\/")
def disable_sed(bot, trigger) -> None:
    bot.say("trying to disable sed")
    pass
```

That does trigger, but it didn't overwrite the sed behavior. They both trigger:

```
serif: test
serif: s/test/testing/
my_sopel: serif meant to say: testing
my_sopel: trying to disable sed
```

I've looked through the tutorials and other documentation, but I couldn't find how to do this besides those two failed attempts. Apologies if this already exists in the docs.

**Comment by dgw** [comment]
You can add this to disable the sed function:

```ini
[core]
exclude =
    find
```

You had the right approach the first time, but had trouble finding the right plugin name. 😸

**Comment by serif** [comment]
I see "Spelling Correction Module" in the description of the "find" plugin now. I also realized I should have added `-i` to my `grep` search to make it case-insensitive. If I had done that, the term "correct" would have triggered on "Correction".

Thanks again. :)
