### ISSUE TITLE
Rainbow Text

### ISSUE THREAD

**Issue by xnaas** [sopel-irc/sopel#1962]
### The problem
Rainbow text is a *crucial part* of IRC and the IRC experience.

### The solution
Reply to `.rainbow <text here>` with `<text here>` all beautiful and rainbow-fied.

### Alternatives
Using a bot that isn't Sopel... 🤮

### Notes
Example screenshot:

![example](https://i.imgur.com/DsUz2Vu.png)

**Comment by dgw** [comment]
A `.rainbow` command? Could you not just… create a `sopel-rainbow` plugin? 🤔

I'm not gonna lie, this could be a fun little project for me Soon™, and I'd happily host it in the @sopel-irc org + publish it to PyPI. It's just not likely to become a new core plugin. Most of those are set to get moved into separate packages for 8.0, so this new one really should just start its life already standalone (regardless of which of us makes it).

**Comment by xnaas** [comment]
Just so it's documented here and not just in IRC chatlogs...it was mentioned that this isn't a core request. Should a repo open in the future for not-quite-core-but-sorta-kinda, I can move this there. 😄

**Comment by dgw** [comment]
I'm going to close this here in favor of sopel-irc/sopel-rainbow#1.
