### ISSUE TITLE
sopel --version fails with VersionConflict even though pip check passes

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel#2009]
### Description
Sopel --version fails on https://github.com/MirahezeBots/MirahezeBots/actions/runs/444179286 but pip check as show in https://github.com/MirahezeBots/MirahezeBots/actions/runs/444227506 reports no issue. Installed things shouldn't be any different.

### Reproduction steps
1. See action log in https://github.com/MirahezeBots/MirahezeBots/pull/380/checks?check_run_id=1609121656 for clearest

### Expected behavior
pip check should report the issue or it should work

### Logs
```
If applicable, add logs to help us figure out what's happening. Raw logs are
super helpful! Logs are usually found in ~/.sopel/logs, depending on your
configuration.
```
See links above
### Environment
- Sopel `.version`: 7.0.7
- Sopel installed via: pip
- Python version: 3.10-dev
- Operating system: Ubuntu
- IRCd `/version`: N/A - CLI fails
- Relevant plugins: N/A

### Notes
Could be an issue with a plugin as this build checks plugins are compatible with us as much but I'm a bit lost.

**Comment by dgw** [comment]
Why are you reporting bugs against Python 3.10-dev? We don't support unstable Python releases.

**Comment by RhinosF1** [comment]
> Why are you reporting bugs against Python 3.10-dev? We don't support unstable Python releases.

To be able catch things that may break in the future and see random errors that don't make sense so I can moan about them. Closing this as it looks a python issue.
