### ISSUE TITLE
Race condition when plugins want to access bot state after PART/QUIT

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#2017]
We should reprioritize some stuff in coretasks to avoid deleting things like Channel or User objects before plugin code has a chance to run. e.g. by the time a plugin receives a QUIT event, coretasks will have already deleted the user from `bot.users`.

All these events should probably be 'medium' priority, actually. Then the documentation can say plugins that want to do stuff before can choose 'low', and 'high' for after. Such plugin triggers should also run with `@plugin.thread(False)`. (@Exirel contributed to this info-dump via IRC.)

**Comment by Exirel** [comment]
I started a new chapter under "plugin", called "advanced tips & tricks". That'll be useful to put anything else that was asked 1,000,000 times on IRC.
