### ISSUE TITLE
translate: mangle is a bit useless due to rate limit

### ISSUE THREAD

**Issue by RhinosF1** [sopel-irc/sopel#2021]
### Description
Mangle ends up just saying 'None' a lot after using it more than once or twice within a minute or so due to what seems to be a rate limit

### Reproduction steps
1. Start a basic, stock sopel up
2. Use mangle a few times within a minute or so
3. It returns None

### Expected behavior
It either back off and respond when it is successful or error nicely. @rate (I think) might be useful here

### Logs
```
If applicable, add logs to help us figure out what's happening. Raw logs are
super helpful! Logs are usually found in ~/.sopel/logs, depending on your
configuration.
```

### Environment
- Sopel `.version`: lastest on PyPi
- Sopel installed via: pip 
- Python version: 3.7
- Operating system: Debian Buster
- IRCd `/version`: freenode's
- Relevant plugins: mangle

### Notes
https://cloud.google.com/translate/quotas

**Comment by dgw** [comment]
I had to spam a `.mangle` command over 20 times in a minute for it to stop responding.

Low priority issue, patches welcome, yadda-yadda.
