### ISSUE TITLE
Follow semver.org sopel release

### ISSUE THREAD

**Issue by eamanu** [sopel-irc/sopel#2022]
### The problem
I was looking to adopt sopel package on Debian. Before, try to adopt sopel, it's important
try to fix this open discussion [#943405](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=943405).

According to Antoine Beaupre position, also mine and other Debian Developers that I 
ask about this issue, would be great if sopel can follow the semver.org convetion for releases.

As you can see in the bug report, for a patch release sopel include big changes, that don't
have sense for a patch release. 

### The solution
Bug fixes, security fixes, etc use patch release. For other changes use major and minor release.

**Comment by RhinosF1** [comment]
Do we know if there have been concerns with sopel 7.0.x releases which are much more recent?

**Comment by Exirel** [comment]
I've many concerns about that, and I'll try to focus on some particular point referenced in both 943405 and 927481.

This bit, in particular:

> * Cleaned up code in instagram and unicode modules
> * Core modules now use bot.channels instead of deprecated bot.privileges

What makes that not suitable for a PATCH version exactly?

I checked PR merged in version [v6.6.4](https://github.com/sopel-irc/sopel/commits/v6.6.4), here they are:

* #1485 and #1494 are both bug-fixes, they don't change the behavior and they don't add new feature, they fix something that was broken in some cases
* #1484 and #1483 are code cleanup, and they don't add nor change any existing feature

These 4 PRs are all patches or bug-fixes: code cleanup, fixing inconsistent behavior without breaking anything. In my book, they conform to semver PATCH.

So you can understand that I'm quite surprised at the claim in the referenced bugs.

**Comment by Exirel** [comment]
Also, if Debian could stop using Sopel 6, witch we don't support anymore, that could be great.

**Comment by RhinosF1** [comment]
I'm confused as well. Replacing usage of deceprated code, not deceprating it, seems fine for a patch.

**Comment by eamanu** [comment]
Hi everyone, thanks for your response.

I forward the Debian Issue to here, maybe to have another opinion of the original issue author.

That I can interpret from the bug report, e.g. this line `Core modules now use bot.channels instead of deprecated bot.privileges` 
seems to have a new feature change, you are deprecating a feature and use a new one. 

But looking on the PR, seems to be normal PATCH change. As you note me.

Currently sopel was (Intent to) orphaned by the maintainer so my plan is updated and maintain it on Debian. That is
the reason about the 6.x.x version.

**Comment by Exirel** [comment]
> That I can interpret from the bug report, e.g. this line `Core modules now use bot.channels instead of deprecated bot.privileges`

I understand the confusion, but `bot.privileges`  has been deprecated in [Sopel 6.2.0 as per its changelog](https://sopel.chat/changelog/6.2.0/).

What that line means is that `sopel/coretasks.py` doesn't **read** `bot.privileges`, but it doesn't define it. However, in #1494, we ensure that `bot.privileges` and `bot.channels` are properly in sync, fixing potential bugs. As per the PR's description:

> The fact that they don't is a leftover bug from who knows when.

I think we follow Semver as best as possible. And by "we" I mean @dgw that always reminds everyone about backward compatibility, and he ensures that we are doing bug fixes only for patch version, and new features are added only in minor version.

**Comment by dgw** [comment]
And features are removed only in major versions.

I understand that Debian packages have a very high standard for maintaining stability between updates on the same OS release, but you should know that the Sopel project supports and updates only the most recent minor version, with rare exceptions. Things can and will break on older releases like 6.x.

**Comment by dgw** [comment]
Well, unless there's a recent example of Sopel failing to follow semver (and I've done my absolute best since taking over the project in 2018), I don't think anything actionable will come of leaving this issue open. We can always reopen if needed!

**Comment by eamanu** [comment]
thanks @dgw @Exirel @RhinosF1 for your support
