### ISSUE TITLE
Dependabot?

### ISSUE THREAD

**Issue by BlackWidowMovie0** [sopel-irc/sopel#2030]
### Dependabot?
There is no code-checker for PRs.

### Dependabot?
Install Dependabot on GitHub in the [GitHub Repository](https://github.com/sopel-irc/sopel).

See my repository for dependabot (access granted upon request).

IRC nick: blackwidowmovie0

**Comment by dgw** [comment]
> There is no code-checker for PRs.

We have 8 jobs on Travis CI that run for each PR and each push to a maintained branch (`master`, release maintenance), plus LGTM and Coveralls. We practically drown in "code-checker"s.

But regardless, Dependabot alerts _are_ enabled. You can't see them, but they're turned on.
