### ISSUE TITLE
Translated version of seen plugin

### ISSUE THREAD

**Issue by ronilaukkarinen** [sopel-irc/sopel#2031]
Is there any way to translate the built-in seen.py to other language? Cannot figure out any clear way to do that. Tried to copy it as a module but didn't work out. Not very experienced python developer here.

**Comment by Exirel** [comment]
I wanted to add i18n capability to Sopel for some times now, and I think it's doable. I created #2032 to track the whole effort required for that.

**Comment by dgw** [comment]
Closing in favor of global i18n tracking issue, #2032. Any plugins in core will be covered by that if/when it's worked on.
