### ISSUE TITLE
cli: tracebacks shown in too many places

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#2036]
Playing with Sopel's CLI tools on a fresh cloud instance, I found the following:

- [x] `sopel-config init`: mid-wizard, hitting <kbd>Ctrl</kbd>+<kbd>C</kbd> spits out a `KeyboardInterrupt` traceback
  - This should just abort creating the config, maybe with a "Config operation cancelled" message
- [x] `sopel-plugins` actions run when no config has been created yet spit out a `sopel.config.ConfigurationNotFound` traceback
  - These should catch and display a friendly error message only
  - ~~Things like `sopel-plugins show` should probably work for core plugins _at least_ even if no config exists?~~ NAK, meh. Just say there's no config, same as the others
- [x] `sopel-config list`: no output if no configs exist
  - Not a traceback, but might as well be addressed at the same time.
  - An empty list would be appropriate for output intended for consumption by a script, but we intend Sopel's CLI utilities to be used by humans. A helpful message suggesting to run `sopel-config init` might be good.

**Comment by Exirel** [comment]
> `sopel-config init`: mid-wizard, hitting Ctrl+C spits out a `KeyboardInterrupt` traceback

Aw indeed.

> Things like `sopel-plugins show` should probably work for core plugins _at least_ even if no config exists?

Yes but ultimately no, because a config can add extra plugin directories allowing to shadow an existing core plugin by another one, which would "show" a different plugin. 

> A helpful message suggesting to run `sopel-config init` might be good.

Ha yes, and we can keep it script-friendly by having that output on stderr instead of stdout.

**Comment by BlackWidowMovie0** [comment]
@dgw @Exirel You can assign to me, I'll see what I can do from my fork, but I'll remove myself if I feel it's too advanced for me.

**Comment by dgw** [comment]
@BlackWidowMovie0 Sure, take a crack at it.
