### ISSUE TITLE
Allow .help line limit to be set in config

### ISSUE THREAD

**Issue by MacFan4000** [sopel-irc/sopel#2045]
### The problem
We have found that in plenty of cases (such as wth .urlexclude and .urlallow) the help messages are said to be too long and then are subsequently sent in a PM. Looking at the messages, the help text isn't that long, and it is because in the code there is a blank line between sentences.

### The solution
Allow the help text length threshold to set in config. This would allow users to set it to a value that is good for them.

### Alternatives
You could also increase the limit of fix the individual cases, but it's probably better to allow users to control the limit rather then setting a hard unchangeable limit in the code.

### Notes
There is currently an unchangeable hard limit of 3 lines. (https://github.com/sopel-irc/sopel/blob/0cd434af8aef8e5122c49790f27612085c30d07c/sopel/modules/help.py#L268)

**Comment by Exirel** [comment]
I might want to implement that on the [sopel-help](https://github.com/sopel-irc/sopel-help/) plugin, that will replace the built-in help plugin at some point.

**Comment by dgw** [comment]
@MacFan4000 The built-in help plugin is going to be removed in a few releases. Would be _help_ful if you could confirm if the same issue applies to [the standalone help plugin](https://github.com/sopel-irc/sopel-help). If so, I'll transfer the issue.

**Comment by MacFan4000** [comment]
It does, as that's what our bot using, and both plugins have the same hard limit of 3

btw I have also now opened sopel-irc/sopel-help#2

**Comment by dgw** [comment]
> btw I have also now opened [sopel-irc/sopel-help#2](https://github.com/sopel-irc/sopel-help/issues/2)

Great, we'll close this and leave it for the newer plugin. 😸
