### ISSUE TITLE
isup responds twice

### ISSUE THREAD

**Issue by MacFan4000** [sopel-irc/sopel#2061]
### Description
when I run .isup or .isupinsecure, the bot responds twice. first is the error (if any) then it says that the site is up
### Reproduction steps
1. setup a sopel bot using the master branch.
2. in the irc channel run .isup with some url that is down
3. it responds twice

### Expected behavior
only responds with an error or else up, not up and error

### Environment
- Sopel `.version`: [e.g. 7.0.0 or d416e19] master branch
- Sopel installed via: [apt, pip, `setup.py install`, source, ?] source
- Python version: [e.g. 3.6.9] 3.7
- Operating system: [e.g. Debian 10] debian buster
- IRCd `/version`: [e.g. InspIRCd 3.0.1] freenode
- Relevant plugins: [adminchannel, weather, custom\_thing.py, ?] isup

### Notes
seems to be because in https://github.com/sopel-irc/sopel/blob/master/sopel/modules/isup.py#L89 none of the except statements return and so the bot.say for "website is up" is always executed.

**Comment by MacFan4000** [comment]
15:09 <+MacFan4000> .isupinsecure https://bots1.mirahezebots.org
15:09 <+MirahezeBotBeta> [isup] https://bots1.mirahezebots.org looks down to me (SSL error). Try using `.isupinsecure`.
15:09 <+MirahezeBotBeta> [isup] https://bots1.mirahezebots.org looks fine to me.

**Comment by dgw** [comment]
> * Sopel `.version`: [e.g. 7.0.0 or [d416e19](https://github.com/sopel-irc/sopel/commit/d416e1966e4e2b74cce49b8f100ef68fb07a4731)] master branch

The specific commit would be helpful, for bisecting the history.

**Comment by MacFan4000** [comment]
https://github.com/MirahezeBots/sopel/commit/8dbce960d1ef1f65b2c1560cbd4fa8d6f5aa1361 this commit, later commits on that fork are just ci modifications

**Comment by dgw** [comment]
Seems to have been caused by 5af0eea249238485d70c8e14743358a50115b0f4. I will investigate further.

**Comment by dgw** [comment]
Indeed, adding the missing `return` statements fixes it. I'll see if I can resurrect my old forgotten branch with more tests for this plugin on top of that patch, then PR both together.

**Comment by Exirel** [comment]
If you don't have time I'll do that by the end of the WE I think.

**Comment by dgw** [comment]
@Exirel If you get around to building tests before I find my footing, feel free to commit them on #2063's branch.
