### ISSUE TITLE
Support 2-pronoun sets in the pronoun module 

### ISSUE THREAD

**Issue by eliocamp** [sopel-irc/sopel#2068]
### The problem

Setting pronouns in the pronouns module can be unintuitive because the bot accepts either a 1-pronoun "object" command (`.setpronouns she`) or a long 5-pronouns "subject/object/possessive-determiner/possessive-pronoun/reflexive" commnad (`.setpronouns she/her/her/hers/herself`). However, in my experience most people are used to the 2-pronoun convention of "subject/object" `.setpronouns she/her`). 

### The solution

Supporting 2-word version of pronouns. 

### Alternatives

An alternative would be to improve the message for unrecognised pronoun sets by adding explicit instructions to use either 1- or 5-pronoun sets.

**Comment by eliocamp** [comment]
(I think this might be a relatively easy fix: just add the two-word combos to the list on [these lines](https://github.com/sopel-irc/sopel/blob/master/sopel/modules/pronouns.py#L17-L30). 

If this is a desirable feature, I can send a PR in that fashion.

**Comment by Exirel** [comment]
> If this is a desirable feature, I can send a PR in that fashion.

Yes it is, and I think your idea is a good one: adding all the variations (`he/him`, `she/her`) in the mapping should do it, I think.

**Comment by eliocamp** [comment]
We are going to use Sopel as our conference bot (we are using IRC as chat platform). Is there a timeline for this change to be merged and a new version to be published?

**Comment by dgw** [comment]
No. If it's time-critical for you, please run a fork.

**Comment by eliocamp** [comment]
Thanks. Good to know :)

**Comment by dgw** [comment]
btw @eliocamp I'm hoping we can get 7.1 out this week, ahead of the CI platform changes that motivated #2073. Depending on when your conference is, you might be able to skip using a fork. :)

**Comment by eliocamp** [comment]
Fantastic! Thanks.
