### ISSUE TITLE
.blocks command is confusing.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#2101]
[10:38am] BetaAnt> .blocks Bender
10:38AM URL> BetaAnt: I could not figure out what you wanted to do.
[10:38am] BetaAnt> .help blocks
10:38AM URL> Manage Sopel's blocking features.    See [ignore system
          documentation]({% link _usage/ignoring-people.md %}).
[10:39am] BetaAnt> blah
[10:39am] BetaAnt> .blocks list
10:39AM URL> BetaAnt: I could not figure out what you wanted to do.
[10:39am] BetaAnt> .blocks list Bender
10:39AM URL> BetaAnt: Invalid input for displaying blocks.
[10:39am] BetaAnt> .blocks add Bender Bender
10:39AM URL> BetaAnt: Invalid format for adding a block. Try: .blocks add
          (nick|hostmask) sopel
[10:40am] BetaAnt> .blocks add Bender sopel
10:40AM URL> BetaAnt: Invalid format for adding a block. Try: .blocks add
          (nick|hostmask) sopel
[10:41am] * BetaAnt doesn't understand
          https://sopel.chat/usage/ignoring-people/ :(
10:41AM URL> [url] Making Sopel ignore people - Sopel | sopel.chat
[10:41am] BetaAnt> .version
10:42AM URL> [version] Sopel v7.1.0 | Python: 3.9.5

I just wanted to block Bender name because he's an old rbot. What am I doing wrong? I don't remember this being difficult many years ago with Willie.           https://sopel.chat/usage/ignoring-people/'s instructions are confusing,. Thank you for reading and hopefully answering soon. :)

**Comment by Exirel** [comment]
Did you tried `.blocks add nick Bender` like the doc said?

**Comment by antdude** [comment]
Exirel: Thank you for the quick answer! I thought nick was nickname to use. Closing! :D
