### ISSUE TITLE
URL module doesn't auto-title urls by default

### ISSUE THREAD

**Issue by MacFan4000** [sopel-irc/sopel#2107]
### Description
I found that after upgrading to Sopel 7.1 the bot wasn't automatically posting titles for URLS, and it wasn't until I explicitly set it in the config that it started working. https://github.com/sopel-irc/sopel/blob/7.1.x/sopel/modules/url.py#L58 implies that it defaults to true, but that doesn't seem to hold true.

### Reproduction steps
1. don't have enable_auto_title set at all in the config
4. Post a URL in a channel with the bot, and find that the title isn't posted by the bot

### Expected behavior
What did you expect to happen instead?
By default title is automatically posted.

### Environment
- Sopel `.version`: [e.g. 7.0.0 or d416e19] 7.1
- Sopel installed via: [apt, pip, `setup.py install`, source, ?] pip
- Python version: [e.g. 3.6.9] 3.7
- Operating system: [e.g. Debian 10] debian buster
- IRCd `/version`: [e.g. InspIRCd 3.0.1] Libera Chat
- Relevant plugins: [adminchannel, weather, custom\_thing.py, ?] URL

**Comment by dgw** [comment]
Already fixed by #2084, due out in 7.1.1 probably this weekend.

You located the workaround, I see, but I'm going to pin this issue until release so here's a config snippet anyway:

```ini
[url]
enable_auto_title = true
```
