### ISSUE TITLE
More than one owners in ~/.sopel/default.cfg doesn't work.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#2109]
In its [core] section, I have:

```
owner =
              Ant
              BetaAnt
```

Both Ant and BetaAnt (from 2 different ISPs) are the names (tabs before them). IRC client (BitchX) /msg sopel .quit doesn't work from both accounts. Shouldn't this work?  It will work if I only have one name. Or do I have this set up wrong?

I am copying the formatting for:
```
nick_blocks =
        Flexo
        Bender
```

**Comment by dgw** [comment]
You can't just decide that any arbitrary config value should be a list. `owner` is a single nick, nothing more. See https://sopel.chat/docs/config.html#sopel.config.core_section.CoreSection.owner and https://sopel.chat/docs/configuration.html#owner-admins.

**Comment by antdude** [comment]
Thanks. After reading https://sopel.chat/docs/configuration.html#owner-admins, I tried:

owner = Ant
admins = BetaAnt

Ant (ant@0::1) worked, but not BetaAnt (ant@someaddress.com).  Both have same nickname. Am I missing something?

**Comment by dgw** [comment]
> Am I missing something?

I certainly am. The `owner` and `admins` config values take _only_ nicknames, and I don't know what you've done with the hostmasks.

**Comment by antdude** [comment]
Um, hostmasks? What are those? Are they required?

**Comment by dgw** [comment]
No. If you have:

```ini
owner = Ant
admins = BetaAnt
```

That should work, unless BetaAnt tries to use an owner-only command.

I don't know what you meant by "Both have same nickname."

**Comment by antdude** [comment]
When I do /w in BitchX:

BetaAnt     ~ant@someaddress.com (Ant)
Ant         ~ant@0::1 (Eciton burchelli)

**Comment by dgw** [comment]
What does that have to do with Sopel? I don't use that client and have no idea what `/w` is supposed to do.

**Comment by antdude** [comment]
It shows the addresses connected from. Is that the hostmask stuff to get from?

**Comment by dgw** [comment]
No. Sopel doesn't want hostmasks for its owner or admins. Unless you can explain what is not working as expected, I will consider this question answered by https://github.com/sopel-irc/sopel/issues/2109#issuecomment-864492586.

**Comment by antdude** [comment]
Oh, hmm.
