### ISSUE TITLE
CHANTYPES not used in `Identifier.is_nick()`

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#2115]
Some networks may have unusual channel types beyond the static list in `tools._channel_prefixes`. Beyond that, there is always the possibility that an unusual CHANTYPES, PREFIX, and/or STATUSMSG combination could make `Identifier.is_nick()` erroneously consider a channel to be a nickname.

For example: Given `CHANTYPES=+& PREFIX=(ov)@#`, Sopel's current code would consider `+channel` to be a nickname, NOT a channel.

### Notes

Previously attempted (in a very hacky way) at #1963. Any proper solution should work for both this and #1886.

**Comment by Exirel** [comment]
Fixed by #2236.
