### ISSUE TITLE
"You[apos]re" result from Sopel's URL parser

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#2203]
### Description
"You[apos]re" is shown for "You're" in a https://matrix.to/#/#element-community-testing:matrix.orghttps://matrix.to/#/#element-community-testing:matrix.org link.

### Reproduction steps
1. Copy and paste https://matrix.to/#/#element-community-testing:matrix.orghttps://matrix.to/#/#element-community-testing:matrix.org for Sopel bot to parse.
2. See Sopel's parsed URL results for "You[apos]re".

### Expected behavior
I should see "You're" instead of "You[apos]re".

### Logs
I don't see anything interesting in ~/.sopel/logs?

### Environment
- Sopel `.version`: 7.1.5
- Sopel installed via: pip
- Python version: 3.9.7
- Operating system: 64-bit Fedora v33
- IRCd `/version`: ircd-ratbox-3.0.8(20121231_3-27427)
- Relevant plugins: mostly defaults

### Notes
Chat log from my IRC client in my Debian Jessie v8 box:
...
06:14PM Mousey> but
          https://matrix.to/#/#element-community-testing:matrix.orghttps://matrix.to/#/#element-community-testing:matrix.org
06:14PM URL> [url] You[apos]re invited to talk on Matrix | matrix.to
06:14PM Mousey> but https://matrix.to/#/#element-community-testing:matrix.org is for
          community testing!
06:14PM URL> [url] You[apos]re invited to talk on Matrix | matrix.to
[06:14pm] * RecoveryAnty upvotes without watching.
[06:15pm] RecoveryAnty> weird
[06:15pm] RecoveryAnty> You[apos]re
[06:15pm] RecoveryAnty> Can't even show apostrophe?
06:15PM Mousey> that would be hexchat's fault
[06:15pm] RecoveryAnty> Uh...
[06:16pm] RecoveryAnty>
          https://matrix.to/#/#element-community-testing:matrix.orghttps://matrix.to/#/#element-community-testing:matrix.org
06:16PM URL> [url] You[apos]re invited to talk on Matrix | matrix.to
[06:16pm] RecoveryAnty> nope
[06:16pm] RecoveryAnty> BitchX here.
[06:16pm] RecoveryAnty> Sopel's fault I bet.
...

**Comment by dgw** [comment]
This isn't _really_ Sopel's fault: Anyone relying on the Python standard library resources for dealing with HTML character entity references would have had this same problem until newer tools became available in Python 3.3 and 3.4.

Sopel's HTML entity functions (which `url.py` uses) date back to before those came out, so they use what was available at the time. It seems that `apos` wasn't a recognized HTML entity name back then, but it _is_ part of the newer [HTML5 list](https://html.spec.whatwg.org/multipage/named-characters.html#named-character-references) that modern Python uses in those new stdlib tools.

Modern _Sopel_ certainly can use the newer tools if available. I'll work on a patch to do that for 7.1.6.

**Comment by antdude** [comment]
Thanks dgw. :)

**Comment by dgw** [comment]
Closing with merge of #2204.

**Comment by antdude** [comment]
Thank you, dgw! :)
