### ISSUE TITLE
Python3.8: ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by ronilaukkarinen** [sopel-irc/sopel#2248]
### Description

Running sopel with python 3.8.0 produces following error:

I have trried everything. All the packages are installed.

```
$ cd $HOME/.sopel && sopel
Sopel 7.1.7 (running on Python 3.8.0)
https://sopel.chat/

Loaded config file: /home/rolle/.sopel/default.cfg
Unexpected error in bot setup
Traceback (most recent call last):
  File "/home/rolle/.local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 338, in dbapi
    from pysqlite2 import dbapi2 as sqlite
ModuleNotFoundError: No module named 'pysqlite2'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rolle/.local/bin/sopel", line 11, in <module>
    load_entry_point('sopel', 'console_scripts', 'sopel')()
  File "/home/rolle/sopel-7.1.7/sopel/cli/run.py", line 714, in main
    return command(opts)
  File "/home/rolle/sopel-7.1.7/sopel/cli/run.py", line 671, in command_legacy
    ret = run(settings, pid_file_path)
  File "/home/rolle/sopel-7.1.7/sopel/cli/run.py", line 74, in run
    p = bot.Sopel(settings, daemon=daemon)
  File "/home/rolle/sopel-7.1.7/sopel/bot.py", line 111, in __init__
    self.db = SopelDB(config)
  File "/home/rolle/sopel-7.1.7/sopel/db.py", line 171, in __init__
    self.engine = create_engine(self.url, pool_recycle=3600)
  File "/home/rolle/.local/lib/python3.8/site-packages/sqlalchemy/engine/__init__.py", line 443, in create_engine
    return strategy.create(*args, **kwargs)
  File "/home/rolle/.local/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py", line 87, in create
    dbapi = dialect_cls.dbapi(**dbapi_args)
  File "/home/rolle/.local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 343, in dbapi
    raise e
  File "/home/rolle/.local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/pysqlite.py", line 341, in dbapi
    from sqlite3 import dbapi2 as sqlite  # try 2.5+ stdlib name.
  File "/usr/local/lib/python3.8/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.8/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

### Reproduction steps
1. Install from official release
2. Run sopel

Commands used:

1. wget https://github.com/sopel-irc/sopel/archive/refs/tags/v7.1.7.tar.gz
2. tar -xvf v7.1.7.tar.gz
3. cd $HOME/sopel-7.1.7
4. pip3.8 install --user -e .
5. pip3.8 install --user -r requirements.txt
7. pip3.8 install --user lxml schedule spacy
8. pip3.8 install --user chatterbot
9. pip3.8 install --user pysqlite3
10. pip3.8 install --user db-sqlite3
11. sudo apt install libsqlite3-dev
12. cd $HOME/.sopel && sopel

### Expected behavior
To be able to run sopel.

### Logs
```
If applicable, add logs to help us figure out what's happening. Raw logs are
super helpful! Logs are usually found in ~/.sopel/logs, depending on your
configuration.
```

### Environment
- Sopel `.version`:  7.1.7
- Sopel installed via: Tarball release
- Python version: 3.8.0
- Operating system: Ubuntu 20.04

### Side notes

On python3.7 there's no problems with exactly the same commands except for `pip3.7`.

**Comment by dgw** [comment]
I don't understand why you're installing `pysqlite3` or `db-sqlite3`. Sopel and ChatterBot both require SQLAlchemy<1.4, and you shouldn't need anything else to use SQLite databases. Python 3.8 [has `sqlite3` DBAPI-2.0](https://docs.python.org/3.8/library/sqlite3.html) built into the standard library.

Additionally, `db-sqlite3` hasn't been updated since 2013 and you _really_ shouldn't install or need such old packages on modern Python.

**Comment by ronilaukkarinen** [comment]
Yeah it actually doesn't let it install, I was just testing if it fixes the problem. But it doesn't. With clear reinstall the problem persists on 3.8. On 3.7 no problems.

**Comment by half-duplex** [comment]
I also confirmed this worked fine for me, on Ubuntu 20.04 w/ its latest python (3.8.10).
Installing Sopel through pypi is going to be easier to maintain, unless you need to edit the source code.
```
sudo apt install python3-pip
pip3 install --user -U requests # system python-requests is too old
pip3 install --user sopel
~/.local/bin/sopel
```

This also worked fine, in the same environment:
```
sudo apt install python3-pip
wget https://github.com/sopel-irc/sopel/archive/refs/tags/v7.1.7.tar.gz
tar axvf v7.1.7.tar.gz
cd sopel-7.1.7
pip3 install --user -U requests
pip3 install --user -e .
~/.local/bin/sopel
```

Alternatively, you can install in a virtualenv:
```
sudo apt install python3-virtualenv
virtualenv -p python3 sopel-venv
source sopel-venv/bin/activate
pip install sopel # or pip install -e path/to/sopel-v7.1.7
sopel
```
