### ISSUE TITLE
URL handler called multiple times for multiple URLs in single message

### ISSUE THREAD

**Issue by timwoj** [sopel-irc/sopel#2258]
### Description

Plugins with URL handlers will see that handler called multiple times if there are multiple URLs in messages received from the server.

### Reproduction steps

I have a simple plugin such as 
```
from sopel import plugin
import logging
LOGGER = logging.getLogger(__name__)

@plugin.url(r'(http|https|ftp)')
def on_url(bot, trigger):
   LOGGER.info(f'on_url handler {trigger.plain}')
   for trigger_url in trigger.urls:                                                                
        LOGGER.info(trigger_url)                                                                    
```

If I send the message `http://test.org http://abc.com` from a channel the bot is joined to, I get this in the log:

```
[2022-02-19 21:26:56,312] sopel.modules.url_test  INFO     - on_url handler https://test.com https://abc.org
[2022-02-19 21:26:56,312] sopel.modules.url_test  INFO     - on_url handler https://test.com https://abc.org
[2022-02-19 21:26:56,313] sopel.modules.url_test  INFO     - https://test.com
[2022-02-19 21:26:56,315] sopel.modules.url_test  INFO     - https://test.com
[2022-02-19 21:26:56,318] sopel.modules.url_test  INFO     - https://abc.org
[2022-02-19 21:26:56,319] sopel.modules.url_test  INFO     - https://abc.org
```

### Expected behavior
I'd expect the logs to only have one call to the `on_url` handler, given that the trigger object contains all of the URLs in the message.

### Environment
- Sopel `.version`: 6e56fc6bce71ebfa15247332b7aa645033bdfb1a (working on a fork with some custom plugins, this is the last common commit)
- Sopel installed via: `pip`
- Python version: 3.10.2
- Operating system: ArchLinux
- IRCd `/version`: UnrealIRCd-5.0.4
- Relevant plugins: custom url_test.py

**Comment by dgw** [comment]
This is by design: The `@plugin.url` decorator is meant to dispatch every matching callable for each matched URL, which is exactly the behavior you describe, and pass to it via `trigger` the exact URL that matched.

For what you're trying to do to work as intended, you need the pattern to match the full URL, not just the protocol, and access it via `trigger.group(0)` instead of `trigger.urls`:

```py
"""Test plugin located at ~/.sopel/plugins/url_test.py"""
from sopel import plugin, tools

LOGGER = tools.get_logger('url_test')

@plugin.url(r'(?:http|https|ftp).*')  # wildcard ensures capturing the whole link
def on_url(bot, trigger):
    LOGGER.info(f'on_url handler {trigger.plain}')
    LOGGER.info(f'dispatched URL: {trigger.group(0)}')
```

The output is then:

```
[2022-02-19 22:47:15,735] sopel.externals.url_test INFO     - on_url handler https://example.com https://example2.com
[2022-02-19 22:47:15,735] sopel.externals.url_test INFO     - dispatched URL: https://example.com
[2022-02-19 22:47:15,736] sopel.externals.url_test INFO     - on_url handler https://example.com https://example2.com
[2022-02-19 22:47:15,736] sopel.externals.url_test INFO     - dispatched URL: https://example2.com
```

Use of a non-capturing group is immaterial, but can improve performance if you don't need the result of that group saved.

Note that since I didn't put this plugin into Sopel's core plugins folder, I had to use the "public" way of getting a logger (`tools.get_logger`). If you're set on maintaining a fork, you'll have to ignore that change; I included my sample code as-is so it would accurately reflect exactly what I ran and tested.

**Comment by half-duplex** [comment]
@timwoj To be clear, the intended way of using Sopel is not to clone this repo and put your custom plugins into it, it is to install Sopel using `pip` and put your custom plugins in its search path (or entrypoints). I would recommend against maintaining a fork just for that.

**Comment by timwoj** [comment]
> This is by design: The @plugin.url decorator is meant to dispatch every matching callable for each matched URL, which is exactly the behavior you describe, and pass to it via trigger the exact URL that matched.

Huh. I'm curious why the API is provided to retrieve all of the URLs as an enumerable list is provided then. Either way, I reworked that bit of my code to match the above and everything seems fine now. I'll close out this issue.

> To be clear, the intended way of using Sopel is not to clone this repo and put your custom plugins into it, it is to install Sopel using pip and put your custom plugins in its search path (or entrypoints). I would recommend against maintaining a fork just for that.

Awesome. I ended up reorganizing everything and got the entry point version all working.

**Comment by dgw** [comment]
> I'm curious why the API is provided to retrieve all of the URLs as an enumerable list

Any callable will get that, even if it's not a `@plugin.url` callable. Sopel tries to give all the tools to everybody where possible, and let plugin developers use what they want to use.

If you wanted to have your plugin trigger only once, but not for lines that don't contain a link, you can use `@plugin.search` instead and then something like your original approach to enumerate all links Sopel found in the line:

```py
"""Test plugin located at ~/.sopel/plugins/url_test.py"""
from sopel import plugin, tools

LOGGER = tools.get_logger('url_test')

@plugin.search(r'(https?|ftp):')
def on_url(bot, trigger):
   LOGGER.info(f'on_url handler {trigger.plain}')
   for trigger_url in trigger.urls:                                                                
        LOGGER.info(trigger_url)
```

See also: [the `search` decorator](https://sopel.chat/docs/plugin/decorators.html#sopel.plugin.search)'s documentation.
