### ISSUE TITLE
config: FilenameAttribute doesn't handle quotes well

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#2263]
### Description
If the value of a `FilenameAttribute` set in the config file is quoted, it silently creates a mess.

### Reproduction steps
1. Set `core.logdir = "/path/to/logs"`
2. Run Sopel
3. Sopel quietly creates a silly directory tree inside `$HOMEDIR`:
```
$ tree ~/.sopel
/home/dgw/.sopel
├── "
│   └── path
│       └── to
│           └── logs"
│               ├── default.error.log
│               ├── default.exceptions.log
│               ├── default.raw.log
│               └── default.sopel.log
...
```

### Expected behavior
Even though quotes aren't required in Sopel's config file, they should be sensibly handled.

### Environment
- Sopel `.version`: current `master`, aca10553da2a996aaaa4051741fae6fb7e6c4940
- Sopel installed via: `-e .` @ above commit
- Python version: 3.8, 3.9
- Operating system: Ubuntu 20.04 (WSL)

### Notes
This is a leftover todo from #1959, where I updated the docs but didn't make any code changes related to this.

**Comment by half-duplex** [comment]
Can we just switch to TOML >.>

**Comment by dgw** [comment]
Definitely not for 8.0.

**Comment by Exirel** [comment]
As written in the doc:

> Quoting a value unnecessarily can lead to unexpected behavior such as an absolute pathname being interpreted as relative to Sopel’s home directory.

**Comment by dgw** [comment]
Yes @Exirel, that's what I added in #1959. But in the interest of user-friendliness (Sopel is supposed to be "simple", remember) I think we should add sensible behavior like stripping quotes (and logging a warning), unless there are reasonable use cases where someone might intentionally want a folder named `"`.
