### ISSUE TITLE
Multiple irc connection configuration

### ISSUE THREAD

**Issue by daomengRen** [sopel-irc/sopel#2347]
### Requested Feature

Support to configure multiple irc connections under the same configuration file, each connection is independent, they have their own plug-ins and channels, so starting a Sopel can realize different irc connections, different channels and plug-in configurations. Or, can someone tell me if this is possible in the current version, thanks

**Comment by dgw** [comment]
By design, for multiple connections with independent sets of plugins and channels, you create a config file for each and start multiple instances of Sopel.
