### ISSUE TITLE
docs: include how-to information for getting help/reporting bugs

### ISSUE THREAD

**Issue by SnoopJ** [sopel-irc/sopel#2395]
### Requested Feature

It's common for errors reported in a reply by a Sopel instance to be inadequate for debugging what went wrong, so that the first step in getting a user the assistance they need is helping them locate and share the logs for their instance. It would be handy to have more of a formal "how to get help" narrative to make the experience more consistent for both users and helpers, and there may be other common advice/procedures that could be laid out in a document like that.

### Notes

There's [some notes in `CONTRIBUTING.md`](https://github.com/sopel-irc/sopel/blob/master/CONTRIBUTING.md?plain=1#L1-L12) and [some information about logger configuration in the docs](https://sopel.chat/docs/configuration.html#logging) that are good starting points for this request.

Some 'prior art' in other projects:
* The Littlest JupyterHub's [Looking at Logs](https://tljh.jupyter.org/en/latest/troubleshooting/logs.html)
* PyInstaller's [When Things Go Wrong](https://pyinstaller.org/en/stable/when-things-go-wrong.html)

**Comment by dgw** [comment]
The FAQ added in #2533 (https://unstable.docs.sopel.chat/faq) covers this topic.

**Comment by dgw** [comment]
Let's say this should stay open until the more explicit fix is merged.
