### ISSUE TITLE
cli: `--quiet` arg doesn't do anything

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#2397]
### Description

Between 6.x and 7.0, when the CLI and logging stuff was rewritten, it appears that the `--quiet` argument's function got lost. It's still parsed and stored in the options when `argparse` processes the command line for `sopel start`, `sopel stop`, etc., but the `opts.quiet` flag is never used.

Even in the current `master` branch, using `sopel.cli.run.command_start()` as an example (the other subcommands are similar), `opts` is passed to the `get_configuration()` helper and then the only remaining reference to it is here:

https://github.com/sopel-irc/sopel/blob/94065d7fb2aaafb946c98e4542a5fc7dbfb4a499/sopel/cli/run.py#L327-L330

However, note the following `run_script.py` code from 6.x, which uses `OutputRedirect` (a now-unused class that was just formally marked deprecated in #2385):

https://github.com/sopel-irc/sopel/blob/592735d4ea61f61212a9e5d1ae5f0a90c6f07983/sopel/run_script.py#L152-L153

It looks like this goes all the way back to #1678, and has therefore been broken since 7.0.0. That's when the output redirection was replaced by a setup function (`sopel.logger.setup_logging()`) that takes only the bot's Config into account and does not receive any arguments from the CLI.

### Reproduction steps

1. Run `sopel start --quiet`
2. The bot prints output to the terminal

### Expected behavior

The bot should not print output to the terminal; help text for `--quiet` says that it should "Suppress all output".

### Notes

It's funny that we have tests to make sure the `--quiet` argument is parsed and present in the resulting `opts` object, but never got around to a functional test that actually checks whether it quiets the bot's output.

I guess how long it took to discover this shows you just how few people actually use `--quiet`… including me. (#1678 was merged over 3 years ago.) Before tonight, I have no idea when or even if I've ever used that flag.

In the end, we need to either _fix it_ in 8.0 or _remove it entirely_.

### Sopel version

94065d7fb2aaafb946c98e4542a5fc7dbfb4a499

### Installation method

`pip install`

**Comment by Exirel** [comment]
I'm for removing it. If someone wants to suppress output, they can do `sopel start >/dev/null 2>&1`.
