### ISSUE TITLE
help: invalid pattern in Python 3.11

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#2403]
The old built-in `help` plugin uses a global regex flag in the middle of a pattern, which is no longer allowed as of Python 3.11:

https://github.com/sopel-irc/sopel/blob/81b5e1180f2ac331263894323b7c52c8f7ab9825/sopel/modules/help.py#L246

Doing this [was deprecated in Python 3.6](https://docs.python.org/3.6/whatsnew/3.6.html#id5) (scroll to `re` header, if the link fragment breaks).

## The workaround is to install [`sopel-help`](https://pypi.org/project/sopel-help/) from PyPI.

It is [an official replacement](https://github.com/sopel-irc/sopel-help), extracted from the core bot package and released separately for easier updates. We intend to keep it usable with the older 7.1.x Sopel versions until Sopel 8 is released.

**Comment by antdude** [comment]
Thanks, dgw. Is it possible to see this URL without Sopel to see what it looks like in a text web browser (lynx, eLinks, etc.) since I SSH2 into my friend's Fedora box?

**Comment by dgw** [comment]
@antdude Surely you meant to post that on #2402?

**Comment by antdude** [comment]
@dgw. Oops! Dang typos. Thanks. :(
