### ISSUE TITLE
Sopel should respond in-kind to triggers sent with STATUSMSG

### ISSUE THREAD

**Issue by SnoopJ** [sopel-irc/sopel#2440]
### Description

Sopel supports responding to a `PRIVMSG` that uses the [`STATUSMSG`](https://modern.ircdocs.horse/#statusmsg-parameter) feature, and used to respond in the same manner, but this behavior has changed and the bot now responds directly in a channel. For instance, a message sent to `+#sopel` would previously cause a response to be sent to `+#sopel`, but now sends a response to `#sopel`.

### Reproduction steps

See below

### Expected behavior

The old behavior makes sense, but may have been a bit of a coincidence. The bot should respond in-kind to match the style of communication that users are using. It would be confusing for instance for non-voiced users to see a response to a command that was sent only to the voiced users in a channel.

### Relevant logs

In the below sample, `terribot` (running Sopel 7.1.9) responds to my messages in-kind, but `testibot` (running b5eba03) responds in the channel

```shell
7:55 -- Msg -> +##terribot-testing: https://butt.holdings/
17:55 -- Msg:+(terribot): [url] Hold on to your butts! | butt.holdings
17:55 <+testibot> [url] Hold on to your butts! | butt.holdings
17:56 -- Msg -> +##terribot-testing: !version
17:56 -- Msg:+(terribot): [version] Sopel v7.1.9 | Python: 3.9.9
17:56 <+testibot> [version] Sopel v8.0.0.dev0 | Python: 3.7.16 | Commit: b5eba03ce74baae36e3456ac938686fb23f5671b
```

### Notes

Tested on Libera.chat which advertises `STATUSMSG=@+`

### Sopel version

master

### Installation method

`pip install`

### Python version

3.7.16

### Operating system

Ubuntu 20.04

### IRCd

solanum-1.0-dev(20221103-ed775e9b)

### Relevant plugins

N/A

**Comment by dgw** [comment]
This could be considered the "spaghetti squash" I was afraid of in https://github.com/sopel-irc/sopel/pull/2370#pullrequestreview-1237607381

I think the sanest fix would be to include the `Trigger`'s [`status_prefix`](https://github.com/sopel-irc/sopel/blob/b5eba03ce74baae36e3456ac938686fb23f5671b/sopel/trigger.py#L341) in the [destination logic](https://github.com/sopel-irc/sopel/blob/b5eba03ce74baae36e3456ac938686fb23f5671b/sopel/bot.py#L1282-L1283) within `SopelWrapper`. (That's one example, but almost every method has it.)

**Comment by SnoopJ** [comment]
This appears to be caused by [deliberate stripping of the `STATUSMSG` prefix](https://github.com/sopel-irc/sopel/blob/b5eba03ce74baae36e3456ac938686fb23f5671b/sopel/trigger.py#L251-L252), if I remove that, I get the expected behavior.

> I think the sanest fix would be to include the `Trigger`'s [`status_prefix`](https://github.com/sopel-irc/sopel/blob/b5eba03ce74baae36e3456ac938686fb23f5671b/sopel/trigger.py#L341) in the [destination logic](https://github.com/sopel-irc/sopel/blob/b5eba03ce74baae36e3456ac938686fb23f5671b/sopel/bot.py#L1282-L1283) within `SopelWrapper`

This sounds reasonable to me

**Comment by dgw** [comment]
> This appears to be caused by [deliberate stripping of the `STATUSMSG` prefix](https://github.com/sopel-irc/sopel/blob/b5eba03ce74baae36e3456ac938686fb23f5671b/sopel/trigger.py#L251-L252)

The prefix must be removed because if it's left there, things like `trigger.sender.is_nick()` return(ed) wrong values for STATUSMSG triggers.

It's correct to consider the status prefix as separate from the Identifier. We just forgot to make use of it later 😅

**Comment by Exirel** [comment]
Oh right...

@SnoopJ could you provide the IRC raw logs for your example? This would be a great base for a non-regression test.

Also, I'd love to fix this bug myself, given that I think it's my fault.

**Comment by SnoopJ** [comment]
> Also, I'd love to fix this bug myself, given that I think it's my fault.

Fine by me! Below is the patch I mentioned on IRC:

<details><summary>clicky clicky for patch</summary>

```diff
diff --git a/sopel/bot.py b/sopel/bot.py
index 5354602b..310aab73 100644
--- a/sopel/bot.py
+++ b/sopel/bot.py
@@ -1256,6 +1256,10 @@ class SopelWrapper:
     def __setattr__(self, attr, value):
         return setattr(self._bot, attr, value)
 
+    @property
+    def default_destination(self) -> Optional[identifiers.Identifier]:  # actually optional?
+        return (self._trigger.status_prefix or "") + self._trigger.sender
+
     def say(self, message, destination=None, max_messages=1, truncation='', trailing=''):
         """Override ``Sopel.say`` to use trigger source by default.
 
@@ -1280,7 +1284,7 @@ class SopelWrapper:
 
         """
         if destination is None:
-            destination = self._trigger.sender
+            destination = self.default_destination
         self._bot.say(self._out_pfx + message, destination, max_messages, truncation, trailing)
 
     def action(self, message, destination=None):
@@ -1298,7 +1302,7 @@ class SopelWrapper:
             :meth:`sopel.bot.Sopel.action`
         """
         if destination is None:
-            destination = self._trigger.sender
+            destination = self.default_destination
         self._bot.action(message, destination)
 
     def notice(self, message, destination=None):
@@ -1316,7 +1320,7 @@ class SopelWrapper:
             :meth:`sopel.bot.Sopel.notice`
         """
         if destination is None:
-            destination = self._trigger.sender
+            destination = self.default_destination
         self._bot.notice(self._out_pfx + message, destination)
 
     def reply(self, message, destination=None, reply_to=None, notice=False):
@@ -1339,7 +1343,7 @@ class SopelWrapper:
             :meth:`sopel.bot.Sopel.reply`
         """
         if destination is None:
-            destination = self._trigger.sender
+            destination = self.default_destination
         if reply_to is None:
             reply_to = self._trigger.nick
         self._bot.reply(message, destination, reply_to, notice)
```
</details>

> @SnoopJ could you provide the IRC raw logs for your example? This would be a great base for a non-regression test.

No problem:

```
2023-03-31 18:58:24,270 <<      '@time=2023-03-31T22:58:24.266Z;account=SnoopJ :SnoopJ!~snoopj@user/snoopj PRIVMSG +##terribot-testing :!version\r\n'
2023-03-31 18:58:24,277 >>      'PRIVMSG ##terribot-testing :[version] Sopel v8.0.0.dev0 | Python: 3.7.16 | Commit: b5eba03ce74baae36e3456ac938686fb23f5671b\r\n'
2023-03-31 18:58:24,316 <<      '@time=2023-03-31T22:58:24.284Z;account=SnoopJ :terribot!~sopel@user/snoopj PRIVMSG +##terribot-testing :[version] Sopel v7.1.9 | Python: 3.9.9\r\n'
2023-03-31 18:58:24,347 <<      '@time=2023-03-31T22:58:24.320Z;account=SnoopJ :testibot!~sopel@user/snoopj PRIVMSG ##terribot-testing :[version] Sopel v8.0.0.dev0 | Python: 3.7.16 | Commit: b5eba03ce74baae36e3456ac938686fb23f5671b\r\n'
```

**Comment by dgw** [comment]
> `+        return (self._trigger.status_prefix or "") + self._trigger.sender  # this isn't properly handling sender = None`

About this part, I think the best solution is to just `if self._trigger.sender is None: return None`.

If the `sender` was `None`, then there's no chance it will have a STATUSMSG prefix that needs to be preserved.
