### ISSUE TITLE
Allow willie to accept commands without the command prefix in private messages

### ISSUE THREAD

**Issue by tylercrumpton** [sopel-irc/sopel#252]
One feature that I've seen in quite a few other IRC bots is the ability to use commands in a private message with the bot, without having to use the command prefix (the full-stop by default in willie).

It should be relatively straight-forward to implement a similar option for willie, allowing for greater flexibility and a better user experience for users of the bot. A user would still be able to use the command prefix in private messages, but it would not be required.

**Comment by matthijskooijman** [comment]
FWIW, I'm also used to having non-prefixed commands in private messages (coming from supybot), and I'd like to see this in willie as well. Not sure if the conflict possibility should stop this from being optionally implemented - it's up to the bot owner to only enable t his if none of his module would conflict.  In the end, anything can conflict - I can just as well write a module that uses a rule to match things that have the configured prefix as well.
