### ISSUE TITLE
plugin: `event` has no `events` counterpart

### ISSUE THREAD

**Issue by ghost** [sopel-irc/sopel#2548]
There's `sopel.plugin.event` but no aliased `sopel.plugin.events`.

`(action_|nickname_)?commands?` has it too.

**Comment by dgw** [comment]
Hmm, we're trending _away_ from these pluralized decorator copies. https://github.com/sopel-irc/sopel/issues/1619#issuecomment-672961826. Which is to say, the existence of decorators named `*commands` is a (an?) historical artifact. e should mark them as deprecated someday, then remove them, not add more.
