### ISSUE TITLE
adminchannel: empty `.tmask` handled incorrectly

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#2596]
### Description

Running `.tmask` without any argument technically sets an empty topic mask, but in a broken way.

### Reproduction steps

0. Enable `adminchannel` plugin if not enabled
1. As chanop, do just `.tmask` (no argument)
2. Do `.showmask`
3. Sopel responds with an exception:
   `Unexpected TypeError (can only concatenate str (not "NoneType") to str) from dgw. Message was: .showmask`

### Expected behavior

`adminchannel` should properly _clear_ the topic mask in this case, such that doing `.showmask` yields the same output as if `.tmask` had never been set at all.

Additionally, `.showmask` should handle `None` as if the topic mask is unset. Defense in depth!

### Notes

I've a half-assed patch for this in `adminchannel-tmask-none` branch, but it's untested and probably needs some more work before becoming a pull request.

### Sopel version

973a489355540d68b95db01a49e983ac7a740bcc

### Installation method

`pip install`

### Python version

3.10.7

### Relevant plugins

adminchannel

**Comment by half-duplex** [comment]
Unless we have an established pattern, I prefer possibly-destructive things be explicit: an argument of empty quotes, a hyphen, `-clear`, or similar to clear it, `.tmask` without arguments shows usage including how to clear.

**Comment by dgw** [comment]
The thought of adding a `.clearmask` or `.tmclear` command did cross my mind, yes. I had forgotten about `.showmask`, didn't expect `.tmask` to accept an empty arg either, and was surprised.

**Comment by dgw** [comment]
_Process note: We're likely to slot #2601 into 8.0.0 because it's a user-facing change and not a pure bugfix, so I've changed the issue's target milestone._
