### ISSUE TITLE
https://sopel.chat/ web site needs a contact location.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#2615]
### Requested Feature

https://sopel.chat/ web site needs a contact location as well unless I am not seeing it.

### Problems Solved

It would be easier for users to find help.

### Alternatives

I had to find the answer in https://github.com/sopel-irc/sopel/.

### Notes

Thank you for reading. :)

**Comment by dgw** [comment]
1) The website has its own repo: https://github.com/sopel-irc/sopel.chat
2) There is already contact info in the very first FAQ entry on the home page:

![image](https://github.com/user-attachments/assets/7ac0c8e1-ccc8-4d5c-939b-dac036dd528a)
