### ISSUE TITLE
exit on error Command Line flag

### ISSUE THREAD

**Issue by tyrope** [sopel-irc/sopel#273]
As suggested by @elad661 for #268 
"Run its own willie instance so that we can easily detect commits that breaks the ability of the bot to start and connect. To do that we will need to add a switch willie, something like `--exit-on-error` to make the bot exit with a predefined code as soon as a core exception is detected."

**Comment by maxpowa** [comment]
Not sure if this is needed for testing, we're currently able to test a large portion of the bot without actually starting a full instance.

**Comment by Exirel** [comment]
If nobody is running the bot to test it, and need this, I think we can close it for now (this comment is not sponsored by the Clean Up Industry, I swear).

**Comment by dgw** [comment]
The way testing works now, I agree we don't need this feature. (Thanks for checking old issues, @Exirel!)
