### ISSUE TITLE
Document 'rule' triggers

### ISSUE THREAD

**Issue by tyrope** [sopel-irc/sopel#311]
To prevent accidental mentions, read all instances of [at] as @ .

Currently, the list of commands only shows [at]command triggers, but not [at]rule ones.
This might need an exception when automated due to the 'anything' rules for certain [at]event-based actions.

**Comment by Exirel** [comment]
I think both @dgw initiative to create a "sopel-module" site, and my PR #1434 to have a `sopel-module` command line to show help of module, including rules & intent, are a great start.

I'm not convince by the wiki (promoted by issue #398), and I think there is something to do with Sphinx and the autodoc - I'm an heavy user of Sphinx, and I think I can make a PR to demo something about this.

**Comment by dgw** [comment]
This should be revisited in the website repo. The script to generate a list of commands and related documentation lives there, and it's not Sopel's responsibility to facilitate that in any way (except for maintaining clean internals, which we want to do anyway for maintainability reasons).
