### ISSUE TITLE
Feature request: add admin levels

### ISSUE THREAD

**Issue by LeartS** [sopel-irc/sopel#343]
Currently Willie has a simple admin structure: either someone is an admin, or someone is not.
A nice feature would be and admins "hierarchy": various admins levels, with each one able to execute more commands than the previous.

The levels should be configurable: users should be able to assign, for each command, a minimum admin level requirement to trigger it.

I hope what I mean it's clear. Thanks.

**Comment by dgw** [comment]
Given the API changes that this would require, I don't see it happening. Using channel privileges is sort of a workaround (though not perfect), I guess.

We can reopen if someone has ideas for implementation without breaking existing `trigger.admin` logic.
