### ISSUE TITLE
topic add feature

### ISSUE THREAD

**Issue by teh-maxh** [sopel-irc/sopel#350]
Instead of requiring additions to the topic to be done manually (`.t [new topic] | [old topic]`), add a command so that Willie will do it automatically (`.at [new topic]`).

**Comment by Helldembez** [comment]
I made an attempt to create a module like Venti mentioned. Problem I encounter is that the channel objects topic is empty. So unless I'm missing something there is no way to get the current topic. I've tried this so far.

`
currentChannel = bot.channels[trigger.sender]
currentChannel2 = Channel(trigger.sender)
print(currentChannel.topic)
`

**Comment by dgw** [comment]
I don't think this is going to happen in the foreseeable future.
