### ISSUE TITLE
New rules for pull requests and commit messages

### ISSUE THREAD

**Issue by elad661** [sopel-irc/sopel#483]
I'm tired of seeing pull requests titled "Fix test for" when they actually fix a test FAILURE. Fixing a test failure when the test itself is correct is fixing FUNCTIONALITY. When the test is wrong, that is when you can use "Fix test". I'm also tired of commit messages saying "Fix ... in ..." without further details.

I think we need more clear commit message guidlines:

The following commit messages are _not okay_:
1. Fix NameError in foo.py
2. Fix foo
3. Fix tests in foo.py
4. Fix bug introduced in commit foo

A commit message should be descriptive, and it should not only contain an answer to "what" but also an answer to "why". 

"Fix foo" is not good unless foo is _clearly_ broken, and the way it is broken is clear. When it's not clear, or it's a functionality change, the extended commit message should explain what is the broken behavior, and why is your commit the appropriate way to fix the problem. A commit message such as "Fix NameError" is too generic to be descriptive: What caused the exception? Why? How do you fix it? 

You want to make it possible for someone looking at the commit log to understand the motivation behind the commit without reading too much code. 

When you add a human error message, "Make error message in foo() more user friendly" is good, while "Fix KeyError in foo.py" is bad. When you fix a bug uncovered by unit tests, "Fix tests in foo.py" is bad, while "Fix spaghetti rate error in foo.py" is good. When you fix a regression, "Fix bug introduced in commit foo" is bad, while "Fix a regression from foo that caused spaghetti to be too sticky" is good.

Make use of extended commit messages. Sum up your change in one line at the top, make two new lines and write a more descriptive explanation below. 

Please [read this post for more information about proper commit messages](http://who-t.blogspot.de/2009/12/on-commit-messages.html).

I suggest we agree on and enforce a commit message/pull request description policy by considering my points and the points raised in the blog post.

**Comment by dgw** [comment]
Closing as basically resolved. I'm more or less enforcing good commit messages as I review PRs, and the conventions have been pretty well explained in CONTRIBUTING.md since 2016.
