### ISSUE TITLE
Add a way for modules to listen on Willie's output

### ISSUE THREAD

**Issue by elad661** [sopel-irc/sopel#526]
It would be neat if modules could act upon Willie's own output. We discussed this before and I think the general conclusion was "too hard to do". The thing is, it won't be to hard if we decide that callables are uni-directional (one callable won't be able to listen to both input and output).

If we can't build `Trigger()` properly for this, we can simply provide the raw line sent. We should encourage modules to not send out more data in response to parsing sent data, cause that might lead to an infinite loop. We especially don't want `url.py` or anything similar to use that.

Output triggers should use events and regexes and priorities as well.

This will be useful for chanlogs as it will allow as to log what the bot is saying to the channel.

calling the callables should be done after the sending lock is released, because you never want to hold that lock for too long.

As for defining such callables, I suggest `@willie.module.output_handler`

**Comment by maxpowa** [comment]
I've implemented this in https://github.com/sopel-irc/sopel/pull/1072.
