### ISSUE TITLE
url.py fails to find the title if the title tag contains a space

### ISSUE THREAD

**Issue by Ban3** [sopel-irc/sopel#530]
example:  ``` <title >string</title>```

```start = content.find('<title>') ``` doesn't find that title.

I think using a parser would be the correct way to handle getting the title tag. I have modified url.py to use BeautifulSoup for extracting the title, if that's okay I can send a pull request.

**Comment by maxpowa** [comment]
[url.py line 205](https://github.com/sopel-irc/sopel/blob/master/sopel/modules/url.py#L205) should be cleaning up extra things from the title tag. Do you have an example of a website thats exhibiting this behavior?

**Comment by maxpowa** [comment]
No info, so closing.
