### ISSUE TITLE
Module configuration errors

### ISSUE THREAD

**Issue by reissmann** [sopel-irc/sopel#545]
Hi,

i just installed willie using pip. When starting willie, doing the automatic configuration and getting to the question whether I'd like to "check if any modules need configuring", i get a bunch of errors:

willie --configure-modules
Error loading rand: 'module' object has no attribute 'module' (in config.py)
Error loading meetbot: 'module' object has no attribute 'module' (in config.py)
Error loading help: 'module' object has no attribute 'module' (in config.py)
Error loading ai: 'module' object has no attribute 'module' (in config.py)
[...]

Any hint, what I'm missing?

**Comment by sharktamer** [comment]
Looks like this issue is still occurring when running run_example_tests
