### ISSUE TITLE
Quits when the irc server can't be reconnected

### ISSUE THREAD

**Issue by glandium** [sopel-irc/sopel#548]
When the irc server somehow is disconnected, willie tries to reconnect after 20 seconds. Unfortunately, when that reconnect fails, it doesn't keep retrying.

**Comment by matthijskooijman** [comment]
I'm also running into this just now, sometimes reconnecting fails and my bot drops off the channel requiring manual intervention.

To me, it seems sensible to just have it reconnect indefinitely, if there is some non-temporary problem, the bot operator can notice the bot's absence and investigate (right now, this also needs to happen with a temporary problem).

On startup, reconnecting indefinitely could also make sense. When you start willie manually from the commandline, throwing an error and giving up after 1 attempt is probably fine, but when run from e.g. an initscript, reconnects could make sense (consider the case where you reboot your server just when the IRC server is unavailable for a few minutes).

**Comment by Nuvelle** [comment]
This is still something I would love to see added.

I run the bot from home and sometimes the net drops out, if its for more than a couple of mins the bot dies and must manually be restarted. An indefinite/set rejoin attempt would be invaluable to me and the people who use the bot!

**Comment by rinzes** [comment]
Why not use crontab

**Comment by maxpowa** [comment]
Sopel should continue attempting connection even if it fails as of https://github.com/sopel-irc/sopel/commit/a10cf3e8413ef6dfdf9b25aeb6ea5f67e246e6f4
