### ISSUE TITLE
Save joined channels in the configuration

### ISSUE THREAD

**Issue by phantium** [sopel-irc/sopel#563]
Right now when you add a channel with !join it does not save the channel to the config and the channel is not rejoined after restarting the bot.

Personally I would like to see this added, however also with the option for a delay joining channels so that bots who join a lot of channels don't flood the server.

Chances are, that I'll write a module to do this as it's something I need personally.
However in my case it would not make sense to write this into the default.cfg, as more than 10 channels would already be too difficult to maintain in the config file.

**Comment by Exirel** [comment]
It is doable, for sure, but I don't know what the proper interface would be. In particular, I wonder what the default behavior should be.

For example, would it be something like this?

    <me> !join [channel] [remember: default=no]

This would make Sopel join the channel until restart:

    <me> !join #onlyonce

This would make Sopel save the channel in its configuration:

    <me> !join #awesome yes

But maybe there are better way to tell that. What do you think @dgw? Is that something to consider?

**Comment by dgw** [comment]
I'd say it should always save joined (and parted) channels to the config. The optional second argument to `.join` is already used for channel key/password, and it would get complicated to add a third argument that's also optional.

**Comment by Exirel** [comment]
Oh right! It makes sense. I can do that this week.

7.x or 6.x?

**Comment by dgw** [comment]
7.x, probably. Especially if you feel like implementing general config auto-save (#1354) at the same time. 😁
