### ISSUE TITLE
Missing backports.ssl_match_hostname when installing with pip

### ISSUE THREAD

**Issue by joehakimrahme** [sopel-irc/sopel#568]
On OSX, I install willie running `pip`:

```
Downloading/unpacking willie
  Downloading willie-4.4.1.tar.gz (97kB): 97kB downloaded
  Running setup.py egg_info for package willie

Installing collected packages: willie
  Running setup.py install for willie
    changing mode of build/scripts-2.7/willie from 644 to 755

    changing mode of /Users/joehakimrahme/.venv/daas/bin/willie to 755
Successfully installed willie
Cleaning up...
```

When I try to run `willie` I get this error:

```
Traceback (most recent call last):
  File "/Users/joehakimrahme/.venv/daas/bin/willie", line 31, in <module>
    import willie.web
  File "/Users/joehakimrahme/.venv/daas/lib/python2.7/site-packages/willie/web.py", line 35, in <module>
    import backports.ssl_match_hostname
ImportError: No module named backports.ssl_match_hostname
```

I don't know much about packaging but it seems like `backports.ssl_match_hostname` is not marked as a dependency.
## Temporary fix

Manually installing `backports.ssl_match_hostname` solves the issue.

```
pip install backports.ssl_match_hostname
```

**Comment by shiyeli** [comment]
Hi,how was this problem now?I also get this right now. I really install the module "backports.ssl_match_hostname",

`iMac:~ yetongxue$ pip list | grep back
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
backports.ssl-match-hostname (3.5.0.1)`

**Comment by shiyeli** [comment]
Hi,how was this problem now?I also get this right now. I really install the module "backports.ssl_match_hostname",I am in puzzled about this. 

```
 iMac:~ yetongxue$ pip list | grep back 
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning. 
 backports-abc (0.5) 
 backports.shutil-get-terminal-size (1.0.0) 
 backports.ssl-match-hostname (3.5.0.1)
```
