### ISSUE TITLE
Error messages when trying to run willie in python3

### ISSUE THREAD

**Issue by JoshuaACasey** [sopel-irc/sopel#572]
Welcome to Willie. Loading modules...

Error loading quotes: cannot import name 'quote' (../../.willie/modules/willie-modules/quotes.py:9)
Error loading rss: No module named 'feedparser' (modules/rss.py:16)
Error loading nws: invalid syntax (nws.py, line 171) (../<frozen importlib._bootstrap>:321)
Error loading roulette: invalid syntax (roulette.py, line 81) (../<frozen importlib._bootstrap>:321)
Error loading bugzilla: No module named 'lxml' (modules/bugzilla.py:11)
Error loading spellcheck: No module named 'enchant' (modules/spellcheck.py:13)
Error loading currency: No module named 'lxml' (modules/currency.py:11)
Error loading reddit-info: No module named 'praw' (modules/reddit-info.py:13)
Error loading ip: No module named 'pygeoip' (../../.willie/modules/willie-modules/ip.py:15)
Error loading weather: No module named 'feedparser' (modules/weather.py:15)
Error loading urbaanisanakirja: invalid syntax (urbaanisanakirja.py, line 28) (../<frozen importlib._bootstrap>:321)
Error loading ilmatieteenlaitos: cannot import name 'quote' (../../.willie/modules/willie-modules/ilmatieteenlaitos.py:10)
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)
Error loading siwa: cannot import name 'quote' (../../.willie/modules/willie-modules/siwa.py:8)
Error loading tiny: cannot import name 'quote' (../../.willie/modules/willie-modules/tiny.py:11)

Registered 47 modules,
15 modules failed to load

Connecting to irc.dftba.net:6697...
Connected.

---

Python 2.7.6 doesn't show these errors. Most of the errors are not relevant because they're third-party modules (from this git https://github.com/Meicceli/willie-modules) but there appear to be a couple core modules listed, also.

**Comment by rodolfobandeira** [comment]
This is how I solve the problem here on Ubuntu:
```
sudo apt-get install python-pip python-dev libxml2-dev libxslt-dev
pip install --user lxml
pip install --user pygeoip
pip install --user feedparser
```
