### ISSUE TITLE
Block hostmask wont block

### ISSUE THREAD

**Issue by SnipersLaww** [sopel-irc/sopel#575]
I have been trying to add various hostmasks using the proper style of ._@._.service.country and even ._@._.country and such and I dont even see these being added to my default.cfg file in the host_blocks section when the bot says they were successfully added and the users can still use commands.  They even show in the .blocks list hostmask list.  When I just add their nicks via the nick block though, they are added to the default.cfg list just fine and are unable to use any commands.  Being unable to block via hostmask is troublesome for those that like to switch names to get around limitations.

(sorry if this may or may not be clear enough.. Been up for over 40 hours and I am now crashing)

**Comment by 464bb26bac556e85b6fd6b524347b103** [comment]
Definitely doesn't work as documented.
