### ISSUE TITLE
Certain KICKs do not trigger admin.py's hold_ground rejoin

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#576]
I noticed that sometimes my Willie (4.4.1, installed from pip, with Python 2.7.3 on Ubuntu 12.04 LTS) would not rejoin on being kicked. Finally I decided to have a look into it.

After testing with several different users (mostly BotServ bots on Rizon, for convenience) in different channels, I found that the one user—a BotServ bot—that did not trigger a rejoin had a `-` in its hostname: `Ayu@ayu-anime.net`.

That's as far as I've gotten due to the late hour, but it seems strange.

**Comment by maxpowa** [comment]
Is this still valid in 6.3.1?

**Comment by dgw** [comment]
I have not been able to reproduce this on the current version of Sopel. Closing until and unless I can reproduce again.
