### ISSUE TITLE
[Feature] Announcments from shell

### ISSUE THREAD

**Issue by johnlage** [sopel-irc/sopel#646]
This would be triggered by running something like:

```
bash$ willie.py --announce blah
```

This would be using either separate code from the announce module, the announce module itself, or some other solution. I do not know if this should require the announce module to be loaded, and maybe having this enabled from the configs would be necessary. The usage case for this would be for example, I want to restart my bots on a nightly basis for updates and stuff. I would like the bot to auto-announce this via a script running with cron, but currently that isn't supported.

Thanks for all your hard work,

John Lage

**Comment by maxpowa** [comment]
See https://github.com/dgw/sopel-sockmsg for a sample implementation. Not sure if something like this is very desirable in core.

**Comment by dgw** [comment]
Let's leave this to custom implementations using my sockmsg example or a similar approach.
