### ISSUE TITLE
Support for uncommon priviliege prefixes

### ISSUE THREAD

**Issue by thorerik** [sopel-irc/sopel#648]
We are running a small network of our own on inspircd where we have enabled that IRCOPs have a seperate, higher level(denoted by ! on the nicklist)

Even if the user(me in this case) has +o, if they are logged in as IRCOP, willie will throw the following error (in this case using .radio on, which requires OP):

```
KeyError: Nick('Thor') (file "/usr/home/ircd/willie/willie/modules/radio.py", line 104, in radio)
```

On the terminal it provides the following traceback:

```
Traceback (most recent call last):
  File "/usr/home/ircd/willie/willie/bot.py", line 741, in call
    exit_code = func(willie, trigger)
  File "/usr/home/ircd/willie/willie/modules/radio.py", line 104, in radio
    if bot.privileges[trigger.sender][trigger.nick] < OP:
KeyError: Nick('Thor')
```
if I log out as IRCOP and just plain +o it functions as expected.

**Comment by maxpowa** [comment]
Tracking this in #1082
