### ISSUE TITLE
Verify consistency of plugin output formatting

### ISSUE THREAD

**Issue by embolalia** [sopel-irc/sopel#709]
Most things follow `[Thing] foo: bar | baz: wat`. I think that's probably the way we should go. We should make any tweaks to that we want (`2 comments`, or `Comments: 2`?), make a clear guideline, and implement it across modules.

One thing I would like to consider is using `…` over `...`. It gains us 2 extra characters (which, if you're using an ellipsis in the first place, you probably want), and gives me that warm fuzzy feeling I get from using Unicode properly. As a prerequisite, I'd like to add a guideline that when any non-ASCII character is used in source, the actual Unicode character is put in the file (`'…'`, not `'\u2026'`).

**Comment by elad661** [comment]
I think the ``2 comments`` vs ``Comments: 2`` varies between uses, I don't think each form fits all our uses. And a label shouldn't be mandatory, eg. Temperature: 5°C is silly when you can just say 5°C.

I agree with all the other points you mentioned.

**Comment by tyrope** [comment]
I agree with the labels. If the unit is obvious enough (like temperature, as exampled by elad) it should be discarded in favour of smaller messages. Keeping `|` as 'section seperators' and the ellipsis `\u2026` are definitely the way to go though.

**Comment by elad661** [comment]
I don't like the section separators in the wikipedia output, liked it better the way it was before

**Comment by dgw** [comment]
Punting to 7.1, as it pairs well with #1001.
