### ISSUE TITLE
Allow willie.module.rate To Apply To All Nicks

### ISSUE THREAD

**Issue by prestonconnors** [sopel-irc/sopel#718]
Hello,

I think a nice feature in willie would have some flag that is applicable to willie.module.rate to allow rate limiting of certain commands to only be activated by any/all nicks.

Example situation is a large chat room where I would like the 'hello' command to bot.reply('hello world!') only once every 300 seconds no matter how many people typed '.hello' after the first person activated the '.hello' command. If there is a current way of doing this please let me know and disregard this feature request!

**Comment by hroafelme** [comment]
This would be very good. I can't belive the bot does not have a global post rate. 

When you run the bot in a channel with over 1000 users it can be crazy, for example twich.tv

**Comment by tyrope** [comment]
@hroafelme The bot DOES have a global rate limiter. But it limits the entirety of the bot's IRC output.

**Comment by dgw** [comment]
How about a new `@globalrate` decorator?
