### ISSUE TITLE
Ignore trailing quote characters on URL

### ISSUE THREAD

**Issue by marsbard** [sopel-irc/sopel#726]
I have not installed willie but as a user it is very annoying to have urls in a quoted string throw "Page not found" error

I was recently advising the owner of the bot to upgrade and got this:

`<marsbard> acesabe: install git and then "git clone https://github.com/embolalia/willie.git"
<G1tB0t> [ Page not found · GitHub ] - github.com`

**Comment by tyrope** [comment]
Quotation marks are valid URI characters. Many IRC clients would include that " with the URL as well. I recommend ensuring there's spaces around URLs when you're using a medium that might use the URL as-is.

**Comment by embolalia** [comment]
NAK. As @tyrope said, nothing we can realistically do about this.

**Comment by marsbard** [comment]
Well there is a difference to being slavish to the URL spec and doing 
something that works for users.

Personally in my 17 year career using web technologies I have never seen 
a URL with a quotation mark in it anywhere, let alone at the end.

Martin

**Comment by embolalia** [comment]
I took a second look at the spec, and double quotes in fact are not allowed. The regex character class for what is allowed would be `[a-zA-Z0-9-_.~!$&'()*+,;=:/?#\[\]@]`. While double quotes aren't in this list, `()!;,.` would all also cause problems. Strictly speaking, if we were to not be "slavish" to the spec and instead be consistent with what users expect, we would follow what clients do, and from a cursory look that would appear to include the double-quote. Personally, I would err toward abiding by specs, as they're the best way to get clarity and consistency from ambiguous situations

**Comment by marsbard** [comment]
this is a bit ugly but if you got a 404 and the URL has a quote on the end, try again without the quote?
