### ISSUE TITLE
Allow modules to be folders

### ISSUE THREAD

**Issue by embolalia** [sopel-irc/sopel#732]
This is something I've heard a few people ask for, and it'll make #733  easier. It'll make the import system even more complex than it already is, but it's doable

---

* [x] Determine a namespace for modules on PyPI. ~~Probably `willie.modules` is best, meaning we should move the existing stuff to `willie.default_modules` or some such thing to avoid conflicts.~~ `sopel_modules`
* [x] Write documentation for how to make modules in folders

**Comment by embolalia** [comment]
Module loading is still a horrible mess, but at least now it's a horrible mess that's mostly in its own file.

**Comment by embolalia** [comment]
Closing, to be finished in #766

**Comment by embolalia** [comment]
Still has some TODOs that need fixing.

**Comment by nkuttler** [comment]
Is it just me or is the load functionality totally broken?

https://github.com/nkuttler/willie/blob/master/willie/modules/reload.py#L110

All that does is to check if the module that should be loaded is already loaded, and that obviously fails for the normal use case. I made a naive fix that works for me:

```
if hasattr(bot.config, 'extra'):
    path = '%s/%s.py' % (bot.config.extra, module_name)
```

This obviously won't load a package, or handle lists of directories in `config.extra` or trailing slashes gracefully. I think that `sys.path` should probably be searched as well?

Or is the enumerate_modules() function buggy in the sense that it should include available modules, not loaded ones? I'm kind of confused this bug exists if module loading doesn't work at all for me.

**Comment by embolalia** [comment]
Reopening, because I closed it before accounting for the module namespacing and documentation.
