### ISSUE TITLE
Make it easier to share modules

### ISSUE THREAD

**Issue by embolalia** [sopel-irc/sopel#733]
This has been kicking around my head for a while. [willie-extras](https://github.com/embolalia/willie-extras) really doesn't scale at all (it was primarily intended for the random stuff we throw on dftba.net and don't want in the main project). 

We need some sort of central location for all this that doesn't require too much oversight from us (and which doesn't imply too much curation on our part). One option could be to package them and put them on a PyPI server (probably a discrete one, to make finding them easier). Another would be to have a file in willie-extras storing repo links and whatnot. Both involve ongoing effort on my part (to keep the server up, or to merge PRs), but I think both are doable.

**Comment by tyrope** [comment]
I think if we allow sub-folder groups of modules, -extras should be fine. Since you can download per-file via github. It would also encourage us to keep those modules up to spec. (Perhaps we could even setup travis for it? Idk if Travis supports grabbing the willie repo to test willie-extras)

**Comment by embolalia** [comment]
The entire point of this ticket is to create a mechanism that does *not* have me (and the couple other people with push access on -extras) as a bottleneck. As it stands, *any* maintenance to any Willie module with any discoverability to speak of has to be funneled through us. A number of the modules in there are ones I didn't write, I don't use, and I don't care about. It's good for the ecosystem for such things to exist, but not for them to be funneled through us for maintenance.

**Comment by tyrope** [comment]
Is there a way to auto-pull requests if they pass the travis build? Might be slightly insecure, but with the git log any malicious users could perhaps be blacklisted?

**Comment by anarcat** [comment]
what about granting more people access to willie-extras?

otherwise i like the idea of having a search path and `pip` modules.

**Comment by janandjohn3** [comment]
At some point it could be cool to build some sort of system that would
allow people to install willie-extras modules from within willie. Just
pointing out how that could be nice.

John Lage

**Comment by belak** [comment]
It would be nice if modules could be installed in a virtualenv and could just be loaded from the pythonpath.

**Comment by embolalia** [comment]
With 6.0, and sopel-irc/sopel-cookiecutter, this is now super easy. Closing.
