### ISSUE TITLE
Database error

### ISSUE THREAD

**Issue by rinzes** [sopel-irc/sopel#757]
I have willie 5.1.1 installed and I'm starting to get this error:

DatabaseError: database disk image is malformed (file "/usr/local/lib/python2.7/dist-packages/willie/db.py", line 64, in execute)

**Comment by rinzes** [comment]
I have deleted the .db files and still getting the above error in v5.2

**Comment by embolalia** [comment]
Does excluding `seen` help at all? I suspect, since it whacks the database constantly, it might be too much for sqlite and causing problems. This is also backed by the fact that that whacking was introduced in 5.1, when the error seems to have started.

**Comment by rinzes** [comment]
I'll give that a try

**Comment by rinzes** [comment]
update: after adding "exclude seen" all is well so far

**Comment by maxpowa** [comment]
Does this still happen in 6.3.1? Can we close this?

**Comment by dgw** [comment]
Nearly two years later, I think we can close this.
