### ISSUE TITLE
Clarify sopel.module decorator docs

### ISSUE THREAD

**Issue by embolalia** [sopel-irc/sopel#758]
There's no reason these should say what the equivalent phenny-style assignment is. A standard phrasing should be used between them that makes their use clear within the context of modern Willie.

**Comment by dgw** [comment]
Is this even still a thing we need to work on? I don't see any phenny-style equivalents in our docs any more, and we've done quite a bit of work on the module decorator docstrings already.

@Exirel, do you have a plan for this? Maybe a brief version you can share?

**Comment by Exirel** [comment]
@dgw I was flagging interesting issues for me, mostly related to documentation. But right now I'm not sure this one is that meaningful. There is another issue to migrate Wiki documentation to the Sphinx documentation, and it contains a flag about plugins and stuffs.

So I guess we can close this.

**Comment by dgw** [comment]
Yeah, #398. That's also partially completed, between our doc updates and the work I put into moving pages from the GitHub wiki to the website.

I agree that this issue doesn't seem relevant any more, so I'll close it as we both agree.
