### ISSUE TITLE
`foo in bot.memory` no longer incorrect?

### ISSUE THREAD

**Issue by matthijskooijman** [sopel-irc/sopel#782]
The [documentation for memory](https://github.com/embolalia/willie/wiki/Willie-tutorial,-Part-4) says:

> The only difference is that, if you want to be thread safe (and you do), you should use the contains function rather than the in keyword when checking if memory contains a given key.

However, looking at the [implementation](https://github.com/embolalia/willie/blob/master/willie/tools/__init__.py#L312-L325), the `contains` method is equal to the `__contains__` method (which is AFAIK invoked by the `in` operator). It also says the `contains` method is deprecated.

Is the documentation out of date, or is there something else I'm missing here?

**Comment by Exirel** [comment]
New [documentation's URL](https://github.com/sopel-irc/sopel/wiki/Sopel-tutorial,-Part-4), issue stay the same.

**Comment by Exirel** [comment]
I didn't want to say it, but yes, the wiki should be left to rest in peace and lay down in a cold, dark, and very gentle place.

**Comment by dgw** [comment]
I think we can close this, actually. The wiki article in question was migrated to Sopel's website, and no longer mentions the deprecated `contains()` function as of sopel-irc/sopel.chat#19.
