### ISSUE TITLE
Better consistency between wrapped and unwrapped Willie objects

### ISSUE THREAD

**Issue by embolalia** [sopel-irc/sopel#796]
I noticed [`action()` takes the recipient as the second (optional) arg](http://willie.dftba.net/docs/#action), whereas `msg()` takes it as a mandatory first. Perhaps this could be re-worked such that the default is None (raising ValueError) in the un-wrapped class, and then have the wrapper provide the default argument. It might be worth deprecating `msg` in favor of `say` with this alteration. There's also no reason why `action()` shouldn't be available in the "real" class with this modification. 

`reply()` still wouldn't make much sense, since you'd have to supply who's being replied to, at which point you might as well just join up the string yourself. (Although, maybe just do it for consistency…)

**Comment by tyrope** [comment]
This will break many modules, so should probably be 6.0

**Comment by embolalia** [comment]
This was done in 1217c40a7549660b26deb9a6858a90f7f11172b6
