### ISSUE TITLE
.seen should keep track of joins and disconnections in channels.

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#815]
For an example (FYI: Flexo is rbot):

```
[01:37pm] <Ant> @seen Ben
01:37PM <Flexo> Ant: Ben was last seen 3 hours, 17 minutes and 43 seconds ago, joining #linux
[01:38pm] <Ant> Long ago. :P
[01:38pm] <Ant> .seen Ben
01:38PM <Willie> Ant: I last saw Ben at 2015-05-20 - 05:39:18 in here, saying That's early for them
[01:38pm] <Ant> uh
[01:38pm] <Ant> Willie doesn't see joins?
01:39PM <Mousey> rbot superiority reigns
01:39PM <Mousey> FILE A BUNG!
01:39PM <Mousey> s/N//
01:39PM <Laz> Mousey meant: "FILE A BUG!"
01:39PM <Willie> Mousey meant to say: FILE A BUG!
01:39PM <janice> Mousey meant: "FILE A BUG!"
[01:39pm] <Ant> BUNG? Hahah!
[01:39pm] <Ant> good idea
[01:39pm] * Ant goes to Willie!
```

Thank you in advance. :)

**Comment by elad661** [comment]
I think that was by design? Because many people are online all the time and sometimes they join automatically, and what you really want to know is when they were last active

**Comment by antdude** [comment]
How about listing both like this example?

[01:15pm] <Ant> @seen Bender
01:15PM <Flexo> Bender was last seen 6 months, 24 days, 20 hours, 54 minutes and 51 seconds
          ago, quitting IRC (Quit: okay bye) and a moment before saying "Ant: I'm a v.
          0.9.15 (fork branch, revision 6423121, 5 files changed) [3 months, 8 days, 9
          hours, 32 minutes and 21 seconds ago] rubybot, (c) Tom Gilbert and the rbot
          development team - http://ruby-rbot.org" in #linux

**Comment by elad661** [comment]
That format is waaaaaay too long

**Comment by antdude** [comment]
Bah, not that long!

**Comment by deathbybandaid** [comment]
Indeed, the proposed output is lengthy. This should be an easy PR if the output is more uniform with current `.seen` output.

However, this is not something I think should be implemented for bot owners using sqlite. I would think this is a good feature addition for `.seen`, if the plugin was installed separately with a warning stating: "The use of this plugin may cause database issues. Bot owners should consider using a different database."

**Comment by dgw** [comment]
Gave this a hard think just now. Elad had it right: Sopel's `.seen` command is about seeing when someone was last active. In the modern IRC world, where we trend toward everyone using some kind of bouncer or other always-online connection, seeing someone's last quit or join due to a momentary network issue is not very helpful.
