### ISSUE TITLE
Hide input of passwords in wizard

### ISSUE THREAD

**Issue by embolalia** [sopel-irc/sopel#819]
This is a 6.0 regression, which I might or might not get done for the actual release.

**Comment by Exirel** [comment]
I should just fix it, since I'm already working on the wizard & the config... :smile:

**Comment by dgw** [comment]
@Exirel Slot this into 7.0 if you think it's doable in a few days, or 7.1 if not. It's been broken for this long, so it's not _that_ big a deal if it slips out of 7.0. Even though I actually just missed milestoning it. 😅
