### ISSUE TITLE
use virtual host?

### ISSUE THREAD

**Issue by katmai** [sopel-irc/sopel#828]
i have been reading but is there any way to make willie use virtualhosts what i mean by that is not to connect with the default ip ? sorry been a long day and i can't seem to find anything about it.

cheers.

**Comment by embolalia** [comment]
Unless I'm mistaken, vhosts are entirely a server-side thing. Unless you're talking about ident spoofing, which is different and again I'm not sure that it's something Willie would be responsible for affecting.

**Comment by elad661** [comment]
Closing as this is marked "needinfo" for a long while now, and the reporter did not provide the required info. Feel free to re-open if you can provide the required info.
