### ISSUE TITLE
Plugin API: Add optional message to module.rate()

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#830]
If set, send `message` as a notice to the calling user if the command was canceled due to rate-limit. Ideally, it would support a placeholder such as `{time_left}` for the message to tell the user when they can use the command again.

I'd be happy to code it up and PR it; just want to establish that it'd have a chance of being merged first, before putting in that time.

~~Could also have a third parameter to toggle between using NOTICE and PRIVMSG.~~

**Comment by dgw** [comment]
If one of the collaborators for this repo feels like assigning this to me, I just came across it while cleaning out my oldest issues in the GitHub dashboard view, and am reminded that this would still be useful to have (since the majority of my Sopel modules use bespoke rate-limiting that includes these features).

**Comment by dgw** [comment]
Thanks for the reminder that this exists, @kwaaak. Assigning to Sopel 7 milestone, as it's an API change.

**Comment by dgw** [comment]
Hmm, this is not going to be so nice to implement with the rework of `@rate` from #1065.

Adding another optional `msg` kwarg would be fine, I guess, but not nearly as elegant as what I originally wanted to do (when there was only one type of rate-limit).

I suppose long-term we could consider splitting `@rate` into three decorators, but… it's not worth complicating the API like that for such a minor feature.

**Comment by dgw** [comment]
NAK third parameter (OP edited); should always use NOTICE.

**Comment by Exirel** [comment]
Still not sure how to do that properly for so many different rate limits:

```
def rate(user=0, channel=0, server=0, message=None):
```

Or:

```
def rate(user=0, channel=0, server=0, user_message=None, channel_message=None, server_message=None):
```

Or:

```
def rate(user=0, channel=0, server=0):  # deprecated?
def rate_user(limit, message=None):
def rate_channel(limit, message=None):
def rate_server(limit, message=None):
```

@dgw any opinion?

**Comment by dgw** [comment]
Combination of 1 & 3, mostly so there's a way to add more specific messages if necessary:

```python
def rate(user=0, channel=0, server=0, message=None):  # not deprecated
def rate_user(limit, message=None):
def rate_channel(limit, message=None):
def rate_server(limit, message=None):
```

Could be nice if e.g. `@rate(30, 'It's too soon!')` acted like `@rate_user(30, 'It's too soon!')`, but I know how you feel about "smart" argument handling.

No objection to putting this in 8.0, either, as there's plenty left for 7.1 as it is.

**Comment by Exirel** [comment]
Yeah OK it's getting quite complex and Sopel 8 will handle it, because Sopel 8 is 7.1 but better.

**Comment by Exirel** [comment]
Working on that, I already have a working solution, I just need to iron out the tests and the documentation.
