### ISSUE TITLE
Sopel doesn't work at all

### ISSUE THREAD

**Issue by pierg75** [sopel-irc/sopel#854]
I know it's very generic but this is what I get on Fedora 22. I didn't try any other distro, I might do it later, but willie was working (and the version in fedora works) fine.
After having reset the config, I get some errors from the included plugins:

Welcome to Sopel. Loading modules...

Error loading reddit: No module named 'praw' (modules/reddit.py:17)
Error loading ip: No module named 'pygeoip' (modules/ip.py:9)
Error loading bugzilla: No module named 'lxml' (modules/bugzilla.py:9)
Error loading weather: No module named 'feedparser' (modules/weather.py:15)
Downloading malwaredomains db...
Error loading currency: No module named 'lxml' (modules/currency.py:11)
Error loading ipython: No module named 'IPython' (modules/ipython.py:23)

Registered 35 modules,
6 modules failed to load

Just to be sure I have these modules:

$ python
Python 2.7.10 (default, Jul  5 2015, 14:15:43) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml
>>> import praw

This was done with the same user I use to run Sopel.
The config created by the installer is:

[core]
nick = Sopel
host = irc.internal.server
use_ssl = false
port = 6667
owner = user
channels = #chan1,#chan2

Executing "commands" returns:

[13:35] <Sopel> Commands I recognise: .
[13:35] <Sopel> For help, do 'Sopel: help example' where example is the name of the command you want help for.

**Comment by pierg75** [comment]
Just to confirm, went back to Willie 5.5 and everything works

**Comment by embolalia** [comment]
How did you install it, and how are you running it?

**Comment by pierg75** [comment]
If remember well I've taken the sources from github and running just like:

# sopel.sopel.py

**Comment by embolalia** [comment]
That'll run it with python 3, whereas if you pip installed the requirements it probably installed them for python 2. That'll explain the import errors in modules at startup, but there should still be some things working without that…

**Comment by pierg75** [comment]
Ahh indeed, I see that python was loaded.
I did then a pip installation (checked that python 2.7 is used) but I get when running .command:

Connecting to internal.irc.server:6667...
Connected.
Traceback (most recent call last):
  File "/home/bot/.local/lib/python2.7/site-packages/sopel/bot.py", line 245, in call
    exit_code = func(sopel, trigger)
  File "/home/bot/.sopel/modules/translate.py", line 218, in collect_mangle_lines
    if bot.config.has_section('translate') and bot.config.translate.collect_mangle_lines:
  File "/home/bot/.local/lib/python2.7/site-packages/sopel/config/__init__.py", line 163, in __getattr__
    % (type(self).__name__, name))
AttributeError: 'Config' object has no attribute 'has_section'

I get the same when I use the source and change the env setting to python2

**Comment by embolalia** [comment]
So, to be clear, the first time you just ran it from source, doing `./sopel.py`, and nothing worked. You then did `pip install sopel==6.0.0a4` and then ran `./sopel.py`, and (except for that traceback, which is a separate issue) everything works fine. Had you pip installed anything before running `./sopel.py` initially?

**Comment by embolalia** [comment]
Wait, when you said "doesn't work at all", what exactly did you mean? `.commands` gave a reply, right? Did other commands like `.t` or `.c` work? It sounds like the error is actually that the output of `.commands` is wrong, not that nothing works, which is totally different.

**Comment by embolalia** [comment]
Please verify whether you still have this issue with 6.0.0a5.

**Comment by pierg75** [comment]
With the latest from github I don't see any more this problem.
Thanks and sorry for being so late.
You can close this one I guess.
