### ISSUE TITLE
Pip upgrade not installing latest version - willie complains

### ISSUE THREAD

**Issue by Serubin** [sopel-irc/sopel#855]
After running pip install willie --upgrade willie still complains about being a minor version behind. Willie says it's version is 5.4.0 and would like to be upgraded to 5.4.1

**Comment by tyrope** [comment]
Current versions are 5.5.0 and 6.0.0a4

If it's complaining about 2.x, something is horribly wrong, since we started counting at 3.

**Comment by Serubin** [comment]
Sorry - that was a typo: 5.4.0 -> 5.4.1

**Comment by embolalia** [comment]
I was not able to reproduce this. What OS are you on? Are you doing anything with python3, virtualenv, scl, …

**Comment by Serubin** [comment]
I'm on debian 8 with both python3 and python2.7. I think willie is using 2.7 as that is the system default.

**Comment by embolalia** [comment]
How are you running Willie? If you're just running the `willie` command, what's the output of `which willie`? Did you apt-get install willie at some point, even if you later pip installed it? (I know the Debian package has had some issues before…)

**Comment by Serubin** [comment]
seru@calypso:~$ which willie
/usr/local/bin/willie


I've only installed using pip. I may uninstall and just install from the source.

**Comment by embolalia** [comment]
Is this still an issue with `sopel`?

**Comment by Serubin** [comment]
Doesn't appear so.
