### ISSUE TITLE
chanlogs.py UnicodeDecodeError

### ISSUE THREAD

**Issue by hierocles** [sopel-irc/sopel#856]
The chanlogs.py module produces a UnicodeDecodeError whenever a non-ASCII character is posted in the channel.

The error looks like this:
```
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 38: ordinal not in range(128) (file "/home/hierocles/Snakepit/willie/local/lib/python2.7/site-packages/willie/modules/chanlogs.py", line 135, in log_message)
```

I looked at the offending line in chanlogs.py and did some Googling. I have very little experience with Python, but I came across this Stackoverflow discussion on the UnicodeDecodeError: http://stackoverflow.com/questions/24475393/unicodedecodeerror-ascii-codec-cant-decode-byte-0xc3-in-position-23-ordinal

The problem there was that Python was encoding twice, which required it to first decode to ASCII. I looked to see if this same thing was happening in chanlogs.py, and it sure is.

_format_template() is returning a UTF-8 encoded message if the Python major version number is less than 3. (I am running 2.7.) This message is then getting encoded into UTF-8 *again* by log_message().

I commented out the Python version checking in _format_template(), so that the value it returns is never encoded to UTF-8, leaving encoding up to log_message().

Now, this works for my setup, but like I said, I don't know Python. So I'm not sure if this is a good idea at all or if it would work with other setups.

**Comment by embolalia** [comment]
Please search for issues before reporting them. This has duplicates #768 (and a number of others). To reiterate, chanlogs is known to be broken with unicode. The cause of this bug is well known, but the module is being removed in 6.0, per #818, so no further patches to it are being made here. Remove its configuration, or add it to `exclude`, and the issue will go away.
