### ISSUE TITLE
Willie -> Sopel config file conversion script

### ISSUE THREAD

**Issue by itskieranp** [sopel-irc/sopel#863]
Since upgrading to Willie 5.5 from 5.3, I have been getting lots of "depracated" errors for things such as `server_password`, yet there is no info about the preferred way to update the file. Could perhaps a script be made to do this? (if needed, I can do so, given the relevant docs)

**Comment by embolalia** [comment]
It's mentioned in the [migration page](http://sopel.chat/willie_6.html); from 5.3 on, the documented way to set up nickserv and other auth is with the auth_method, auth_password, etc. documented [here](http://sopel.chat/6.0.0a1/docs/#the-core-configuration-section). If you want to make a script to make that change, feel free. If you submit a PR for it, it should go in `contrib/`.

**Comment by Exirel** [comment]
I wonder if this is still relevant today: it's been more than 3 years now!

**Comment by dgw** [comment]
@Exirel Good catch; let's not spend dev time on this.
