### ISSUE TITLE
Ignore forced name change

### ISSUE THREAD

**Issue by ZeroTheSavior** [sopel-irc/sopel#869]
Can this be an option? I set the name and the server is changing it to the same name, so it shouldn't be an issue.

Registered 33 modules,
8 modules failed to load

Connecting to localhost:6667...
Connected.
CRITICAL:sopel.modules.coretasks:Nick changed by server. This can cause unexpected behavior. Please restart the bot.
Calling shutdown for 0 modules.
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...

**Comment by elad661** [comment]
1) This is weird, the server shouldn't do it

2) We can add a condition so if it's the same, Sopel won't freak out.

**Comment by embolalia** [comment]
That is definitely a very bizarre thing for the server to do, but we can accommodate it. What IRCd is doing this? It'd be useful to know for testing.

**Comment by ZeroTheSavior** [comment]
It's an irc 'emulator'. It connects using Pickups, a program that connects to Google Hangouts then acts as an irc server as if a Hangouts group chat were a regular irc server for irc clients to connect.

**Comment by elad661** [comment]
I've committed a fix, but I have no way to verify it. Please test it and let me know if it worked so I can close this issue.

**Comment by embolalia** [comment]
No comment since the fix was pushed a while ago, so I'm going to assume this is resolved.
