### ISSUE TITLE
".... [WARNING] link posted by Ant is possibliy malicious (confidence .../10)"

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#870]
What the frak?
...
[01:59pm] <Ant> KaT: http://dilbert.com/strip/2015-08-28
01:59PM <Willie> [ Wally Gets Nano Robot Injection - Dilbert Comic Strip on 2015-08-28 | Dilbert by Scott Adams ] -
          dilbert.com
01:59PM <Willie> [WARNING] link posted by Ant is possibliy malicious (confidence 100.0% - 10/10)
01:59PM <Bender> back. FML - posted by hopelesscollegechick in miscellaneous
[01:59pm] <Ant> wtf!
[02:00pm] <Ant> http://aqfl.net
[02:00pm] <Ant> uh
02:00PM <Willie> [ Ant's Quality Foraged Links (AQFL) | Top quality and cool links foraged, approved, and shared by
          Ant and others. Also, blogs and comments. ] - aqfl.net
[02:00pm] <Ant> http://google.com
02:00PM <Willie> [ Google ] - google.com
[02:00pm] <Ant> http://cnn.com
02:00PM <Willie> [ Breaking News, U.S., World, Weather, Entertainment & Video News - CNN.com ] - cnn.com
[02:00pm] <Ant> http://dilbert.com/strip/2015-08-28
02:00PM <Willie> [ Wally Gets Nano Robot Injection - Dilbert Comic Strip on 2015-08-28 | Dilbert by Scott Adams ] -
          dilbert.com
[02:00pm] <Ant> Ant http://dilbert.com/strip/2015-08-28
02:00PM <Willie> [ Wally Gets Nano Robot Injection - Dilbert Comic Strip on 2015-08-28 | Dilbert by Scott Adams ] -
          dilbert.com
02:00PM <Willie> [WARNING] link posted by Ant is possibliy malicious (confidence 100.0% - 10/10)
[02:00pm] <Ant> um
[02:01pm] <Ant> Ant http://aqfl.net
02:01PM <Willie> [WARNING] link posted by Ant is possibliy malicious (confidence 100.0% - 10/10)
02:01PM <Willie> [ Ant's Quality Foraged Links (AQFL) | Top quality and cool links foraged, approved, and shared by
          Ant and others. Also, blogs and comments. ] - aqfl.net
[02:01pm] <Ant> Ant https://google.com
02:01PM <Willie> [WARNING] link posted by Ant is possibliy malicious (confidence 100.0% - 10/10)
02:01PM <Willie> [ Google ] - google.com
[02:01pm] <Ant> lol
...
[02:12pm] <Ant> Can someone pleae kindly post a valid URL to me.
...
02:22PM <KaT> Ant: http://dilbert.com/strip/2015-08-28
02:22PM <Willie> [WARNING] link posted by KaT is possibliy malicious (confidence 100.0% - 10/10)
...

A bug?

**Comment by elad661** [comment]
Yes, it's definitely a bug... and we are unsure why it happens. I'll look into it.

**Comment by antdude** [comment]
Thanks,  Elad. It scared me at first. :) I hope it gets fixed in v5.x and not just v6.

**Comment by elad661** [comment]
Fixed. See commit message for full gory details!

**Comment by antdude** [comment]
Thanks again, Elad! Will this fix be in v5.x or only v6?

**Comment by elad661** [comment]
I've pulled this fix into 5.x too. You should consider updating to 6.x, since it's way better :)

**Comment by antdude** [comment]
Isn't v6 still buggy and under development? :/

**Comment by elad661** [comment]
well, @embolalia can answer about this in more details, but afaik, while 6 is still under development, it is much less buggy than 5.x because @embolalia is fixing *a lot* of bugs.

**Comment by embolalia** [comment]
It is still under development, but it's mostly stable at this point. I'll probably be moving it from alpha to beta within a couple weeks. And honestly, I could probably do a final release right now. It's no more buggy than any other release at this point! :D
