### ISSUE TITLE
ListAttribute should be striped

### ISSUE THREAD

**Issue by Deedasmi** [sopel-irc/sopel#872]
```extra=/test, /test2```

Will fail and cause sopel to not launch, while:

```extra=/test,/test2 ```

Will not.

**Comment by tyrope** [comment]
Although this will fix the problem in `[core]extra=`, it could introduce a new problem to (the unintended feature) `[core]channel=#channel,#foo password,#bar` unless executed properly.

**Comment by Deedasmi** [comment]
This is my first time contributing to a project, and I haven't totally figured out how Sopel works on the inside yet, so.... Do you have any suggestions on a better/safer way to fix it? It just makes sense to me that the config file should not be dependent on (the lack of) whitespace.

**Comment by embolalia** [comment]
This wouldn't harm the channel password thing (since it only removes from the ends of each item), but it would make it impossible to have list items that have spaces. It'll have to be optional, that is `ListAttribute` takes an argument `strip`, and stripping is only done if it's `True` (which I think can be the default).

**Comment by Deedasmi** [comment]
> "would make it impossible to have list items that have spaces."

I don't understand this part. As you mention in the first line, this is not a str.replace(" ", ""). It will simply remove every space immediately before and after a comma, which in a comma separated string should be pretty harmless.

If you'd still prefer the default argument, I can go ahead and update the pull request in a bit.

**Comment by embolalia** [comment]
Sorry, I meant list items that start or end with a space. It's an edge case, but handling edge cases well is important.

**Comment by Deedasmi** [comment]
#873 now has a default parameter.
