### ISSUE TITLE
dice not accepting upper-case

### ISSUE THREAD

**Issue by ventris** [sopel-irc/sopel#874]
The dice function wont accept upper-case D in number of dices.

eg. 1D100

answer from bot: "SyntaxError, eval(1D100), unexpected EOF while parsing (<unknown>, line 1)"

Has only been tried on python 3.

**Comment by Deedasmi** [comment]
http://i.imgur.com/dubuZwB.png?1

It also doesn't handle invalid input very gracefully. I'll look into it more this weekend.

**Comment by maxpowa** [comment]
Appears to have been resolved by #969
