### ISSUE TITLE
Ability to add admins in irc

### ISSUE THREAD

**Issue by stopspazzing** [sopel-irc/sopel#886]
There currently is no way to add admins to the config file without manually editing the file and adding them. A simple:

```
.admins add NICK
.admins remove NICK
```

would be awesome. Also should be restricted to owner only for obvious reasons.

**Comment by dgw** [comment]
Actually, once `.set` is fixed to work with list-type settings again, you can do `.set admins` to get the current list, and e.g. `.set admins adminnick,anotheradmin,adminnumber3` to update it, then `.save`. As I recall, settings changed with `.set` do take effect immediately.

**Comment by stopspazzing** [comment]
Sounds like a good idea. But set doesn't let you change it? or do you have to redefine the whole list to change 1 item?

**Comment by dgw** [comment]
The way `.set` works now, yes, you have to redefine the whole list. Now that config options have types, someone feeling adventurous could implement adding/removing list items and other goodies.

**Comment by stopspazzing** [comment]
```
foreach (name in adminslist) 
    if name == args[0]
        adminslist.remove('name')
```

**Comment by elad661** [comment]
This (and .set too) is a bad idea

**Comment by embolalia** [comment]
Yeah, changing the confg from IRC, with the current state of auth, is probably not something we should have. This is a blatantly obvious privilege escalation vuln. `account-tag` will change that, but currently no ircds actually implement it. I've filed #888 to implement support for that. I'll leave this open, but I don't think it's worthwhile to put any more attention into the usability of something this dangerous until it's done.

When it does come time to do this, it should be more general append/remove support for list items.

**Comment by Exirel** [comment]
As I've to maintain a server, I totally agree with @elad661 and @embolalia, it's scary!

**Comment by dgw** [comment]
#1385 fixed the issue with `.set` handling spaces. An `.admins` command isn't going to happen, though.
