### ISSUE TITLE
Dynamically adding and removing triggers

### ISSUE THREAD

**Issue by Thermi** [sopel-irc/sopel#890]
Hello,

Is it possible to add and remove triggers during runtime?
Also, where is the piece of code that calls the modules's trigger handler?

Kind regards,
Thermi

**Comment by maxpowa** [comment]
I'm not sure if there's any recommended way to do this, but this is how I do it. https://github.com/maxpowa/sopel-idlerpg/blob/master/sopel_modules/idlerpg/idlerpg.py#L231-L262

**Comment by embolalia** [comment]
Programmatically, no. You can load additional modules at runtime, and reload existing ones, which will take care of adding their triggers appropriately. What @maxpowa is doing probably works, but is not officially supported.

**Comment by firerogue** [comment]
Going to reply despite the closed issue. It might make more sense to use some sort of dict in memory to track which triggers are "enabled" and "disabled" and simply emulate the behaviour by having the first line of the relevant commands be `if disabled: return` or something
