### ISSUE TITLE
Core; nick_blocks

### ISSUE THREAD

**Issue by rinzes** [sopel-irc/sopel#893]
I have nick_blocks = nick_name in the core config but when he/she posts a url the bot still posts the output of that url link.

**Comment by maxpowa** [comment]
I've fixed this with https://github.com/sopel-irc/sopel/pull/912 and https://github.com/sopel-irc/sopel/pull/911

**Comment by embolalia** [comment]
Those are merged, so this can be closed. Thanks, @maxpowa!
