### ISSUE TITLE
authenticate via privmsg

### ISSUE THREAD

**Issue by rinzes** [sopel-irc/sopel#895]
I am on a server that requires authenticate via privmsg to X (ie: privmsg x authop #channel nick password). I didn't see in the current docs a way to accomplish this so requesting a Feature

**Comment by maxpowa** [comment]
I'm going to close this since AUTHOP isn't part of IRC spec nor is it widely used. I included a simple module that should be the minimum required to perform the authentication.

```
import sopel

@sopel.module.event(events.RPL_WELCOME, events.RPL_LUSERCLIENT)
@sopel.module.rule('.*')
def perform_authop(bot, trigger):
    bot.say('AUTHOP #somechan nick password', recipient='X')
```
