### ISSUE TITLE
Allow to configure url output

### ISSUE THREAD

**Issue by fgsch** [sopel-irc/sopel#896]
SSIA.

I can provide a patch if this is wanted.

sopel 6.0.0
python 2.7.9

**Comment by embolalia** [comment]
Configure it how? Can you give an example?

**Comment by fgsch** [comment]
For example I found the domain after the title a bit superfluous. 
I understand some people might want it hence I think being able to configure how the output looks like would make sense. atm is hardcoded to '[ title ] - domain'

**Comment by embolalia** [comment]
NAK to configuration; it would introduce too many potential points of failure for a benefit that would rarely get seen. Improving it could be looked at under #709.
