### ISSUE TITLE
TypeError: 'NoneType' object is not iterable using translate

### ISSUE THREAD

**Issue by fgsch** [sopel-irc/sopel#897]
@tr :jp :en kurasu
TypeError: 'NoneType' object is not iterable (file "../sopel/modules/translate.py", line 62, in translate)

sopel 6.0.0
python 2.7.9

**Comment by elad661** [comment]
Can you please provide the full stack trace? you can find it in exceptions.log in `~/.sopel/logs` or your configured logging location if you configured one.

**Comment by fgsch** [comment]
Sure:

Signature: TypeError: 'NoneType' object is not iterable (file "../sopel/modules/translate.py", line 62, in translate)
from xxx at 2015-09-22 11:02:29.672448. Message was: @tr :jp kurasu
Traceback (most recent call last):
  File "../sopel/bot.py", line 257, in call
    exit_code = func(sopel, trigger)
  File "../sopel/modules/translate.py", line 123, in tr2
    msg, src = translate(phrase, src, dest)
  File "../sopel/modules/translate.py", line 62, in translate
    return ''.join(x[0] for x in data[0]), language
TypeError: 'NoneType' object is not iterable

**Comment by maxpowa** [comment]
'jp' is not the abbreviation for japanese, 'ja' is. The error should probably be a bit cleaner, and I've also found that the google translate APIs don't appear to do anything to romanized text, it only translates text with japanese characters.

**Comment by fgsch** [comment]
Thanks for looking into it.
If romanized input is not supported and the error is fixed it should be ok to close this.

**Comment by maxpowa** [comment]
@embolalia this can probably be closed, since #940 was merged.
