### ISSUE TITLE
Feature: Search - Swiftype search engine - free single website/app installation

### ISSUE THREAD

**Issue by randomessence** [sopel-irc/sopel#907]
**Note:** The idea of an official feature is not so important, it was more to share it with anyone who wanted to implement it manually by leaving it here.

[https://swiftype.com/](https://swiftype.com/) - A custom search engine.

I have been using this for a while in place of the google search and it works well for something like 1000 search a month. You still need to register and get an api key and stuff but after that it just works.

The search code:

These are the tree things you need modify with your personal information. The Swiftype docs are dynamic so you should see your personal info as you look at the docs.

`uri =` The URL to your search
`auth_token=` Your auth token
`engine_key=` Your engine key

~~~
def custom_api_swift(query):
    uri = 'https://api.swiftype.com/api/v1/engines/mysearch/search.json'
    args = '?auth_token=tokengoeshere&engine_key=enginekeygoeshere&per_page=1&q=' + query
    bytes = web.get(uri + args)
    return json.loads(bytes)


def custom_search_swift(query):
    results = custom_api_swift(query)
    try:
        return results['records']['page'][0]['sections'][1] + ' -- ' + results['records']['page'][0]['url']
    except IndexError:
        return None
    except TypeError:
        return False
~~~

The trigger

~~~
@commands('s')
@example('.s apache')
def s(bot, trigger):
    query = trigger.group(2)
    if not query:
        return bot.reply('.s what? for example: .s apache')
    uri = custom_search_swift(query)
    if uri:
        bot.say(uri)
        if 'last_seen_url' in bot.memory:
            bot.memory['last_seen_url'][trigger.sender] = uri
    elif uri is False:
        bot.reply("Problem getting data from Swiftype.")
    else:
        bot.reply("No results found for '%s'." % query)
~~~

**Comment by elad661** [comment]
Well, it requires an api token to be functional, which is not something we want in the default module set, and it's an uncommon search engine that not many people use... so this shouldn't be in the default module set.

If you want to turn this code into a module you can share with other people, feel free to use [sopel-cookiecutter](https://github.com/sopel-irc/sopel-cookiecutter) to create a module template, put the code you pasted here in that template, and upload it to PyPi yourself as sopel-swiftype or something similar.
