### ISSUE TITLE
[Suggestion] Bringing back .yt

### ISSUE THREAD

**Issue by loliof** [sopel-irc/sopel#915]

**Comment by loliof** [comment]
There used to be a module for YouTube (.yt) which would search YouTube videos, however it was removed when YouTube started requiring an API key. I have been manually adding my own search method to the “search.py” module while just adds “site:youtube.com” to the search query, which will automatically search for the given term and limit it to youtube.com. This is a suggestion for how it could work, I don’t necessarily care if it’s implemented or not but this is what I have been adding to my “search.py” file after every release so I can still search YouTube videos.  


@commands('yt')
def yt(bot, trigger):
	br = Browser()
	query = str('site:youtube.com ' + trigger.group(2))
	if not query:
		return bot.reply('.yt what?')
    # If the API gives us something, say it and stop
	result = duck_api(query)
	if result:
		br.open(result)
		title = br.title()
		full = ("[" + str(title) + "] " +  str(result))
		bot.say(full)
		return
		
	uri = duck_search(query)
	if uri:
		br.open(uri)
		title = br.title()
		full = ("[" + str(title) + "] " +  str(uri))
		bot.say(full)
		if 'last_seen_url' in bot.memory:
			bot.memory['last_seen_url'][trigger.sender] = uri
	else:
		bot.reply("No results found for '%s'." % query)

**Comment by TheReverend403** [comment]
https://github.com/sopel-irc/sopel-youtube

**Comment by elad661** [comment]
Use https://github.com/sopel-irc/sopel-youtube

**Comment by loliof** [comment]
@elad661 @TheReverend403 Well then. Sorry about that :P
