### ISSUE TITLE
Reloading custom module: x not in list

### ISSUE THREAD

**Issue by joelwmale** [sopel-irc/sopel#919]
Trying to reload a custom module called "commands" however when i run "Sopel: reload commands"

I get: ValueError: list.remove(x): x not in list (file "/usr/local/lib/python2.7/dist-packages/sopel/bot.py", line 176, in unregister)

Any ideas?

**Comment by dasu** [comment]
I've seen this a few times as well.  Seems to mostly happen when I have an error in the module i'm reloading.  You can always quit sopel and start it up again to see if the module starts.

**Comment by embolalia** [comment]
Can you try this out with the latest release? I think I fixed this alongside some other stuff, but I want to confirm before closing this.

**Comment by joelwmale** [comment]
Haven't seen it in a few days now, will reopen if I see it again!
