### ISSUE TITLE
Regex match at end of line

### ISSUE THREAD

**Issue by pierg75** [sopel-irc/sopel#920]
In a module I'm using the following regex:
```
@rule(r'\b[\S]+\+\+')
```
This works if the match is within the line but if this is at the end of the line, it doesn't match it (the function for the rule is not executed).
This python code works normally:
```
>>> import re
>>> p = re.compile(ur'\b[\S]+\+\+')
>>> test_str = "ufskjhu ckkcs  ksma test111++"
>>> re.findall(p, test_str)
['test111++']
```
While the same line is not matched with sopel

**Comment by embolalia** [comment]
`@rule` uses `.match()`, so if you want it anywhere in the line it'll need to have `.*?` before it.
