### ISSUE TITLE
dft.ba shut down, should probably start replacing links sopel outputs

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#921]
This morning a bot user told me that the link to the tzdb list wasn't working. Apparently dft.ba is no longer accepting new short URLs. The site homepage says that old links should continue to work, but there are intermittent errors (I've seen 502 Bad Gateway several times in the last hour) and it's probably bad to rely on a service that's officially no longer supported.

I'd be happy to go through the code myself and submit a PR to just replace the short URLs with their long equivalents—since URL shorteners aren't really needed on IRC—but before I do so, I thought I'd ask if it would be preferable to set up URLs on sopel.chat or another domain that can be used instead. @embolalia, any thoughts?

**Comment by embolalia** [comment]
Just pushed 23ca3f5e56a6da63a0f92d15566e259af6d91c03, which refers people to http://sopel.chat/tz, which not only fixes this problem, but also makes it easier for people to find their timezone.

**Comment by dgw** [comment]
That's a great utility, and timezones do suck. Thanks!
