### ISSUE TITLE
Sopel.chat is down

### ISSUE THREAD

**Issue by maxpowa** [sopel-irc/sopel#922]
![](https://u.xpw.us/vi5qtb.png)

ping @embolalia

**Comment by dgw** [comment]
Still down. The actual error is "Connection refused", if I try to connect myself.

**Comment by embolalia** [comment]
The server got rebooted by the provider last night (on pretty short notice -_-). I don't have access from where I am right now, but I'll reboot it when I get back (around 19:00 EDT). In the mean time, all the content there is in either this repo or sopel-irc/sopel-website.
