### ISSUE TITLE
[web]Implement HTTP PUT

### ISSUE THREAD

**Issue by tyrope** [sopel-irc/sopel#934]
I was recently in a conversation with an API Dev who pointed out the difference between [POST](http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-21#section-5.3.3) and [PUT](http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-21#section-5.3.4).

I noticed the sopel.web package has no put() method.

**Comment by embolalia** [comment]
`web` is semi-deprecated. It's not going to be removed any time soon, but we're not doing new features for it. `requests` does a better job and is more complete, so that's recommended over `web`.
