### ISSUE TITLE
Python 3 incompatibility bug? TypeError: can't concat bytes to str

### ISSUE THREAD

**Issue by duk3luk3** [sopel-irc/sopel#937]
Using the admin module quit command running sopel on archlinux with python 3.5:

> ERROR:sopel.modules.sopel.irc:ERROR recieved from server: Closing Link: mechasqueak-test[p200300630A2FCF79AE220BFFFE4D6336.dip0.t-ipconnect.de] (Quit: Quitting on command from DukeOfEarl)
> Calling shutdown for 0 modules.
> Closed!
> Traceback (most recent call last):
>   File "/usr/lib64/python3.5/asyncore.py", line 83, in read
>     obj.handle_read_event()
>   File "/usr/lib64/python3.5/asyncore.py", line 423, in handle_read_event
>     self.handle_read()
>   File "/usr/lib64/python3.5/asynchat.py", line 126, in handle_read
>     self.ac_in_buffer = self.ac_in_buffer + data
> TypeError: can't concat bytes to str
> 
> ERROR:sopel.modules.sopel.irc:Fatal error in core, please review exception log

It seems there's a `decode()` missing.

**Comment by embolalia** [comment]
Hm, idk where that could be that it would blow up like that. There doesn't seem to be anything egregious wrong with that command…

**Comment by duk3luk3** [comment]
It required some pretty intense digging through asyncore to find the bug, but in the end it was pretty obvious.
