### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip' (file "/usr/local/lib/python2.7/dist-packages/sopel/modules/unicode_info.py", line 23, in codepoint)

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#957]
[01:04am] <Ant> .u
01:04AM <Sopel> AttributeError: 'NoneType' object has no attribute 'strip' (file "/usr/local/lib/python2.7/dist-packages/sopel/modules/unicode_info.py", line 23, in codepoint)
01:04AM <Sopel> Ant: Sopel v. 6.1.1

This is in my Debian oldstable with Python v2.7.3. :(

**Comment by dgw** [comment]
Ugh, force-push pollution. But that should keep it from spewing.
