### ISSUE TITLE
Error in url setup procedure - Bot no longer posts titles of links

### ISSUE THREAD

**Issue by nadeko** [sopel-irc/sopel#959]
Hello. I've actually had this error for awhile and tried fixing it awhile back to no avail so I'm hoping someone here could help. The bot no longer seems to show titles of links posted in the channels and when starting the bot I get:

```
Error in url setup procedure: nothing to repeat (../../../../../lib/python2.7/sre_parse.py:517)
```

Which looking at that file points to this:
```
            if not item or (_len(item) == 1 and item[0][0] == AT):
                raise error, "nothing to repeat"
```

So I'm not sure what to do here.

**Comment by embolalia** [comment]
Do you have an `exclusion_char` or `exclude` set under `[url]` in your config? My first guess is that it's set to something that's messing up the regex. Can you post the full traceback from `exceptions.log`?

**Comment by nadeko** [comment]
Thanks for responding. Yes, I do have both an exclusion_char and an exclude url. The exclusion_char is set to ! and the exclude is set to https?://example.net/.*   The weird thing is nothing shows up in the exceptions.log only when I start up the bot. Even with logging_level to debug no errors show up while running and nothing in the exceptions log, only the very first error at the beginning when the bot is initially ran.
