### ISSUE TITLE
Enum for numeric replies

### ISSUE THREAD

**Issue by embolalia** [sopel-irc/sopel#960]
It ought to be possible to do e.g. `@event(numerics.RPL_ISUPPORT)`, rather than having to see `@event('005')` and divine what it is. Since we still have 2.7 support, I imagine it'll look something like this in e.g. `sopel/tools/_numerics.py`:
```
class numerics(object):
    RPL_WELCOME = '001'
    RPL_YOURHOST = '002'
    …
```
And then in `sopel/tools/__init__.py`: `from sopel.tools._numerics import numerics  # NOQA` (keeping it in its own file so that it doesn't clutter up init with hundreds of constant definitions). [This list](https://www.alien.net.au/irc/irc2numerics.html) can be used (only non-deprecated ones without conflicts, i.e. blue) plus any numerics that might be in ircv3.

**Comment by elad661** [comment]
I think this should be called "events" or "irc events" or something like this, numerics is a bit too generic. 

And we can use https://pypi.python.org/pypi/enum34 or similar for backwards compatibility with Python 2.

**Comment by embolalia** [comment]
`events` is good, but idk if it might be confusing for things like `JOIN` to not be there? (Having all the non-numeric events there would just be way too much.) And for the time being, I'm still trying to avoid pypi dependencies in the core (and I'd like to be able to use these values in `coretasks`), so at least for now I think the simple class is the way to go.
