### ISSUE TITLE
"Warning: Couldn't load any modules" when loading only one module

### ISSUE THREAD

**Issue by fatalis** [sopel-irc/sopel#962]
[this line](https://github.com/sopel-irc/sopel/blob/e90a63f3faac2a43ce959e1d03a43bdbad4f142d/sopel/bot.py#L159) should be:
```
if len(modules) > 1:
```

how to reproduce in default.cfg
```
enable = weather
```
the module will function correctly but the startup message will say "Warning: Couldn't load any modules"

**Comment by elad661** [comment]
This should be fixed by 5610d8587ad81ce6db377c8ae7e001fc1b63160c
