### ISSUE TITLE
Say a preconfigured greeting upon joining a channel

### ISSUE THREAD

**Issue by Ganon11** [sopel-irc/sopel#967]
It would be fun if a Sopel admin could (optionally) define a greeting in the Config file that the bot would say upon joining a channel.

For instance, I run a Sopel instance that I've given the nick "WorfBot". A previous incarnation of WorfBot would say `I am WorfBot, son of MoghBot.` With this feature, I could define a setting such as `core.greeting` to be `I am WorfBot, son of MoghBot.`. If the greeting was undefined, no greeting would be used upon channel joining.

Similarly, a departure message might be fun, though used less often.

**Comment by maxpowa** [comment]
You can do that pretty easily with a plugin, just listen for event 'JOIN'
and trigger.nick == bot nick.

**Comment by dgw** [comment]
I'll publish a plugin that can do the join greeting tonight. Will look into how to do the part greeting then, if possible.

**Comment by Ganon11** [comment]
I also filled this issue with the intention of doing the change myself. I can either add a `greeting` module, or modify `irc.py` to look for and say a greeting in `join`

**Comment by maxpowa** [comment]
In my opinion it would be better as a module as it's not required for functionality of Sopel.

**Comment by Ganon11** [comment]
I have a module doing the join message properly. The parting message does not work, since by the time the 'PART' event happens, the bot has already parted the channel (thus the bot can't say a message to that channel).

I also realized that you can already give a part_message to the .part command, so this may not be needed. I'll prepare a pull request with the greeting module.

**Comment by embolalia** [comment]
While a few people might find this useful, I think a lot of others would find it unnecessary (or even spammy). The required configuration is also a problem for including in the mainline. The [general guideline](https://github.com/sopel-irc/sopel/wiki/Module-inclusion-guidelines) is not to allow this, because it makes setting the bot up harder.
