### ISSUE TITLE
Stuck for 4 minutes after receiving ERR_SASLFAIL

### ISSUE THREAD

**Issue by ProgVal** [sopel-irc/sopel#976]
Raw logs:

```
>>1450554176.3839703    CAP LS 302
>>1450554176.3842342    NICK Sopel
>>1450554176.3844688    USER sopel +iw Sopel :Sopel: http://sopel.chat
<<1450554176.3851945    CAP * LS :sasl=EXTERNAL
>>1450554176.3856113    CAP REQ multi-prefix
>>1450554176.3857372    CAP REQ sasl
<<1450554176.4237819    CAP Sopel NAK :multi-prefix
<<1450554176.463731 
<<1450554176.4646215    CAP Sopel ACK :sasl
>>1450554176.4651208    AUTHENTICATE PLAIN
<<1450554176.4657657    904 Sopel :SASL auth failed
<<1450554176.5035148    
>>1450554296.4777203    PING 0.0.0.0
```

Expected behavior: either `CAP END` or close the connection after `904` (`ERR_SASLFAIL`).

Config:

```
[core]
nick = Sopel
host = 0.0.0.0
use_ssl = false
port = 49200
owner = me
channels = 
auth_username = jilles
auth_password = sesame
auth_method = sasl
```

Version: 047a99ed2d3f76c7d54e5bacaac1c1d38d1b743c (Git master at the time I am writing this)

**Comment by Exirel** [comment]
That's an interesting bug to fix, but since it's from 2015 I can assume it's a "low priority".

**Comment by Exirel** [comment]
Thank you me from 2019, now I should take the time to fix that now that I know more about auth and stuff.

My guess is: after such event, Sopel should, indeed, report the issue and close the connection itself, with a big error message in the logs.
