### ISSUE TITLE
Key error when reloading a nonexistent module

### ISSUE THREAD

**Issue by embolalia** [sopel-irc/sopel#977]
`KeyError: 'time' (file "/opt/rh/python33/root/usr/lib/python3.3/site-packages/sopel/modules/reload.py", line 62, in f_reload)` should be a sane error message

**Comment by dgw** [comment]
I am not able to figure out how to reproduce this with Sopel 6.5.1. Either it's been fixed, or this is some kind of edge case that I'll need help tracking down to test a fix. Closing for now...
