### ISSUE TITLE
How to exclude time module from Sopel?

### ISSUE THREAD

**Issue by harrisontran** [sopel-irc/sopel#981]
I want to remove the `sopel.tools.time` module, so I have `exclude = sopel.tools.time` in the config file. However, the module is still loading when Sopel runs; am I formatting the config incorrectly?

**Comment by maxpowa** [comment]
http://sopel.chat/docs/#sopel.config.core_section.CoreSection.exclude

**Comment by embolalia** [comment]
I think you mean `sopel.modules.time`? For that you just want `exclude=time` under the `[core]` section.
