### ISSUE TITLE
Uninstalling Willie, but keeping Sopel in my Debian stable (Jessie).

### ISSUE THREAD

**Issue by antdude** [sopel-irc/sopel#982]
Hello.

I did a "pip uninstall willie", but it broke Sopel when starting him. So I had to uninstall Sopel and reinstalled him. It seems OK now. Is that all I need to do to remove Willie's left overs?

Thank you in advance. :)

**Comment by embolalia** [comment]
`pip uninstall willie` should get rid of all of Willie, with the exception of your `~/.willie` directory. I'm not sure why it would keep Sopel from starting. What's the error that you get?

**Comment by antdude** [comment]
It said something not found. I don't remember the exact wordings.

**Comment by antdude** [comment]
Hello. 

Why does Willie still exist in Pip when Sopel exists to replace it? Anyways, I was able to reproduce it too:

$ sudo pip uninstall willie
Uninstalling willie:
  /usr/local/bin/willie
  /usr/local/lib/python2.7/dist-packages/sopel/__init__.py
  /usr/local/lib/python2.7/dist-packages/sopel/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/willie-5.5.1.egg-info
  /usr/local/lib/python2.7/dist-packages/willie/__init__.py
  /usr/local/lib/python2.7/dist-packages/willie/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/willie/bot.py
  /usr/local/lib/python2.7/dist-packages/willie/bot.pyc
  /usr/local/lib/python2.7/dist-packages/willie/config/__init__.py
  /usr/local/lib/python2.7/dist-packages/willie/config/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/willie/config/core_section.py
  /usr/local/lib/python2.7/dist-packages/willie/config/core_section.pyc
  /usr/local/lib/python2.7/dist-packages/willie/config/types.py
  /usr/local/lib/python2.7/dist-packages/willie/config/types.pyc
  /usr/local/lib/python2.7/dist-packages/willie/coretasks.py
  /usr/local/lib/python2.7/dist-packages/willie/coretasks.pyc
  /usr/local/lib/python2.7/dist-packages/willie/db.py
  /usr/local/lib/python2.7/dist-packages/willie/db.pyc
  /usr/local/lib/python2.7/dist-packages/willie/formatting.py
  /usr/local/lib/python2.7/dist-packages/willie/formatting.pyc
  /usr/local/lib/python2.7/dist-packages/willie/irc.py
  /usr/local/lib/python2.7/dist-packages/willie/irc.pyc
  /usr/local/lib/python2.7/dist-packages/willie/logger.py
  /usr/local/lib/python2.7/dist-packages/willie/logger.pyc
  /usr/local/lib/python2.7/dist-packages/willie/module.py
  /usr/local/lib/python2.7/dist-packages/willie/module.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/__init__.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/admin.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/admin.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/adminchannel.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/adminchannel.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/announce.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/announce.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/bugzilla.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/bugzilla.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/calc.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/calc.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/clock.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/clock.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/countdown.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/countdown.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/currency.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/currency.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/dice.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/dice.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/etymology.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/etymology.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/find.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/find.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/find_updates.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/find_updates.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/github.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/github.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/help.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/help.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/ip.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/ip.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/ipython.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/ipython.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/isup.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/isup.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/lmgtfy.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/lmgtfy.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/meetbot.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/meetbot.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/movie.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/movie.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/ping.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/ping.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/radio.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/radio.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/rand.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/rand.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/reddit.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/reddit.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/reload.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/reload.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/remind.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/remind.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/rss.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/rss.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/safety.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/safety.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/search.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/search.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/seen.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/seen.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/spellcheck.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/spellcheck.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/tell.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/tell.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/tld.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/tld.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/translate.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/translate.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/unicode_info.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/unicode_info.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/units.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/units.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/uptime.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/uptime.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/url.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/url.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/version.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/version.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/weather.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/weather.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/wikipedia.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/wikipedia.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/wiktionary.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/wiktionary.pyc
  /usr/local/lib/python2.7/dist-packages/willie/modules/xkcd.py
  /usr/local/lib/python2.7/dist-packages/willie/modules/xkcd.pyc
  /usr/local/lib/python2.7/dist-packages/willie/test_tools.py
  /usr/local/lib/python2.7/dist-packages/willie/test_tools.pyc
  /usr/local/lib/python2.7/dist-packages/willie/tools/__init__.py
  /usr/local/lib/python2.7/dist-packages/willie/tools/__init__.pyc
  /usr/local/lib/python2.7/dist-packages/willie/tools/calculation.py
  /usr/local/lib/python2.7/dist-packages/willie/tools/calculation.pyc
  /usr/local/lib/python2.7/dist-packages/willie/tools/jobs.py
  /usr/local/lib/python2.7/dist-packages/willie/tools/jobs.pyc
  /usr/local/lib/python2.7/dist-packages/willie/tools/time.py
  /usr/local/lib/python2.7/dist-packages/willie/tools/time.pyc
  /usr/local/lib/python2.7/dist-packages/willie/trigger.py
  /usr/local/lib/python2.7/dist-packages/willie/trigger.pyc
  /usr/local/lib/python2.7/dist-packages/willie/web.py
  /usr/local/lib/python2.7/dist-packages/willie/web.pyc
Proceed (y/n)? y
  Successfully uninstalled willie
ant@ANTian:~/Downloads$ sudo gem clean^C
$ sopel -d
Traceback (most recent call last):
  File "/usr/local/bin/sopel", line 9, in <module>
    load_entry_point('sopel==6.2.1', 'console_scripts', 'sopel')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
ImportError: No module named sopel.run_script


I had to uninstall and reinstall Sopel. :(

**Comment by embolalia** [comment]
Some people may want older versions (since there are breaking changes between Willie and Sopel), so Willie will be in PyPI forever.

Regarding your error, what happens if you reinstall Sopel? Are you doing anything with virutalenv, or multiple python versions?

**Comment by antdude** [comment]
I did mention I reinstalled it to make it work again. That was with old Python v2.7. ;)

**Comment by embolalia** [comment]
You're installing with pip, not apt-get, right? When you reinstall, are you removing and then installing fresh, or just running pip install again?

**Comment by antdude** [comment]
Correct. I checked to see if apt-get even shows Willie and Sopel:


(SopelPython3)ant@Box:~/Downloads$ apt-cache show willie
N: Unable to locate package willie
E: No packages found
(SopelPython3)ant@Box:~/Downloads$ apt-cache show sopel
N: Unable to locate package sopel
E: No packages found
(SopelPython3)ant@Box:~/Downloads$

**Comment by elad661** [comment]
Well, I see the problem. The sopel forward compatibility layer in willie, which is `/usr/local/lib/python2.7/dist-packages/sopel/__init__.py`, overrides sopel itself.

Basically, this means willie and sopel conflict. You simply can't have both installed globally on the same system.

I don't think it's an issue, to be honest. If uninstalling willie and only then installing (or re-installing) sopel fixes the problem (which it does), then it's all good and you have nothing to worry about.

**Comment by antdude** [comment]
@embolalia  Ah, I thought we were trying to phase out Willie and replace with Sopel.

**Comment by elad661** [comment]
Willie is no more. Sopel is what you should be using now. Willie is like an old version of Sopel. We simply renamed the project.

Please read my comment again. You can't have willie and sopel exist at the same time on the same machine. Either you use sopel, or you use the old and unsupported willie. You can't have both.
