### ISSUE TITLE
failed to create process

### ISSUE THREAD

**Issue by harkenn** [sopel-irc/sopel#991]
Installed successfully, no errors or anything.

Ran `sopel` and immediately get "failed to create process"

Windows 10
Attempted in various shells (Git Bash, Powershell, and Cmd)

**Comment by embolalia** [comment]
I don't know much about how things work on Windows, but from some quick searching around it looks like if you moved the directory where Python is installed, that might make this happen? I'm not sure.

**Comment by harkenn** [comment]
If they're in the same directory you get this defect or it resolves this defect?

Python and sopel are in different paths on the same system, however python is on the Path so that it can be used easily via `python` in any shell.

**Comment by elad661** [comment]
Did you try running `python sopel.py`? I assume that just typing `sopel` will not work because our shabang is for POSIX-like systems and not for windows.

**Comment by badon** [comment]
I duplicated this bug in Windows 7:

>sopel
failed to create process.

This suggested workaround did not work:

>python sopel.py
python: can't open file 'sopel.py': [Errno 2] No such file or directory

This workaround DID work:

>python "C:\Program Files\Python 3.5\Scripts\sopel-script.py"
WARNING!!! You are running with a non-UTF8 locale environment variables (e.g. LC_ALL is set to "C"), which makes Python 3 do stupid things. If you get strange errors, please set it to something like "en_US.UTF-8".
WARNING!!! You are running with a non-UTF8 locale environment variables (e.g. LC_ALL is set to "C"), which makes Python 3 do stupid things. If you get strange errors, please set it to something like "en_US.UTF-8".
Welcome to Sopel!
I can't seem to find the configuration file, so let's generate it!

Creating a config directory at ~/.sopel...
Please answer the following questions to create your configuration file:

Enter the nickname for your bot. [Sopel]

**Comment by elad661** [comment]
Honestly, this is not a workaround because this is not a bug. It makes sense that just typing "sopel" in a Windows system will not work. I don't even know if Windows bothers to process the shabang, and even if it does the path there is POSIX-ish, and not Windows-ish. Windows also treats PATH and unlike in POSIX-ish systems, it's uncommon for Windows apps to all be in your PATH.

Simply continue running sopel by doing `python3 sopel.py` or `python sopel.py`.

**Comment by badon** [comment]
Then the tutorial documentation is where I encountered this bug:

https://github.com/sopel-irc/sopel/wiki/Sopel-tutorial,-Part-1

I'm not sure where harkenn found his particular incarnation of this bug.

**Comment by elad661** [comment]
In my opinion, knowing how to use your OS is a prerequisite to using Sopel.

**Comment by badon** [comment]
Right, and I'm a blubbering monkey. Don't listen to me.

**Comment by elad661** [comment]
This is not at all what I just said. There's no need for this kind of language here.
