### ISSUE TITLE
IRC ping module

### ISSUE THREAD

**Issue by madprops** [sopel-irc/sopel#992]
It would be nice to have a real ping module, for example.

madprops> .ping

* Received a CTCP PING 1452310049.35 from kindbot

<kindbot> [PING] madprops: 540.019989014 ms

**Comment by maxpowa** [comment]
I mentioned this in IRC but putting it here too, I've built this functionality into my third party ping module. Not sure if the feature is really needed in core. https://github.com/maxpowa/inumuta-modules/commit/1e64323147acab74573953993fc7ed3e3b461e0e

**Comment by madprops** [comment]
maxpowa's solution works but I made some modifications to make it work more like I wanted. Instead of pinging a specific username, you can just .ping and it will show the result, in the same channel. http://gsick.com/paste/17/
