### ISSUE TITLE
KeyError when using adminchannel commands in PM

### ISSUE THREAD

**Issue by hunter688** [sopel-irc/sopel#997]
when try some admin commands, bot throw exception:

KeyError: Identifier('MyNickname') (file "/usr/lib/python2.7/site-packages/sopel-6.1.1-py2.7.egg/sopel/module.py", line 335, in guarded)

in the default.cfg is line:

owner = MyNickname

**Comment by hunter688** [comment]
exception.log:

Signature: KeyError: Identifier('MyNickname') (file "/usr/lib/python2.7/site-packages/sopel-6.1.1-py2.7.egg/sopel/module.py", line 335, in guarded)
from MyNickname at 2016-01-12 14:03:23.547792. Message was: .topic test
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/sopel-6.1.1-py2.7.egg/sopel/bot.py", line 260, in call
    exit_code = func(sopel, trigger)
  File "/usr/lib/python2.7/site-packages/sopel-6.1.1-py2.7.egg/sopel/module.py", line 335, in guarded
    channel_privs = bot.privileges[trigger.sender]
KeyError: Identifier('MyNickname')

**Comment by maxpowa** [comment]
This issue has already been fixed in master, you should see this problem go away in 6.1.2 or 6.2.0 (whichever comes first). For now, do not use adminchannel commands in PM with the bot, only use them in channels themselves.

**Comment by hunter688** [comment]
updated from git, no errors, but bot still ignore me...
Cannot use admin/owners commands...

**Comment by hunter688** [comment]
How can owner take control over bot after fresh install ?

**Comment by embolalia** [comment]
Which commands are you using exactly? There's a difference between bot admins and channel operators. Admin channel doesn't do anything for the bot admins. I've just removed a few of the more useless commands from there (they were relevant a way long time ago, but not anymore) and added some better error messages for the remainder. Could you try again from master?

**Comment by hunter688** [comment]
for example .op, .topic
now using supybot, which need identify user via ip, ident etc.
