### ISSUE TITLE
[dice] Any particular reason .choice doesn't split on commas?

### ISSUE THREAD

**Issue by dgw** [sopel-irc/sopel#998]
Usually the first time I see people try to use `.choice`, they try to separate the options with commas. That just spits the whole list back at them, and they think Sopel is dumb.

Is there any reason not to add `,` to the accepted delimiters?

**Comment by maxpowa** [comment]
I'd guess that it's because the help text doesn't give any indication that commas would be accepted.
```
<maxpowa> .help choice
<Sopel> maxpowa: .choice option1|option2|option3 - Makes a difficult choice easy.

**Comment by embolalia** [comment]
It looks like @tyrope did this [here](https://github.com/sopel-irc/sopel/commit/c73d394a783605c0538ae3c0cf0727715426dcce), but I'm not sure why comma wasn't made part of it. I guess it's probably to prevent natural language weirdness? Like, if you do `.choice eats, shoots, and leaves | eats shoots and leaves`, you'd get the same as `.choice eats, shoots, and leaves, eats shoots and leaves`, which is unexpected. What I'll do is have a preference order, where it tries splitting on `|`, then `\`, then `/`, then `,`, only continuing to the next possibility if it can't split it. That *should* avoid the most likely ambiguities.

**Comment by dgw** [comment]
:+1: Thanks, @embolalia!
